// GENERATED by scripts/edge-kernels.mjs from src/lib/gc/promises.ts. Do not edit: change the file in src and run
// `npm run gen:edge-kernels`. Imported by gc-trade-portal (the schedule's PR 14b).
/**
 * GC mode, the real build: the dates a company gave us for things other than a quote, moved word for word from the GC mode prototype
 * (branch spike/gc-mode, `gcPromises.ts`): `INSURANCE_ASK_DAYS` by the schedule's PR 1b, the rest by the Board's B2. Two stay on the
 * spike, `promisesKeptBy` and `keepPromisesOn`, which read the prototype's actions: on main the write that keeps a promise calls
 * `gc_keep_promises` in its own transaction.
 */

import type { PromiseState } from './followUp.ts'
import { partnerById } from './lookups.ts'
import type { GcState, Partner, PromiseKind, TradePromise } from '../../../../../../src/lib/gc/types'
import { daysUntil, shortDate, weekdayDate } from './words.ts'

/** Ask for the renewed certificate this many days before the policy runs out. */
export const INSURANCE_ASK_DAYS = 30

/** What each kind is, in a few words, when the office does not say. */
export const PROMISE_WHAT: Record<PromiseKind, string> = {
  insurance: 'the renewed insurance certificate',
  w9: 'a signed W-9',
  sow: 'the signed statement of work',
  start: 'their crew on site',
  submittals: 'their submittals',
  delivery: 'the material delivery',
  payApp: 'the fixed pay application',
  punch: 'the punch items fixed',
  closeout: 'their closeout papers',
  msa: 'the signed master agreement',
}

export function tradePromisesOf(state: GcState): TradePromise[] {
  return state.tradePromises ?? []
}

/** Where a promise stands, the way a quote date does (gcFollowUp's `PromiseState`). */
export function tradePromiseState(p: TradePromise, today: string): { state: PromiseState; days: number } {
  if (p.keptOn) {
    const late = daysUntil(p.keptOn, p.by)
    return { state: late <= 0 ? 'kept' : 'late', days: Math.max(0, late) }
  }
  const until = daysUntil(p.by, today)
  return { state: until > 0 ? 'pending' : until === 0 ? 'today' : 'passed', days: Math.abs(until) }
}

/** "Promised the renewed insurance certificate by Fri Oct 9. That was 2 days ago." */
export function tradePromiseWords(p: TradePromise, today: string): string {
  const { state, days } = tradePromiseState(p, today)
  const day = weekdayDate(p.by)
  const n = `${days} ${days === 1 ? 'day' : 'days'}`
  if (state === 'kept') return `Kept their word: ${p.what} came by ${day}.`
  if (state === 'late') return `${capital(p.what)} came ${n} after their ${day}.`
  if (state === 'pending') return `Promised ${p.what} by ${day}, in ${n}.`
  if (state === 'today') return `Promised ${p.what} today.`
  return `Promised ${p.what} by ${day}. That was ${n} ago.`
}

function capital(words: string): string {
  return words.charAt(0).toUpperCase() + words.slice(1)
}

/** The open promise for the same thing: same company, kind, job and trade. */
export function openPromiseFor(
  state: GcState,
  match: { partnerId: string; kind: PromiseKind; projectId?: string; packageId?: string },
): TradePromise | undefined {
  return tradePromisesOf(state).find(
    (p) =>
      !p.keptOn &&
      p.partnerId === match.partnerId &&
      p.kind === match.kind &&
      (p.projectId ?? null) === (match.projectId ?? null) &&
      (p.packageId ?? null) === (match.packageId ?? null),
  )
}

/**
 * How often a company's other promises held, for its word record: one kept by its day counts made
 * and kept; one that came late, or whose day passed, counts made only. A day they moved before it
 * came does not count.
 */
export function tradePromiseRecord(state: GcState, partner: Partner): { made: number; kept: number } {
  let made = 0
  let kept = 0
  for (const p of tradePromisesOf(state)) {
    if (p.partnerId !== partner.id) continue
    for (const old of p.moved ?? []) if (daysUntil(old.on, old.by) > 0) made += 1
    const { state: s } = tradePromiseState(p, state.today)
    if (s === 'kept') {
      made += 1
      kept += 1
    } else if (s === 'late' || s === 'passed') made += 1
  }
  return { made, kept }
}

/** A company whose insurance runs out within `INSURANCE_ASK_DAYS` (or ran out), and the days left. */
export interface InsuranceRenewal {
  partner: Partner
  expires: string
  /** Negative: it ran out that many days ago. */
  days: number
  /** The date they gave for the new certificate, if they gave one. */
  promise: TradePromise | undefined
}

/** Every renewal to chase, the soonest (or longest gone) first. A declined company is left out. */
export function insuranceRenewals(state: GcState): InsuranceRenewal[] {
  const out: InsuranceRenewal[] = []
  for (const partner of state.partners) {
    if (!partner.coiExpires || partner.vetting?.status === 'declined') continue
    const days = daysUntil(partner.coiExpires, state.today)
    if (days > INSURANCE_ASK_DAYS) continue
    out.push({ partner, expires: partner.coiExpires, days, promise: openPromiseFor(state, { partnerId: partner.id, kind: 'insurance' }) })
  }
  return out.sort((a, b) => a.days - b.days)
}

/** "Their insurance runs out Tue Oct 20, in 16 days." · "Their insurance ran out Sep 30." */
export function insuranceRenewalWords(r: InsuranceRenewal): string {
  if (r.days < 0) return `Their insurance ran out ${shortDate(r.expires)}. Nothing they do for us is covered.`
  if (r.days === 0) return 'Their insurance runs out today.'
  return `Their insurance runs out ${weekdayDate(r.expires)}, in ${r.days} ${r.days === 1 ? 'day' : 'days'}.`
}

/** The partner a promise is with, for the words around it. */
export function promisePartner(state: GcState, p: TradePromise): Partner | undefined {
  return partnerById(state, p.partnerId)
}

/**
 * Papers the Board's kinds wait on (question 8): a company awarded on a live job with no W-9, and a
 * statement of work sent and not signed. Each carries the date they gave, if they gave one.
 */
export interface PaperAsk {
  kind: 'w9' | 'sow'
  partner: Partner
  projectId?: string
  packageId?: string
  /** "No W-9 on file." · "The HVAC statement of work on Helotes Dental Office is waiting on their signature." */
  words: string
  promise: TradePromise | undefined
}

export function paperAsks(state: GcState): PaperAsk[] {
  const out: PaperAsk[] = []
  const askedW9 = new Set<string>()
  for (const project of state.projects) {
    if (project.closedOn || project.lostOn) continue
    for (const pkg of project.packages) {
      const partnerId = pkg.invites.find((i) => i.id === pkg.awardedInviteId)?.partnerId
      const partner = partnerId ? partnerById(state, partnerId) : undefined
      if (!partner) continue
      if (!partner.w9 && !askedW9.has(partner.id)) {
        askedW9.add(partner.id)
        out.push({ kind: 'w9', partner, words: 'No W-9 on file.', promise: openPromiseFor(state, { partnerId: partner.id, kind: 'w9' }) })
      }
      if (pkg.sow?.status === 'sent') {
        const match = { partnerId: partner.id, kind: 'sow' as const, projectId: project.id, packageId: pkg.id }
        out.push({
          ...match,
          partner,
          words: `The ${pkg.trade} statement of work on ${project.name} is waiting on their signature.`,
          promise: openPromiseFor(state, match),
        })
      }
    }
  }
  return out
}

/** Open promises whose day came or passed, and lapsed insurance with no new date: the Follow up badge adds these. */
export function promisesToChase(state: GcState): number {
  const due = tradePromisesOf(state).filter((p) => {
    const s = tradePromiseState(p, state.today).state
    return s === 'passed' || s === 'today'
  }).length
  const lapsed = insuranceRenewals(state).filter((r) => r.days <= 0 && !r.promise).length
  return due + lapsed
}
