// GENERATED by scripts/edge-kernels.mjs from src/lib/gc/words.ts. Do not edit: change the file in src and run
// `npm run gen:edge-kernels`. Imported by gc-trade-portal (the schedule's PR 14b).
/**
 * GC mode, the real build: dates in words, moved word for word from the GC mode prototype (branch
 * spike/gc-mode, `gcWords.ts`) by the schedule's PR 1a, and the days until a date by PR 1b. Every
 * lane's kernels write dates this way.
 */

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

export function shortDate(iso: string | null): string {
  if (!iso) return ''
  const [, m, d] = iso.split('-')
  const month = MONTHS[Number(m) - 1]
  return month ? `${month} ${Number(d)}` : iso
}

const WEEKDAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']

/** "Wed Oct 8": the day of the week with the date, for a due date an estimator plans a week around. */
export function weekdayDate(iso: string | null): string {
  if (!iso) return ''
  const [y, m, d] = iso.split('-').map(Number)
  const day = WEEKDAYS[new Date(Date.UTC(y ?? 1970, (m ?? 1) - 1, d ?? 1)).getUTCDay()]
  return `${day} ${shortDate(iso)}`
}

function utcDay(iso: string): number {
  const [y, m, d] = iso.split('-').map(Number)
  return Date.UTC(y ?? 1970, (m ?? 1) - 1, d ?? 1) / 86_400_000
}

export function daysUntil(iso: string, today: string): number {
  return Math.round(utcDay(iso) - utcDay(today))
}

export function money(n: number): string {
  return `$${Math.round(n).toLocaleString('en-US')}`
}
