import globals from 'globals'
import tseslint from 'typescript-eslint'
import react from 'eslint-plugin-react'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import prettier from 'eslint-config-prettier'

export default tseslint.config(
  {
    ignores: [
      'dist',
      'dev-dist',
      'node_modules',
      'public',
      'tsconfig.tsbuildinfo',
      // Generated by Supabase; not worth linting.
      'src/types/database.ts',
      '*.config.js',
      '*.config.ts',
    ],
  },
  ...tseslint.configs.recommended,
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2020,
      globals: { ...globals.browser, ...globals.node },
    },
    settings: { react: { version: 'detect' } },
    plugins: {
      react,
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      // The high-value rules tsc cannot catch.
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
      // Defined so existing `eslint-disable react/no-danger` directives resolve.
      'react/no-danger': 'warn',
      // Start noisy rules as warnings; ratchet to error later.
      '@typescript-eslint/no-explicit-any': 'warn',
      'prefer-const': 'warn',
      // TS already enforces this via noUnusedLocals / noUnusedParameters.
      '@typescript-eslint/no-unused-vars': 'off',
    },
  },
  prettier,
)
