/**
 * Test data only: the app never reads it. It is the GC mode prototype's made-up data
 * (`initialGcState` in `gcFixture.ts`, branch spike/gc-mode), cut to the fields main's GC kernels
 * read (`../types.ts` and `./types.ts`). Written by to-dos/gc-mode/scripts/schedule-test-state.ts on
 * the spike, never by hand; the spike's test holds the two equal.
 */
import type { GcState } from '../types'

const DATA: GcState = {
  today: '2026-10-02',
  customers: [
    { id: 'cibolo', name: 'Cibolo Creek Partners' },
    { id: 'raman', name: 'Dr. Priya Raman' },
    { id: 'marshvale', name: 'Marsh & Vale Architects' },
    { id: 'ocotillo', name: 'Studio Ocotillo' },
    { id: 'hollis', name: 'Hollis Family Pharmacy' },
    { id: 'mesquite', name: 'Mesquite Design Studio' },
  ],
  projects: [
    {
      id: 'boerne',
      name: 'Boerne Retail Shell',
      address: '1420 River Rd, Boerne',
      town: 'Boerne',
      ourBidSentOn: null,
      startedOn: null,
      customerId: 'cibolo',
      owner: 'Cibolo Creek Partners',
      stage: 'pursuing',
      bidDue: '2026-10-08',
      planSets: [{ rev: 0, touches: [] }, { rev: 1, touches: ['elec', 'hvac', 'plumb'] }],
      packages: [
        {
          id: 'site',
          trade: 'Sitework',
          budget: 185000,
          carried: 'site-lonestar',
          scope: [
            { id: 'site-1', label: 'Clearing and grading' },
            { id: 'site-2', label: 'Utilities to 5 ft of the building' },
            { id: 'site-3', label: 'Paving' },
            { id: 'site-4', label: 'Striping and signs' },
          ],
          invites: [
            {
              id: 'site-lonestar',
              partnerId: 'lonestar',
              status: 'bid',
              invitedOn: '2026-09-19',
              bid: {
                amount: 178400,
                basedOnRev: 1,
                submittedOn: '2026-09-30',
                includes: { 'site-1': 'yes', 'site-2': 'yes', 'site-3': 'yes', 'site-4': 'no' },
                plugs: { 'site-4': 6500 },
              },
            },
            {
              id: 'site-tricounty',
              partnerId: 'tricounty',
              status: 'bid',
              invitedOn: '2026-09-19',
              bid: {
                amount: 191000,
                basedOnRev: 1,
                submittedOn: '2026-10-01',
                includes: { 'site-1': 'yes', 'site-2': 'yes', 'site-3': 'yes', 'site-4': 'yes' },
                plugs: {},
              },
            },
            {
              id: 'site-hillside',
              partnerId: 'hillside',
              status: 'opened',
              invitedOn: '2026-09-19',
              bid: null,
              contacts: [
                {
                  on: '2026-09-26',
                  by: 'Robert',
                  how: 'call',
                  note: 'Greg is busy on a subdivision. Says he will price it by Wednesday.',
                  promisedBy: '2026-09-30',
                },
              ],
            },
          ],
          awardedInviteId: null,
          selfPerform: null,
          sow: null,
        },
        {
          id: 'conc',
          trade: 'Concrete',
          budget: 212000,
          carried: 'conc-guadalupe',
          scope: [
            { id: 'conc-1', label: 'Foundations' },
            { id: 'conc-2', label: 'Slab on grade' },
            { id: 'conc-3', label: 'Sidewalks and curbs' },
            { id: 'conc-4', label: 'Rebar supply' },
          ],
          invites: [
            {
              id: 'conc-alamo',
              partnerId: 'alamo',
              status: 'bid',
              invitedOn: '2026-09-19',
              bid: {
                amount: 205500,
                basedOnRev: 1,
                submittedOn: '2026-09-30',
                includes: { 'conc-1': 'yes', 'conc-2': 'yes', 'conc-3': 'yes', 'conc-4': 'unclear' },
                plugs: {},
              },
            },
            {
              id: 'conc-guadalupe',
              partnerId: 'guadalupe',
              status: 'bid',
              invitedOn: '2026-09-19',
              bid: {
                amount: 219800,
                basedOnRev: 1,
                submittedOn: '2026-10-01',
                includes: { 'conc-1': 'yes', 'conc-2': 'yes', 'conc-3': 'yes', 'conc-4': 'yes' },
                plugs: {},
              },
            },
          ],
          awardedInviteId: null,
          selfPerform: null,
          sow: null,
        },
        {
          id: 'steel',
          trade: 'Structural steel',
          budget: 164000,
          carried: null,
          scope: [
            { id: 'steel-1', label: 'Structural steel' },
            { id: 'steel-2', label: 'Joists and deck' },
            { id: 'steel-3', label: 'Erection' },
          ],
          invites: [
            { id: 'steel-bexar', partnerId: 'bexar', status: 'invited', invitedOn: '2026-09-19', bid: null },
            { id: 'steel-comal', partnerId: 'comal', status: 'declined', invitedOn: '2026-09-19', bid: null },
          ],
          awardedInviteId: null,
          selfPerform: null,
          sow: null,
        },
        {
          id: 'roof',
          trade: 'Roofing',
          budget: 118000,
          carried: 'roof-summit',
          scope: [
            { id: 'roof-1', label: 'TPO membrane' },
            { id: 'roof-2', label: 'Insulation' },
            { id: 'roof-3', label: 'Sheet metal and flashing' },
            { id: 'roof-4', label: 'Roof curbs' },
          ],
          invites: [
            {
              id: 'roof-summit',
              partnerId: 'summit',
              status: 'bid',
              invitedOn: '2026-09-19',
              bid: {
                amount: 112300,
                basedOnRev: 1,
                submittedOn: '2026-09-28',
                includes: { 'roof-1': 'yes', 'roof-2': 'yes', 'roof-3': 'yes', 'roof-4': 'no' },
                plugs: {},
              },
            },
            {
              id: 'roof-bluebonnet',
              partnerId: 'bluebonnet',
              status: 'opened',
              invitedOn: '2026-09-19',
              bid: null,
              contacts: [
                {
                  on: '2026-09-30',
                  by: 'Robert',
                  how: 'call',
                  note: 'Wes has the plans open. He will have a number Monday.',
                  promisedBy: '2026-10-05',
                },
                { on: '2026-09-24', by: 'Robert', how: 'email', note: 'Sent the roof plan and the spec section again.' },
              ],
            },
          ],
          awardedInviteId: null,
          selfPerform: null,
          sow: null,
        },
        {
          id: 'plumb',
          trade: 'Plumbing',
          budget: 86400,
          carried: 'self',
          scope: [
            { id: 'plumb-1', label: 'Underground' },
            { id: 'plumb-2', label: 'Rough in' },
            { id: 'plumb-3', label: 'Top out' },
            { id: 'plumb-4', label: 'Trim' },
          ],
          invites: [],
          awardedInviteId: null,
          selfPerform: { ref: 'BP 512', value: 86400, note: 'Our own bid, priced in Trades mode.' },
          sow: null,
        },
        {
          id: 'hvac',
          trade: 'HVAC',
          budget: 142000,
          carried: null,
          scope: [
            { id: 'hvac-1', label: 'Rooftop units' },
            { id: 'hvac-2', label: 'Ductwork' },
            { id: 'hvac-3', label: 'Controls' },
            { id: 'hvac-4', label: 'Test and balance' },
          ],
          invites: [
            {
              id: 'hvac-coolbreeze',
              partnerId: 'coolbreeze',
              status: 'bid',
              invitedOn: '2026-09-19',
              bid: {
                amount: 148900,
                basedOnRev: 0,
                submittedOn: '2026-09-25',
                includes: { 'hvac-1': 'yes', 'hvac-2': 'yes', 'hvac-3': 'yes', 'hvac-4': 'yes' },
                plugs: {},
              },
              contacts: [
                {
                  on: '2026-09-22',
                  by: 'Robert',
                  how: 'call',
                  note: 'Andre will quote by Friday the 26th.',
                  promisedBy: '2026-09-26',
                },
              ],
            },
            {
              id: 'hvac-kendall',
              partnerId: 'kendall',
              status: 'bid',
              invitedOn: '2026-09-19',
              bid: {
                amount: 139200,
                basedOnRev: 1,
                submittedOn: '2026-10-01',
                includes: { 'hvac-1': 'yes', 'hvac-2': 'yes', 'hvac-3': 'yes', 'hvac-4': 'no' },
                plugs: { 'hvac-4': 4800 },
              },
            },
          ],
          awardedInviteId: null,
          selfPerform: null,
          sow: null,
        },
        {
          id: 'elec',
          trade: 'Electrical',
          budget: 171000,
          carried: null,
          scope: [
            { id: 'elec-1', label: 'Service and gear' },
            { id: 'elec-2', label: 'Panels and feeders' },
            { id: 'elec-3', label: 'Lighting' },
            { id: 'elec-4', label: 'Fire alarm' },
            { id: 'elec-5', label: 'Site lighting' },
          ],
          invites: [
            {
              id: 'elec-voltage',
              partnerId: 'voltage',
              status: 'bid',
              invitedOn: '2026-09-19',
              bid: {
                amount: 166000,
                basedOnRev: 0,
                submittedOn: '2026-09-26',
                includes: { 'elec-1': 'yes', 'elec-2': 'yes', 'elec-3': 'yes', 'elec-4': 'no', 'elec-5': 'yes' },
                plugs: { 'elec-4': 14000 },
              },
            },
            {
              id: 'elec-brightline',
              partnerId: 'brightline',
              status: 'bid',
              invitedOn: '2026-09-19',
              bid: {
                amount: 182500,
                basedOnRev: 1,
                submittedOn: '2026-10-01',
                includes: { 'elec-1': 'yes', 'elec-2': 'yes', 'elec-3': 'yes', 'elec-4': 'yes', 'elec-5': 'yes' },
                plugs: {},
              },
            },
            {
              id: 'elec-tejas',
              partnerId: 'tejas',
              status: 'opened',
              invitedOn: '2026-09-19',
              bid: null,
              contacts: [
                {
                  on: '2026-10-01',
                  by: 'Wendi',
                  how: 'text',
                  note: 'Bill texted back: quote by end of day Friday.',
                  promisedBy: '2026-10-02',
                },
              ],
            },
          ],
          awardedInviteId: null,
          selfPerform: null,
          sow: null,
        },
        {
          id: 'fire',
          trade: 'Fire sprinkler',
          budget: 44000,
          carried: null,
          scope: [
            { id: 'fire-1', label: 'Design and permit' },
            { id: 'fire-2', label: 'Mains and branch lines' },
            { id: 'fire-3', label: 'Heads and trim' },
          ],
          invites: [],
          awardedInviteId: null,
          selfPerform: null,
          sow: null,
        },
      ],
      generalConditions: 138000,
      contingencyPct: 3,
      feePct: 8,
      team: [
        {
          role: 'projectManager',
          name: 'Dana Whitaker',
          phone: '(210) 555-0131',
          email: 'dana@clickconstruction.example',
        },
      ],
    },
    {
      id: 'padb',
      name: 'Boerne Retail Pad B',
      address: '1436 River Rd, Boerne',
      town: 'Boerne',
      ourBidSentOn: null,
      startedOn: null,
      customerId: 'cibolo',
      owner: 'Cibolo Creek Partners',
      stage: 'pursuing',
      bidDue: '2026-10-22',
      planSets: [{ rev: 0, touches: [] }],
      packages: [
        {
          id: 'bsite',
          trade: 'Sitework',
          budget: 96000,
          carried: null,
          scope: [
            { id: 'bsite-1', label: 'Clearing and grading' },
            { id: 'bsite-2', label: 'Utilities to 5 ft of the building' },
            { id: 'bsite-3', label: 'Paving' },
          ],
          invites: [],
          awardedInviteId: null,
          selfPerform: null,
          sow: null,
        },
        {
          id: 'bconc',
          trade: 'Concrete',
          budget: 118000,
          carried: null,
          scope: [
            { id: 'bconc-1', label: 'Foundations' },
            { id: 'bconc-2', label: 'Slab on grade' },
            { id: 'bconc-3', label: 'Drive-through lane' },
          ],
          invites: [],
          awardedInviteId: null,
          selfPerform: null,
          sow: null,
        },
        {
          id: 'bplumb',
          trade: 'Plumbing',
          budget: 61000,
          carried: 'self',
          scope: [
            { id: 'bplumb-1', label: 'Underground' },
            { id: 'bplumb-2', label: 'Rough in' },
            { id: 'bplumb-3', label: 'Top out' },
            { id: 'bplumb-4', label: 'Trim' },
          ],
          invites: [],
          awardedInviteId: null,
          selfPerform: { ref: 'BP 518', value: 61000, note: 'Our own bid, priced in Trades mode.' },
          sow: null,
        },
      ],
      generalConditions: 74000,
      contingencyPct: 5,
      feePct: 8,
      team: [
        {
          role: 'projectManager',
          name: 'Dana Whitaker',
          phone: '(210) 555-0131',
          email: 'dana@clickconstruction.example',
        },
      ],
    },
    {
      id: 'helotes',
      name: 'Helotes Dental Office',
      address: '9811 Bandera Rd, Suite 140, Helotes',
      town: 'Helotes',
      ourBidSentOn: '2026-08-27',
      startedOn: null,
      customerId: 'raman',
      owner: 'Dr. Priya Raman',
      stage: 'buyout',
      bidDue: null,
      planSets: [{ rev: 0, touches: [] }],
      packages: [
        {
          id: 'dry',
          trade: 'Framing and drywall',
          budget: 66000,
          carried: 'dry-hillcountry',
          scope: [
            { id: 'dry-1', label: 'Framing' },
            { id: 'dry-2', label: 'Hang and tape' },
            { id: 'dry-3', label: 'Ceilings' },
          ],
          invites: [
            {
              id: 'dry-hillcountry',
              partnerId: 'hillcountry',
              status: 'bid',
              invitedOn: '2026-09-19',
              bid: {
                amount: 64200,
                basedOnRev: 0,
                submittedOn: '2026-08-20',
                includes: { 'dry-1': 'yes', 'dry-2': 'yes', 'dry-3': 'yes' },
                plugs: {},
              },
            },
          ],
          awardedInviteId: 'dry-hillcountry',
          selfPerform: null,
          sow: {
            status: 'signed',
            price: 64200,
            sov: [
              { id: 'dry-1', label: 'Framing', amount: 22000, pctReported: 100, pctBilled: 100 },
              { id: 'dry-2', label: 'Hang and tape', amount: 27200, pctReported: 60, pctBilled: 0 },
              { id: 'dry-3', label: 'Ceilings', amount: 15000, pctReported: 0, pctBilled: 0 },
            ],
            draws: [{ number: 1, retainage: 2200, net: 19800, status: 'paid', waiver: 'unconditional' }],
          },
        },
        {
          id: 'delec',
          trade: 'Electrical',
          budget: 58000,
          carried: 'delec-brightline',
          scope: [
            { id: 'delec-1', label: 'Panels and feeders' },
            { id: 'delec-2', label: 'Lighting' },
            { id: 'delec-3', label: 'Devices' },
            { id: 'delec-4', label: 'Low voltage rough' },
          ],
          invites: [
            {
              id: 'delec-brightline',
              partnerId: 'brightline',
              status: 'bid',
              invitedOn: '2026-09-19',
              bid: {
                amount: 56900,
                basedOnRev: 0,
                submittedOn: '2026-08-21',
                includes: { 'delec-1': 'yes', 'delec-2': 'yes', 'delec-3': 'yes', 'delec-4': 'yes' },
                plugs: {},
              },
            },
            {
              id: 'delec-voltage',
              partnerId: 'voltage',
              status: 'bid',
              invitedOn: '2026-09-19',
              bid: {
                amount: 61400,
                basedOnRev: 0,
                submittedOn: '2026-08-22',
                includes: { 'delec-1': 'yes', 'delec-2': 'yes', 'delec-3': 'yes', 'delec-4': 'yes' },
                plugs: {},
              },
            },
          ],
          awardedInviteId: 'delec-brightline',
          selfPerform: null,
          sow: {
            status: 'sent',
            price: 56900,
            sov: [
              { id: 'delec-1', label: 'Panels and feeders', amount: 14200, pctReported: 0, pctBilled: 0 },
              { id: 'delec-2', label: 'Lighting', amount: 14200, pctReported: 0, pctBilled: 0 },
              { id: 'delec-3', label: 'Devices', amount: 14200, pctReported: 0, pctBilled: 0 },
              { id: 'delec-4', label: 'Low voltage rough', amount: 14300, pctReported: 0, pctBilled: 0 },
            ],
            draws: [],
            sentOn: '2026-09-30',
          },
        },
        {
          id: 'dhvac',
          trade: 'HVAC',
          budget: 49000,
          carried: 'dhvac-kendall',
          scope: [
            { id: 'dhvac-1', label: 'Split systems' },
            { id: 'dhvac-2', label: 'Ductwork' },
            { id: 'dhvac-3', label: 'Controls' },
          ],
          invites: [
            {
              id: 'dhvac-kendall',
              partnerId: 'kendall',
              status: 'bid',
              invitedOn: '2026-09-19',
              bid: {
                amount: 47600,
                basedOnRev: 0,
                submittedOn: '2026-08-22',
                includes: { 'dhvac-1': 'yes', 'dhvac-2': 'yes', 'dhvac-3': 'yes' },
                plugs: {},
              },
            },
          ],
          awardedInviteId: 'dhvac-kendall',
          selfPerform: null,
          sow: {
            status: 'draft',
            price: 47600,
            sov: [
              { id: 'dhvac-1', label: 'Split systems', amount: 15800, pctReported: 0, pctBilled: 0 },
              { id: 'dhvac-2', label: 'Ductwork', amount: 15800, pctReported: 0, pctBilled: 0 },
              { id: 'dhvac-3', label: 'Controls', amount: 16000, pctReported: 0, pctBilled: 0 },
            ],
            draws: [],
          },
        },
        {
          id: 'dplumb',
          trade: 'Plumbing',
          budget: 38500,
          carried: 'self',
          scope: [
            { id: 'dplumb-1', label: 'Underground' },
            { id: 'dplumb-2', label: 'Rough in' },
            { id: 'dplumb-3', label: 'Top out' },
            { id: 'dplumb-4', label: 'Trim' },
          ],
          invites: [],
          awardedInviteId: null,
          selfPerform: { ref: 'J 1042', value: 38500, note: 'Our own crew. The job runs on the Pipeline.' },
          sow: null,
        },
        {
          id: 'mill',
          trade: 'Millwork',
          budget: 41000,
          carried: 'mill-cedar',
          scope: [
            { id: 'mill-1', label: 'Reception desk' },
            { id: 'mill-2', label: 'Operatory cabinets' },
            { id: 'mill-3', label: 'Break room' },
          ],
          invites: [
            {
              id: 'mill-cedar',
              partnerId: 'cedar',
              status: 'bid',
              invitedOn: '2026-09-19',
              bid: {
                amount: 39800,
                basedOnRev: 0,
                submittedOn: '2026-08-25',
                includes: { 'mill-1': 'yes', 'mill-2': 'yes', 'mill-3': 'yes' },
                plugs: {},
              },
            },
            {
              id: 'mill-sawtooth',
              partnerId: 'sawtooth',
              status: 'bid',
              invitedOn: '2026-09-19',
              bid: {
                amount: 43100,
                basedOnRev: 0,
                submittedOn: '2026-08-26',
                includes: { 'mill-1': 'yes', 'mill-2': 'yes', 'mill-3': 'yes' },
                plugs: {},
              },
            },
          ],
          awardedInviteId: null,
          selfPerform: null,
          sow: null,
        },
      ],
      generalConditions: 52000,
      contingencyPct: 3,
      feePct: 10,
      team: [
        { role: 'superintendent', name: 'Marcy Pruett', phone: '(210) 555-0152' },
        {
          role: 'projectManager',
          name: 'Dana Whitaker',
          phone: '(210) 555-0131',
          email: 'dana@clickconstruction.example',
        },
      ],
    },
    {
      id: 'fairoaksd',
      name: 'Fair Oaks Shops, Building D',
      address: '7920 Fair Oaks Pkwy, Fair Oaks Ranch',
      town: 'Boerne',
      ourBidSentOn: '2026-05-14',
      startedOn: '2026-07-01',
      customerId: 'cibolo',
      owner: 'Cibolo Creek Partners',
      stage: 'building',
      bidDue: null,
      planSets: [{ rev: 0, touches: [] }],
      packages: [
        {
          id: 'fsite',
          trade: 'Sitework',
          budget: 172000,
          carried: 'fsite-tricounty',
          scope: [
            { id: 'fsite-1', label: 'Clearing and grading' },
            { id: 'fsite-2', label: 'Utilities to 5 ft of the building' },
            { id: 'fsite-3', label: 'Paving' },
            { id: 'fsite-4', label: 'Striping and signs' },
          ],
          invites: [
            {
              id: 'fsite-tricounty',
              partnerId: 'tricounty',
              status: 'bid',
              invitedOn: '2026-04-30',
              bid: {
                amount: 168000,
                basedOnRev: 0,
                submittedOn: '2026-05-07',
                includes: { 'fsite-1': 'yes', 'fsite-2': 'yes', 'fsite-3': 'yes', 'fsite-4': 'yes' },
                plugs: {},
              },
            },
          ],
          awardedInviteId: 'fsite-tricounty',
          selfPerform: null,
          sow: {
            status: 'signed',
            price: 168000,
            sov: [
              { id: 'fsite-1', label: 'Clearing and grading', amount: 42000, pctReported: 100, pctBilled: 100 },
              {
                id: 'fsite-2',
                label: 'Utilities to 5 ft of the building',
                amount: 56000,
                pctReported: 100,
                pctBilled: 100,
              },
              { id: 'fsite-3', label: 'Paving', amount: 54000, pctReported: 100, pctBilled: 100 },
              { id: 'fsite-4', label: 'Striping and signs', amount: 16000, pctReported: 100, pctBilled: 100 },
            ],
            draws: [
              { number: 1, retainage: 9800, net: 88200, status: 'paid', waiver: 'unconditional' },
              { number: 2, retainage: 7000, net: 63000, status: 'paid', waiver: 'unconditional' },
            ],
          },
        },
        {
          id: 'fconc',
          trade: 'Concrete',
          budget: 220000,
          carried: 'fconc-guadalupe',
          scope: [
            { id: 'fconc-1', label: 'Foundations' },
            { id: 'fconc-2', label: 'Slab on grade' },
            { id: 'fconc-3', label: 'Sidewalks and curbs' },
          ],
          invites: [
            {
              id: 'fconc-guadalupe',
              partnerId: 'guadalupe',
              status: 'bid',
              invitedOn: '2026-04-30',
              bid: {
                amount: 214000,
                basedOnRev: 0,
                submittedOn: '2026-05-09',
                includes: { 'fconc-1': 'yes', 'fconc-2': 'yes', 'fconc-3': 'yes' },
                plugs: {},
              },
            },
          ],
          awardedInviteId: 'fconc-guadalupe',
          selfPerform: null,
          sow: {
            status: 'signed',
            price: 214000,
            sov: [
              { id: 'fconc-1', label: 'Foundations', amount: 78000, pctReported: 100, pctBilled: 100 },
              { id: 'fconc-2', label: 'Slab on grade', amount: 96000, pctReported: 100, pctBilled: 100 },
              { id: 'fconc-3', label: 'Sidewalks and curbs', amount: 40000, pctReported: 100, pctBilled: 100 },
            ],
            draws: [
              { number: 1, retainage: 7800, net: 70200, status: 'paid', waiver: 'unconditional' },
              { number: 2, retainage: 13600, net: 122400, status: 'paid', waiver: 'unconditional' },
            ],
          },
        },
        {
          id: 'fsteel',
          trade: 'Structural steel',
          budget: 190000,
          carried: 'fsteel-ironhorse',
          scope: [
            { id: 'fsteel-1', label: 'Structural steel' },
            { id: 'fsteel-2', label: 'Joists and deck' },
            { id: 'fsteel-3', label: 'Erection' },
          ],
          invites: [
            {
              id: 'fsteel-ironhorse',
              partnerId: 'ironhorse',
              status: 'bid',
              invitedOn: '2026-04-30',
              bid: {
                amount: 186000,
                basedOnRev: 0,
                submittedOn: '2026-05-11',
                includes: { 'fsteel-1': 'yes', 'fsteel-2': 'yes', 'fsteel-3': 'yes' },
                plugs: {},
              },
            },
          ],
          awardedInviteId: 'fsteel-ironhorse',
          selfPerform: null,
          sow: {
            status: 'signed',
            price: 186000,
            sov: [
              { id: 'fsteel-1', label: 'Structural steel', amount: 92000, pctReported: 100, pctBilled: 100 },
              { id: 'fsteel-2', label: 'Joists and deck', amount: 64000, pctReported: 100, pctBilled: 0 },
              { id: 'fsteel-3', label: 'Erection', amount: 30000, pctReported: 80, pctBilled: 0 },
            ],
            draws: [
              { number: 1, retainage: 9200, net: 82800, status: 'paid', waiver: 'unconditional' },
              { number: 2, retainage: 8800, net: 79200, status: 'requested', waiver: 'conditional' },
            ],
          },
        },
        {
          id: 'felec',
          trade: 'Electrical',
          budget: 252000,
          carried: 'felec-pecanvalley',
          scope: [
            { id: 'felec-1', label: 'Service and gear' },
            { id: 'felec-2', label: 'Panels and feeders' },
            { id: 'felec-3', label: 'Lighting' },
            { id: 'felec-4', label: 'Fire alarm' },
            { id: 'felec-5', label: 'Site lighting' },
          ],
          invites: [
            {
              id: 'felec-pecanvalley',
              partnerId: 'pecanvalley',
              status: 'bid',
              invitedOn: '2026-04-30',
              bid: {
                amount: 248000,
                basedOnRev: 0,
                submittedOn: '2026-05-12',
                includes: { 'felec-1': 'yes', 'felec-2': 'yes', 'felec-3': 'yes', 'felec-4': 'yes', 'felec-5': 'yes' },
                plugs: {},
              },
            },
          ],
          awardedInviteId: 'felec-pecanvalley',
          selfPerform: null,
          sow: {
            status: 'signed',
            price: 248000,
            sov: [
              { id: 'felec-1', label: 'Service and gear', amount: 62000, pctReported: 100, pctBilled: 100 },
              { id: 'felec-2', label: 'Panels and feeders', amount: 54000, pctReported: 80, pctBilled: 50 },
              { id: 'felec-3', label: 'Lighting', amount: 72000, pctReported: 40, pctBilled: 0 },
              { id: 'felec-4', label: 'Fire alarm', amount: 36000, pctReported: 0, pctBilled: 0 },
              { id: 'felec-5', label: 'Site lighting', amount: 24000, pctReported: 0, pctBilled: 0 },
            ],
            draws: [
              { number: 1, retainage: 8900, net: 80100, status: 'paid', waiver: 'conditional' },
              { number: 2, retainage: 4500, net: 40500, status: 'requested', waiver: 'conditional' },
            ],
          },
        },
        {
          id: 'froof',
          trade: 'Roofing',
          budget: 136000,
          carried: 'froof-summit',
          scope: [
            { id: 'froof-1', label: 'TPO membrane' },
            { id: 'froof-2', label: 'Insulation' },
            { id: 'froof-3', label: 'Sheet metal and flashing' },
            { id: 'froof-4', label: 'Roof curbs' },
          ],
          invites: [
            {
              id: 'froof-summit',
              partnerId: 'summit',
              status: 'bid',
              invitedOn: '2026-04-30',
              bid: {
                amount: 132000,
                basedOnRev: 0,
                submittedOn: '2026-05-11',
                includes: { 'froof-1': 'yes', 'froof-2': 'yes', 'froof-3': 'yes', 'froof-4': 'yes' },
                plugs: {},
              },
            },
            {
              id: 'froof-bluebonnet',
              partnerId: 'bluebonnet',
              status: 'bid',
              invitedOn: '2026-04-30',
              bid: {
                amount: 139800,
                basedOnRev: 0,
                submittedOn: '2026-05-12',
                includes: { 'froof-1': 'yes', 'froof-2': 'yes', 'froof-3': 'yes', 'froof-4': 'yes' },
                plugs: {},
              },
            },
          ],
          awardedInviteId: 'froof-summit',
          selfPerform: null,
          sow: {
            status: 'signed',
            price: 132000,
            sov: [
              { id: 'froof-1', label: 'TPO membrane', amount: 64000, pctReported: 100, pctBilled: 0 },
              { id: 'froof-2', label: 'Insulation', amount: 28000, pctReported: 100, pctBilled: 0 },
              { id: 'froof-3', label: 'Sheet metal and flashing', amount: 26000, pctReported: 0, pctBilled: 0 },
              { id: 'froof-4', label: 'Roof curbs', amount: 14000, pctReported: 0, pctBilled: 0 },
            ],
            draws: [],
            sentBack: [
              {
                draw: { number: 1, retainage: 9200, net: 82800, status: 'requested', waiver: 'conditional' },
                lines: [{ sovId: 'froof-1', weSee: 50 }],
              },
            ],
          },
        },
        {
          id: 'fplumb',
          trade: 'Plumbing',
          budget: 112000,
          carried: 'self',
          scope: [
            { id: 'fplumb-1', label: 'Underground' },
            { id: 'fplumb-2', label: 'Rough in' },
            { id: 'fplumb-3', label: 'Top out' },
            { id: 'fplumb-4', label: 'Trim' },
          ],
          invites: [],
          awardedInviteId: null,
          selfPerform: {
            ref: 'J 1088',
            value: 112000,
            note: 'Our own crew. The job runs on the Pipeline.',
            pctDone: 65,
            pctByLine: { 'fplumb-1': 100, 'fplumb-2': 100, 'fplumb-3': 40, 'fplumb-4': 0 },
          },
          sow: null,
        },
        {
          id: 'fhvac',
          trade: 'HVAC',
          budget: 160000,
          carried: 'fhvac-coolbreeze',
          scope: [
            { id: 'fhvac-1', label: 'Rooftop units' },
            { id: 'fhvac-2', label: 'Ductwork' },
            { id: 'fhvac-3', label: 'Controls' },
            { id: 'fhvac-4', label: 'Test and balance' },
          ],
          invites: [
            {
              id: 'fhvac-coolbreeze',
              partnerId: 'coolbreeze',
              status: 'bid',
              invitedOn: '2026-04-30',
              bid: {
                amount: 158000,
                basedOnRev: 0,
                submittedOn: '2026-05-12',
                includes: { 'fhvac-1': 'yes', 'fhvac-2': 'yes', 'fhvac-3': 'yes', 'fhvac-4': 'yes' },
                plugs: {},
              },
            },
          ],
          awardedInviteId: 'fhvac-coolbreeze',
          selfPerform: null,
          sow: {
            status: 'signed',
            price: 158000,
            sov: [
              { id: 'fhvac-1', label: 'Rooftop units', amount: 72000, pctReported: 0, pctBilled: 0 },
              { id: 'fhvac-2', label: 'Ductwork', amount: 54000, pctReported: 80, pctBilled: 60 },
              { id: 'fhvac-3', label: 'Controls', amount: 18000, pctReported: 0, pctBilled: 0 },
              { id: 'fhvac-4', label: 'Test and balance', amount: 14000, pctReported: 0, pctBilled: 0 },
            ],
            draws: [{ number: 1, retainage: 3240, net: 29160, status: 'paid', waiver: 'unconditional' }],
          },
        },
      ],
      generalConditions: 96000,
      contingencyPct: 3,
      feePct: 10,
      schedule: {
        activities: [
          { lineId: 'fsite-1', packageId: 'fsite', start: '2026-07-06', finish: '2026-07-17', after: [] },
          { lineId: 'fsite-2', packageId: 'fsite', start: '2026-07-13', finish: '2026-07-31', after: [] },
          { lineId: 'fsite-3', packageId: 'fsite', start: '2026-08-10', finish: '2026-08-21', after: ['fsite-2'] },
          { lineId: 'fsite-4', packageId: 'fsite', start: '2026-08-24', finish: '2026-08-28', after: ['fsite-3'] },
          { lineId: 'fconc-1', packageId: 'fconc', start: '2026-07-20', finish: '2026-08-07', after: ['fsite-1'] },
          { lineId: 'fplumb-1', packageId: 'fplumb', start: '2026-07-27', finish: '2026-08-07', after: ['fsite-1'] },
          {
            lineId: 'fconc-2',
            packageId: 'fconc',
            start: '2026-08-10',
            finish: '2026-08-28',
            after: ['fconc-1', 'fplumb-1'],
          },
          { lineId: 'fconc-3', packageId: 'fconc', start: '2026-08-31', finish: '2026-09-11', after: ['fsite-3'] },
          { lineId: 'fsteel-1', packageId: 'fsteel', start: '2026-08-17', finish: '2026-09-04', after: ['fconc-1'] },
          { lineId: 'fsteel-2', packageId: 'fsteel', start: '2026-09-07', finish: '2026-09-18', after: ['fsteel-1'] },
          { lineId: 'fsteel-3', packageId: 'fsteel', start: '2026-09-07', finish: '2026-10-02', after: ['fsteel-1'] },
          { lineId: 'froof-2', packageId: 'froof', start: '2026-09-21', finish: '2026-09-30', after: ['fsteel-2'] },
          { lineId: 'froof-1', packageId: 'froof', start: '2026-09-21', finish: '2026-10-09', after: ['fsteel-2'] },
          { lineId: 'froof-3', packageId: 'froof', start: '2026-10-12', finish: '2026-10-21', after: ['froof-1'] },
          { lineId: 'froof-4', packageId: 'froof', start: '2026-10-05', finish: '2026-10-09', after: ['fsteel-2'] },
          { lineId: 'felec-1', packageId: 'felec', start: '2026-08-24', finish: '2026-09-11', after: ['fconc-1'] },
          { lineId: 'felec-2', packageId: 'felec', start: '2026-09-14', finish: '2026-10-02', after: ['felec-1'] },
          { lineId: 'felec-3', packageId: 'felec', start: '2026-09-14', finish: '2026-10-23', after: ['felec-1'] },
          { lineId: 'felec-5', packageId: 'felec', start: '2026-10-19', finish: '2026-10-30', after: ['fconc-3'] },
          {
            lineId: 'felec-4',
            packageId: 'felec',
            start: '2026-11-02',
            finish: '2026-11-20',
            after: ['felec-3', 'fairoaksd-insp-roughin'],
          },
          { lineId: 'fplumb-2', packageId: 'fplumb', start: '2026-09-14', finish: '2026-09-25', after: ['fconc-2'] },
          { lineId: 'fplumb-3', packageId: 'fplumb', start: '2026-09-28', finish: '2026-10-09', after: ['fplumb-2'] },
          { lineId: 'fhvac-2', packageId: 'fhvac', start: '2026-09-14', finish: '2026-10-09', after: ['fsteel-1'] },
          { lineId: 'fhvac-1', packageId: 'fhvac', start: '2026-10-12', finish: '2026-10-23', after: ['froof-1'] },
          {
            lineId: 'fhvac-3',
            packageId: 'fhvac',
            start: '2026-11-02',
            finish: '2026-11-13',
            after: ['fhvac-1', 'fairoaksd-insp-roughin'],
          },
          {
            lineId: 'fplumb-4',
            packageId: 'fplumb',
            start: '2026-11-30',
            finish: '2026-12-04',
            after: ['fplumb-3', 'fairoaksd-insp-roughin'],
          },
          { lineId: 'fhvac-4', packageId: 'fhvac', start: '2026-11-30', finish: '2026-12-04', after: ['fhvac-3'] },
          {
            lineId: 'fairoaksd-insp-roughin',
            packageId: '',
            start: '2026-10-12',
            finish: '2026-10-13',
            after: ['felec-2', 'fplumb-3', 'fhvac-2'],
            inspection: { label: 'Rough-in inspection' },
          },
          {
            lineId: 'fairoaksd-insp-service',
            packageId: '',
            start: '2026-10-02',
            finish: '2026-10-02',
            after: ['felec-1'],
            inspection: {
              label: 'Electrical service inspection',
              failed: [
                {
                  on: '2026-09-28',
                  note: 'The main bonding jumper is missing at the service panel.',
                  packageIds: ['felec'],
                  reinspectOn: '2026-10-02',
                },
              ],
            },
          },
          {
            lineId: 'fairoaksd-insp-final',
            packageId: '',
            start: '2026-12-07',
            finish: '2026-12-08',
            after: [
              'fsite-4',
              'fsteel-3',
              'froof-2',
              'froof-3',
              'froof-4',
              'felec-5',
              'felec-4',
              'fplumb-4',
              'fhvac-4',
              'fairoaksd-insp-service',
            ],
            inspection: { label: 'Final inspection' },
          },
        ],
        milestones: [
          { id: 'fo-slab', label: 'Slab poured', planned: '2026-08-28', packageId: 'fconc', metOn: '2026-08-27' },
          { id: 'fo-dryin', label: 'Dry-in', planned: '2026-09-25', packageId: 'froof', metOn: null },
          { id: 'fo-roughin', label: 'Rough-in inspection', planned: '2026-10-13', packageId: null, metOn: null },
          { id: 'fo-substantial', label: 'Substantial completion', planned: '2026-12-11', packageId: null, metOn: null },
        ],
        baseline: {
          lockedOn: '2026-07-01',
          activities: {
            'fsite-1': { start: '2026-07-06', finish: '2026-07-17' },
            'fsite-2': { start: '2026-07-13', finish: '2026-07-31' },
            'fsite-3': { start: '2026-08-10', finish: '2026-08-21' },
            'fsite-4': { start: '2026-08-24', finish: '2026-08-28' },
            'fconc-1': { start: '2026-07-20', finish: '2026-08-07' },
            'fplumb-1': { start: '2026-07-27', finish: '2026-08-07' },
            'fconc-2': { start: '2026-08-10', finish: '2026-08-28' },
            'fconc-3': { start: '2026-08-31', finish: '2026-09-11' },
            'fsteel-1': { start: '2026-08-17', finish: '2026-09-04' },
            'fsteel-2': { start: '2026-09-07', finish: '2026-09-18' },
            'fsteel-3': { start: '2026-09-07', finish: '2026-10-02' },
            'froof-2': { start: '2026-09-21', finish: '2026-09-30' },
            'froof-1': { start: '2026-09-14', finish: '2026-10-02' },
            'froof-3': { start: '2026-10-05', finish: '2026-10-14' },
            'froof-4': { start: '2026-10-05', finish: '2026-10-09' },
            'felec-1': { start: '2026-08-24', finish: '2026-09-11' },
            'felec-2': { start: '2026-09-14', finish: '2026-10-02' },
            'felec-3': { start: '2026-09-14', finish: '2026-10-23' },
            'felec-5': { start: '2026-10-19', finish: '2026-10-30' },
            'felec-4': { start: '2026-11-02', finish: '2026-11-20' },
            'fplumb-2': { start: '2026-09-14', finish: '2026-09-25' },
            'fplumb-3': { start: '2026-09-28', finish: '2026-10-09' },
            'fhvac-2': { start: '2026-09-14', finish: '2026-10-09' },
            'fhvac-1': { start: '2026-10-12', finish: '2026-10-23' },
            'fhvac-3': { start: '2026-11-02', finish: '2026-11-13' },
            'fplumb-4': { start: '2026-11-30', finish: '2026-12-04' },
            'fhvac-4': { start: '2026-11-30', finish: '2026-12-04' },
            'fairoaksd-insp-roughin': { start: '2026-10-12', finish: '2026-10-13' },
            'fairoaksd-insp-service': { start: '2026-09-28', finish: '2026-09-28' },
            'fairoaksd-insp-final': { start: '2026-12-07', finish: '2026-12-08' },
          },
        },
        lookAhead: [
          {
            weekOf: '2026-09-14',
            lineId: 'fsteel-2',
            packageId: 'fsteel',
            done: true,
            markedOn: '2026-09-18',
            verifiedOn: '2026-09-21',
          },
          {
            weekOf: '2026-09-14',
            lineId: 'fsteel-3',
            packageId: 'fsteel',
            done: true,
            markedOn: '2026-09-18',
            verifiedOn: '2026-09-21',
          },
          {
            weekOf: '2026-09-14',
            lineId: 'felec-2',
            packageId: 'felec',
            done: false,
            reason: 'materials',
            markedOn: '2026-09-18',
            verifiedOn: '2026-09-21',
          },
          {
            weekOf: '2026-09-14',
            lineId: 'fplumb-2',
            packageId: 'fplumb',
            done: true,
            markedOn: '2026-09-18',
            verifiedOn: '2026-09-21',
          },
          {
            weekOf: '2026-09-14',
            lineId: 'fhvac-2',
            packageId: 'fhvac',
            done: true,
            markedOn: '2026-09-18',
            verifiedOn: '2026-09-21',
          },
          {
            weekOf: '2026-09-21',
            lineId: 'froof-1',
            packageId: 'froof',
            done: false,
            reason: 'weather',
            markedOn: '2026-09-25',
            verifiedOn: '2026-09-28',
          },
          {
            weekOf: '2026-09-21',
            lineId: 'froof-2',
            packageId: 'froof',
            done: true,
            markedOn: '2026-09-25',
            verifiedOn: '2026-09-28',
          },
          {
            weekOf: '2026-09-21',
            lineId: 'fsteel-3',
            packageId: 'fsteel',
            done: false,
            reason: 'crew',
            markedOn: '2026-09-25',
            verifiedOn: '2026-09-28',
          },
          {
            weekOf: '2026-09-21',
            lineId: 'fplumb-2',
            packageId: 'fplumb',
            done: true,
            markedOn: '2026-09-25',
            verifiedOn: '2026-09-28',
          },
          {
            weekOf: '2026-09-21',
            lineId: 'fhvac-2',
            packageId: 'fhvac',
            done: true,
            markedOn: '2026-09-25',
            verifiedOn: '2026-09-28',
          },
          {
            weekOf: '2026-09-28',
            lineId: 'froof-1',
            packageId: 'froof',
            done: true,
            markedOn: '2026-10-02',
            verifiedOn: null,
          },
          {
            weekOf: '2026-09-28',
            lineId: 'fsteel-3',
            packageId: 'fsteel',
            done: false,
            reason: 'crew',
            markedOn: '2026-10-02',
            verifiedOn: null,
          },
          {
            weekOf: '2026-09-28',
            lineId: 'felec-2',
            packageId: 'felec',
            done: false,
            reason: 'materials',
            markedOn: '2026-10-02',
            verifiedOn: null,
          },
          {
            weekOf: '2026-09-28',
            lineId: 'fplumb-3',
            packageId: 'fplumb',
            done: true,
            markedOn: '2026-10-02',
            verifiedOn: '2026-10-02',
          },
          {
            weekOf: '2026-09-28',
            lineId: 'fhvac-2',
            packageId: 'fhvac',
            done: true,
            markedOn: '2026-10-02',
            verifiedOn: null,
          },
        ],
      },
      team: [
        { role: 'superintendent', name: 'Luis Ortega', phone: '(210) 555-0147' },
        {
          role: 'projectManager',
          name: 'Dana Whitaker',
          phone: '(210) 555-0131',
          email: 'dana@clickconstruction.example',
        },
      ],
      dailyLogs: [
        {
          date: '2026-09-21',
          crews: [
            { packageId: 'fsteel', workers: 5 },
            { packageId: 'froof', workers: 4 },
            { packageId: 'felec', workers: 3 },
            { packageId: 'fplumb', workers: 3 },
            { packageId: 'fhvac', workers: 3 },
          ],
          delays: [],
          weatherStop: false,
        },
        {
          date: '2026-09-22',
          crews: [
            { packageId: 'fsteel', workers: 5 },
            { packageId: 'froof', workers: 5 },
            { packageId: 'felec', workers: 3 },
            { packageId: 'fplumb', workers: 3 },
            { packageId: 'fhvac', workers: 3 },
          ],
          delays: [],
          weatherStop: false,
        },
        {
          date: '2026-09-23',
          crews: [
            { packageId: 'fsteel', workers: 3 },
            { packageId: 'froof', workers: 5 },
            { packageId: 'felec', workers: 3 },
            { packageId: 'fplumb', workers: 3 },
            { packageId: 'fhvac', workers: 3 },
          ],
          delays: [{ packageId: 'fsteel', reason: 'crew', note: 'Iron Horse came with three ironworkers, not five.' }],
          weatherStop: false,
        },
        {
          date: '2026-09-24',
          crews: [{ packageId: 'felec', workers: 3 }, { packageId: 'fplumb', workers: 3 }, { packageId: 'fhvac', workers: 2 }],
          delays: [{ packageId: 'froof', reason: 'weather', note: 'Rain all day. The membrane cannot go down wet.' }],
          weatherStop: false,
        },
        {
          date: '2026-09-25',
          crews: [{ packageId: 'felec', workers: 2 }],
          delays: [{ packageId: null, reason: 'weather', note: 'Work stopped at 12:30 for lightning.' }],
          weatherStop: true,
        },
        {
          date: '2026-09-28',
          crews: [
            { packageId: 'fsteel', workers: 4 },
            { packageId: 'froof', workers: 5 },
            { packageId: 'felec', workers: 3 },
            { packageId: 'fplumb', workers: 3 },
            { packageId: 'fhvac', workers: 3 },
          ],
          delays: [],
          weatherStop: false,
        },
        {
          date: '2026-09-29',
          crews: [
            { packageId: 'fsteel', workers: 4 },
            { packageId: 'froof', workers: 5 },
            { packageId: 'felec', workers: 2 },
            { packageId: 'fplumb', workers: 3 },
            { packageId: 'fhvac', workers: 3 },
          ],
          delays: [{ packageId: 'felec', reason: 'materials', note: 'Panel boards are two weeks out.' }],
          weatherStop: false,
        },
        {
          date: '2026-10-01',
          crews: [
            { packageId: 'fsteel', workers: 3 },
            { packageId: 'froof', workers: 4 },
            { packageId: 'felec', workers: 2 },
            { packageId: 'fplumb', workers: 3 },
            { packageId: 'fhvac', workers: 3 },
          ],
          delays: [],
          weatherStop: false,
        },
      ],
      waits: [
        {
          id: 'fairoaksd-wait-1',
          kind: 'delivery',
          title: 'Rooftop units',
          packageId: 'fhvac',
          who: 'Cool Breeze Mechanical\'s supplier',
          lineIds: ['fhvac-1'],
          askedOn: '2026-09-01',
          expectedOn: '2026-10-20',
          shippedOn: null,
          doneOn: null,
          note: 'Carrier: two of the four are built; the rest ship Oct 15.',
        },
        {
          id: 'fairoaksd-wait-2',
          kind: 'decision',
          title: 'the restroom tile',
          packageId: 'fplumb',
          who: 'Cibolo Creek Partners',
          lineIds: ['fplumb-4'],
          askedOn: '2026-09-28',
          expectedOn: '2026-10-30',
          doneOn: null,
        },
        {
          id: 'fairoaksd-wait-3',
          kind: 'utility',
          title: 'The transformer',
          packageId: null,
          who: 'CPS Energy',
          lineIds: ['felec-5'],
          askedOn: '2026-09-15',
          expectedOn: '2026-10-15',
          doneOn: null,
        },
      ],
    },
    {
      id: 'stoneoak',
      name: 'Stone Oak Pharmacy',
      address: '20811 Stone Oak Pkwy, Suite 104, San Antonio',
      town: 'San Antonio',
      ourBidSentOn: '2026-05-14',
      startedOn: '2026-06-12',
      customerId: 'hollis',
      owner: 'Hollis Family Pharmacy',
      stage: 'building',
      bidDue: null,
      planSets: [{ rev: 0, touches: [] }],
      packages: [
        {
          id: 'sdry',
          trade: 'Framing and drywall',
          budget: 43000,
          carried: 'sdry-liveoak',
          scope: [
            { id: 'sdry-1', label: 'Framing' },
            { id: 'sdry-2', label: 'Hang and tape' },
            { id: 'sdry-3', label: 'Ceilings' },
          ],
          invites: [
            {
              id: 'sdry-liveoak',
              partnerId: 'liveoak',
              status: 'bid',
              invitedOn: '2026-09-19',
              bid: {
                amount: 42000,
                basedOnRev: 0,
                submittedOn: '2026-05-06',
                includes: { 'sdry-1': 'yes', 'sdry-2': 'yes', 'sdry-3': 'yes' },
                plugs: {},
              },
            },
          ],
          awardedInviteId: 'sdry-liveoak',
          selfPerform: null,
          sow: {
            status: 'signed',
            price: 42000,
            sov: [
              { id: 'sdry-1', label: 'Framing', amount: 21000, pctReported: 100, pctBilled: 100 },
              { id: 'sdry-2', label: 'Hang and tape', amount: 12000, pctReported: 100, pctBilled: 100 },
              { id: 'sdry-3', label: 'Ceilings', amount: 9000, pctReported: 100, pctBilled: 100 },
            ],
            draws: [
              { number: 1, retainage: 2100, net: 18900, status: 'paid', waiver: 'unconditional' },
              { number: 2, retainage: 2100, net: 18900, status: 'paid', waiver: 'unconditional' },
              { number: 3, retainage: -4200, net: 4200, status: 'requested', waiver: 'conditional' },
            ],
          },
        },
        {
          id: 'selec',
          trade: 'Electrical',
          budget: 39000,
          carried: 'selec-westside',
          scope: [
            { id: 'selec-1', label: 'Panels and feeders' },
            { id: 'selec-2', label: 'Lighting' },
            { id: 'selec-3', label: 'Devices' },
          ],
          invites: [
            {
              id: 'selec-westside',
              partnerId: 'westside',
              status: 'bid',
              invitedOn: '2026-09-19',
              bid: {
                amount: 38000,
                basedOnRev: 0,
                submittedOn: '2026-05-07',
                includes: { 'selec-1': 'yes', 'selec-2': 'yes', 'selec-3': 'yes' },
                plugs: {},
              },
            },
          ],
          awardedInviteId: 'selec-westside',
          selfPerform: null,
          sow: {
            status: 'signed',
            price: 38000,
            sov: [
              { id: 'selec-1', label: 'Panels and feeders', amount: 14000, pctReported: 100, pctBilled: 100 },
              { id: 'selec-2', label: 'Lighting', amount: 14000, pctReported: 100, pctBilled: 100 },
              { id: 'selec-3', label: 'Devices', amount: 10000, pctReported: 100, pctBilled: 100 },
            ],
            draws: [
              { number: 1, retainage: 1400, net: 12600, status: 'paid', waiver: 'unconditional' },
              { number: 2, retainage: 2400, net: 21600, status: 'paid', waiver: 'unconditional' },
              { number: 3, retainage: -3800, net: 3800, status: 'requested', waiver: 'conditional' },
            ],
          },
        },
        {
          id: 'shvac',
          trade: 'HVAC',
          budget: 32000,
          carried: 'shvac-coolbreeze',
          scope: [
            { id: 'shvac-1', label: 'Split systems' },
            { id: 'shvac-2', label: 'Ductwork' },
            { id: 'shvac-3', label: 'Controls' },
          ],
          invites: [
            {
              id: 'shvac-coolbreeze',
              partnerId: 'coolbreeze',
              status: 'bid',
              invitedOn: '2026-09-19',
              bid: {
                amount: 31000,
                basedOnRev: 0,
                submittedOn: '2026-05-08',
                includes: { 'shvac-1': 'yes', 'shvac-2': 'yes', 'shvac-3': 'yes' },
                plugs: {},
              },
            },
          ],
          awardedInviteId: 'shvac-coolbreeze',
          selfPerform: null,
          sow: {
            status: 'signed',
            price: 31000,
            sov: [
              { id: 'shvac-1', label: 'Split systems', amount: 13000, pctReported: 100, pctBilled: 100 },
              { id: 'shvac-2', label: 'Ductwork', amount: 12000, pctReported: 100, pctBilled: 100 },
              { id: 'shvac-3', label: 'Controls', amount: 6000, pctReported: 100, pctBilled: 100 },
            ],
            draws: [
              { number: 1, retainage: 2500, net: 22500, status: 'paid', waiver: 'unconditional' },
              { number: 2, retainage: 600, net: 5400, status: 'paid', waiver: 'unconditional' },
            ],
          },
        },
        {
          id: 'splumb',
          trade: 'Plumbing',
          budget: 26000,
          carried: 'self',
          scope: [
            { id: 'splumb-1', label: 'Underground' },
            { id: 'splumb-2', label: 'Rough in' },
            { id: 'splumb-3', label: 'Top out' },
            { id: 'splumb-4', label: 'Trim' },
          ],
          invites: [],
          awardedInviteId: null,
          selfPerform: { ref: 'J 1071', value: 26000, note: 'Our own crew. The job runs on the Pipeline.', pctDone: 100 },
          sow: null,
        },
      ],
      generalConditions: 24000,
      contingencyPct: 3,
      feePct: 10,
      team: [
        { role: 'superintendent', name: 'Marcy Pruett', phone: '(210) 555-0152' },
        {
          role: 'projectManager',
          name: 'Dana Whitaker',
          phone: '(210) 555-0131',
          email: 'dana@clickconstruction.example',
        },
      ],
    },
  ],
  partners: [
    {
      id: 'lonestar',
      company: 'Lonestar Earthworks',
      contact: 'Dale Whitfield',
      trades: ['Sitework'],
      msa: 'signed',
      msaSignedOn: '2026-06-12',
      coiExpires: '2027-03-01',
      w9: true,
      invited: 6,
      bids: 5,
      promisesMade: 3,
      promisesKept: 2,
    },
    {
      id: 'tricounty',
      company: 'Tri-County Site',
      contact: 'Marisol Vega',
      trades: ['Sitework'],
      msa: 'signed',
      msaSignedOn: '2026-06-12',
      coiExpires: '2027-01-15',
      w9: true,
      invited: 4,
      bids: 4,
      promisesMade: 0,
      promisesKept: 0,
    },
    {
      id: 'hillside',
      company: 'Hillside Excavation',
      contact: 'Greg Paulk',
      trades: ['Sitework'],
      msa: 'none',
      msaSignedOn: null,
      coiExpires: null,
      w9: false,
      invited: 2,
      bids: 0,
      promisesMade: 2,
      promisesKept: 0,
    },
    {
      id: 'alamo',
      company: 'Alamo Concrete',
      contact: 'Hector Luna',
      trades: ['Concrete'],
      msa: 'signed',
      msaSignedOn: '2026-06-12',
      coiExpires: '2026-12-20',
      w9: true,
      invited: 7,
      bids: 6,
      promisesMade: 0,
      promisesKept: 0,
    },
    {
      id: 'guadalupe',
      company: 'Guadalupe Flatwork',
      contact: 'Ines Barrera',
      trades: ['Concrete'],
      msa: 'signed',
      msaSignedOn: '2026-06-12',
      coiExpires: '2027-02-10',
      w9: true,
      invited: 3,
      bids: 3,
      promisesMade: 0,
      promisesKept: 0,
    },
    {
      id: 'bexar',
      company: 'Bexar Steel Erectors',
      contact: 'Tom Riddle',
      trades: ['Structural steel'],
      msa: 'signed',
      msaSignedOn: '2026-06-12',
      coiExpires: '2027-04-30',
      w9: true,
      invited: 3,
      bids: 1,
      promisesMade: 2,
      promisesKept: 1,
    },
    {
      id: 'comal',
      company: 'Comal Iron',
      contact: 'Ray Odom',
      trades: ['Structural steel'],
      msa: 'none',
      msaSignedOn: null,
      coiExpires: null,
      w9: true,
      invited: 2,
      bids: 0,
      promisesMade: 0,
      promisesKept: 0,
    },
    {
      id: 'ironhorse',
      company: 'Iron Horse Fabrication',
      contact: 'Luz Carrasco',
      trades: ['Structural steel'],
      msa: 'signed',
      msaSignedOn: '2026-06-12',
      coiExpires: '2027-05-05',
      w9: true,
      invited: 1,
      bids: 1,
      promisesMade: 0,
      promisesKept: 0,
    },
    {
      id: 'summit',
      company: 'Summit Roofing',
      contact: 'Carla Nguyen',
      trades: ['Roofing'],
      msa: 'signed',
      msaSignedOn: '2026-06-12',
      coiExpires: '2027-06-01',
      w9: true,
      invited: 5,
      bids: 5,
      promisesMade: 2,
      promisesKept: 2,
    },
    {
      id: 'bluebonnet',
      company: 'Bluebonnet Roofing',
      contact: 'Wes Hartley',
      trades: ['Roofing'],
      msa: 'sent',
      msaSignedOn: null,
      coiExpires: '2026-11-30',
      w9: true,
      invited: 2,
      bids: 1,
      promisesMade: 2,
      promisesKept: 1,
      msaSentOn: '2026-09-30',
    },
    {
      id: 'coolbreeze',
      company: 'Cool Breeze Mechanical',
      contact: 'Andre Wallace',
      trades: ['HVAC'],
      msa: 'signed',
      msaSignedOn: '2026-06-12',
      coiExpires: '2027-01-31',
      w9: true,
      invited: 5,
      bids: 4,
      promisesMade: 3,
      promisesKept: 3,
    },
    {
      id: 'kendall',
      company: 'Kendall Air',
      contact: 'Josie Tran',
      trades: ['HVAC'],
      msa: 'sent',
      msaSignedOn: null,
      coiExpires: '2027-02-28',
      w9: true,
      invited: 4,
      bids: 4,
      promisesMade: 3,
      promisesKept: 3,
      msaSentOn: '2026-09-29',
    },
    {
      id: 'voltage',
      company: 'Voltage Brothers',
      contact: 'Sam Okafor',
      trades: ['Electrical'],
      msa: 'signed',
      msaSignedOn: '2026-06-12',
      coiExpires: '2026-09-15',
      w9: true,
      invited: 8,
      bids: 7,
      promisesMade: 5,
      promisesKept: 4,
    },
    {
      id: 'brightline',
      company: 'Brightline Electric',
      contact: 'Nora Castillo',
      trades: ['Electrical'],
      msa: 'signed',
      msaSignedOn: '2026-06-12',
      coiExpires: '2027-03-20',
      w9: true,
      invited: 6,
      bids: 6,
      promisesMade: 4,
      promisesKept: 4,
    },
    {
      id: 'tejas',
      company: 'Tejas Power',
      contact: 'Bill Sorrell',
      trades: ['Electrical'],
      msa: 'none',
      msaSignedOn: null,
      coiExpires: null,
      w9: false,
      invited: 1,
      bids: 0,
      promisesMade: 1,
      promisesKept: 0,
    },
    {
      id: 'redline',
      company: 'Redline Fire Protection',
      contact: 'Mina Shah',
      trades: ['Fire sprinkler'],
      msa: 'signed',
      msaSignedOn: '2026-06-12',
      coiExpires: '2027-02-01',
      w9: true,
      invited: 3,
      bids: 3,
      promisesMade: 0,
      promisesKept: 0,
    },
    {
      id: 'aquashield',
      company: 'AquaShield Sprinkler',
      contact: 'Pete Doyle',
      trades: ['Fire sprinkler'],
      msa: 'none',
      msaSignedOn: null,
      coiExpires: null,
      w9: false,
      invited: 0,
      bids: 0,
      promisesMade: 0,
      promisesKept: 0,
    },
    {
      id: 'hillcountry',
      company: 'Hill Country Interiors',
      contact: 'Rosa Medina',
      trades: ['Framing and drywall'],
      msa: 'signed',
      msaSignedOn: '2026-06-12',
      coiExpires: '2027-04-12',
      w9: true,
      invited: 4,
      bids: 4,
      promisesMade: 0,
      promisesKept: 0,
    },
    {
      id: 'cedar',
      company: 'Cedar & Pine Millwork',
      contact: 'Owen Blake',
      trades: ['Millwork'],
      msa: 'none',
      msaSignedOn: null,
      coiExpires: '2027-01-08',
      w9: true,
      invited: 2,
      bids: 2,
      promisesMade: 0,
      promisesKept: 0,
    },
    {
      id: 'sawtooth',
      company: 'Sawtooth Cabinet Co',
      contact: 'Jill Arnett',
      trades: ['Millwork'],
      msa: 'signed',
      msaSignedOn: '2026-06-12',
      coiExpires: '2027-03-03',
      w9: true,
      invited: 2,
      bids: 2,
      promisesMade: 0,
      promisesKept: 0,
    },
    {
      id: 'pecanvalley',
      company: 'Pecan Valley Electric',
      contact: 'Marcus Bell',
      trades: ['Electrical'],
      msa: 'signed',
      msaSignedOn: '2026-06-12',
      coiExpires: '2026-09-15',
      w9: true,
      invited: 3,
      bids: 3,
      promisesMade: 0,
      promisesKept: 0,
    },
    {
      id: 'liveoak',
      company: 'Live Oak Drywall',
      contact: 'Darnell Pruitt',
      trades: ['Framing and drywall'],
      msa: 'signed',
      msaSignedOn: '2026-06-12',
      coiExpires: '2027-05-01',
      w9: true,
      invited: 3,
      bids: 3,
      promisesMade: 0,
      promisesKept: 0,
    },
    {
      id: 'westside',
      company: 'Westside Electric',
      contact: 'Ana Flores',
      trades: ['Electrical'],
      msa: 'signed',
      msaSignedOn: '2026-06-12',
      coiExpires: '2027-04-15',
      w9: true,
      invited: 3,
      bids: 3,
      promisesMade: 0,
      promisesKept: 0,
    },
  ],
}

/** A fresh copy each call, like the prototype's `initialGcState`, so a test may change what it gets. */
export function initialGcState(): GcState {
  return structuredClone(DATA)
}
