/**
 * Test data only: the app never reads it. It is the GC mode prototype's made-up data
 * (`initialGcState` in `gcFixture.ts`, branch spike/gc-mode), cut to the fields main's GC kernels
 * read (`../types.ts` and `./types.ts`). Written by to-dos/gc-mode/scripts/schedule-test-state.ts on
 * the spike, never by hand; the spike's test holds the two equal.
 */
import type { GcState } from '../types'

const DATA: GcState = {
  today: '2026-10-02',
  customers: [
    {
      id: 'cibolo',
      name: 'Cibolo Creek Partners',
      contact: 'Elena Marchetti',
      portalOn: true,
      payDays: 38,
      retainagePct: 10,
      address: '200 Main Plaza, Suite 300, Boerne',
      phone: '(830) 555-0142',
      email: 'elena@cibolocreekpartners.example',
      contacts: [
        { on: '2026-09-29', by: 'Robert', note: 'Elena sent Addendum 1. She wants the price to hold for 60 days.' },
        { on: '2026-09-18', by: 'Robert', note: 'Walked the site. Pad B will follow about two weeks behind the shell.' },
      ],
    },
    {
      id: 'raman',
      name: 'Dr. Priya Raman',
      contact: 'Dr. Priya Raman',
      portalOn: false,
      payDays: 21,
      retainagePct: 10,
      address: '9811 Bandera Rd, Suite 140, Helotes',
      phone: '(210) 555-0177',
      email: 'priya@helotesdental.example',
      contacts: [
        {
          on: '2026-09-26',
          by: 'Robert',
          note: 'She asked to move the opening to December 1. Told her millwork is the long lead.',
        },
      ],
    },
    {
      id: 'marshvale',
      name: 'Marsh & Vale Architects',
      contact: 'Jonah Vale',
      portalOn: false,
      payDays: null,
      retainagePct: null,
      address: '410 Broadway, Suite 210, San Antonio',
      phone: '(210) 555-0119',
      email: 'jonah@marshvale.example',
      contacts: [
        {
          on: '2026-09-29',
          by: 'Robert',
          note: 'Jonah issued Addendum 1. He expects one more addendum before bid day.',
        },
        {
          on: '2026-08-14',
          by: 'Wendi',
          note: 'Called about the water heater schedule on a plumbing bid. Jonah answered the same day.',
        },
      ],
    },
    {
      id: 'ocotillo',
      name: 'Studio Ocotillo',
      contact: 'Camila Reyes',
      portalOn: false,
      payDays: null,
      retainagePct: null,
      address: '88 Pearl Pkwy, San Antonio',
      phone: '(210) 555-0163',
      email: 'camila@studioocotillo.example',
      contacts: [],
    },
    {
      id: 'hollis',
      name: 'Hollis Family Pharmacy',
      contact: 'Dana Hollis',
      portalOn: true,
      payDays: 18,
      retainagePct: 10,
      address: '20811 Stone Oak Pkwy, Suite 104, San Antonio',
      phone: '(210) 555-0142',
      email: 'dana@hollispharmacy.example',
      contacts: [
        {
          on: '2026-09-29',
          by: 'Robert',
          note: 'Dana wants to open October 20. She asked what is left before the last bill.',
        },
      ],
    },
    {
      id: 'mesquite',
      name: 'Mesquite Design Studio',
      contact: 'Theo Park',
      portalOn: false,
      payDays: null,
      retainagePct: null,
      address: '1202 S Alamo St, San Antonio',
      phone: '(210) 555-0188',
      email: 'theo@mesquitedesign.example',
      contacts: [],
    },
  ],
  projects: [
    {
      id: 'boerne',
      name: 'Boerne Retail Shell',
      startedOn: null,
      packages: [
        {
          id: 'site',
          trade: 'Sitework',
          budget: 185000,
          carried: 'site-lonestar',
          scope: [
            { id: 'site-1', label: 'Clearing and grading' },
            { id: 'site-2', label: 'Utilities to 5 ft of the building' },
            { id: 'site-3', label: 'Paving' },
            { id: 'site-4', label: 'Striping and signs' },
          ],
          invites: [
            {
              id: 'site-lonestar',
              partnerId: 'lonestar',
              status: 'bid',
              invitedOn: '2026-09-19',
              bid: {
                amount: 178400,
                basedOnRev: 1,
                submittedOn: '2026-09-30',
                includes: { 'site-1': 'yes', 'site-2': 'yes', 'site-3': 'yes', 'site-4': 'no' },
                plugs: { 'site-4': 6500 },
                note: 'Striping by others.',
              },
              seenRev: 1,
            },
            {
              id: 'site-tricounty',
              partnerId: 'tricounty',
              status: 'bid',
              invitedOn: '2026-09-19',
              bid: {
                amount: 191000,
                basedOnRev: 1,
                submittedOn: '2026-10-01',
                includes: { 'site-1': 'yes', 'site-2': 'yes', 'site-3': 'yes', 'site-4': 'yes' },
                plugs: {},
                note: '',
              },
              seenRev: 1,
            },
            {
              id: 'site-hillside',
              partnerId: 'hillside',
              status: 'opened',
              invitedOn: '2026-09-19',
              bid: null,
              contacts: [
                {
                  on: '2026-09-26',
                  by: 'Robert',
                  how: 'call',
                  note: 'Greg is busy on a subdivision. Says he will price it by Wednesday.',
                  promisedBy: '2026-09-30',
                },
              ],
              seenRev: 0,
            },
          ],
          awardedInviteId: null,
          selfPerform: null,
          sow: null,
          bidTab: null,
        },
        {
          id: 'conc',
          trade: 'Concrete',
          budget: 212000,
          carried: 'conc-guadalupe',
          scope: [
            { id: 'conc-1', label: 'Foundations' },
            { id: 'conc-2', label: 'Slab on grade' },
            { id: 'conc-3', label: 'Sidewalks and curbs' },
            { id: 'conc-4', label: 'Rebar supply' },
          ],
          invites: [
            {
              id: 'conc-alamo',
              partnerId: 'alamo',
              status: 'bid',
              invitedOn: '2026-09-19',
              bid: {
                amount: 205500,
                basedOnRev: 1,
                submittedOn: '2026-09-30',
                includes: { 'conc-1': 'yes', 'conc-2': 'yes', 'conc-3': 'yes', 'conc-4': 'unclear' },
                plugs: {},
                note: 'Rebar per the structural drawings.',
              },
              seenRev: 1,
            },
            {
              id: 'conc-guadalupe',
              partnerId: 'guadalupe',
              status: 'bid',
              invitedOn: '2026-09-19',
              bid: {
                amount: 219800,
                basedOnRev: 1,
                submittedOn: '2026-10-01',
                includes: { 'conc-1': 'yes', 'conc-2': 'yes', 'conc-3': 'yes', 'conc-4': 'yes' },
                plugs: {},
                note: '',
              },
              seenRev: 1,
            },
          ],
          awardedInviteId: null,
          selfPerform: null,
          sow: null,
          bidTab: null,
        },
        {
          id: 'steel',
          trade: 'Structural steel',
          budget: 164000,
          carried: null,
          scope: [
            { id: 'steel-1', label: 'Structural steel' },
            { id: 'steel-2', label: 'Joists and deck' },
            { id: 'steel-3', label: 'Erection' },
          ],
          invites: [
            {
              id: 'steel-bexar',
              partnerId: 'bexar',
              status: 'invited',
              invitedOn: '2026-09-19',
              bid: null,
              seenRev: null,
            },
            {
              id: 'steel-comal',
              partnerId: 'comal',
              status: 'declined',
              invitedOn: '2026-09-19',
              bid: null,
              seenRev: 0,
            },
          ],
          awardedInviteId: null,
          selfPerform: null,
          sow: null,
          bidTab: null,
        },
        {
          id: 'roof',
          trade: 'Roofing',
          budget: 118000,
          carried: 'roof-summit',
          scope: [
            { id: 'roof-1', label: 'TPO membrane' },
            { id: 'roof-2', label: 'Insulation' },
            { id: 'roof-3', label: 'Sheet metal and flashing' },
            { id: 'roof-4', label: 'Roof curbs' },
          ],
          invites: [
            {
              id: 'roof-summit',
              partnerId: 'summit',
              status: 'bid',
              invitedOn: '2026-09-19',
              bid: {
                amount: 112300,
                basedOnRev: 1,
                submittedOn: '2026-09-28',
                includes: { 'roof-1': 'yes', 'roof-2': 'yes', 'roof-3': 'yes', 'roof-4': 'no' },
                plugs: {},
                note: 'Curbs by the mechanical contractor.',
              },
              seenRev: 1,
            },
            {
              id: 'roof-bluebonnet',
              partnerId: 'bluebonnet',
              status: 'opened',
              invitedOn: '2026-09-19',
              bid: null,
              contacts: [
                {
                  on: '2026-09-30',
                  by: 'Robert',
                  how: 'call',
                  note: 'Wes has the plans open. He will have a number Monday.',
                  promisedBy: '2026-10-05',
                },
                { on: '2026-09-24', by: 'Robert', how: 'email', note: 'Sent the roof plan and the spec section again.' },
              ],
              seenRev: 1,
            },
          ],
          awardedInviteId: null,
          selfPerform: null,
          sow: null,
          bidTab: null,
        },
        {
          id: 'plumb',
          trade: 'Plumbing',
          budget: 86400,
          carried: 'self',
          scope: [
            { id: 'plumb-1', label: 'Underground' },
            { id: 'plumb-2', label: 'Rough in' },
            { id: 'plumb-3', label: 'Top out' },
            { id: 'plumb-4', label: 'Trim' },
          ],
          invites: [],
          awardedInviteId: null,
          selfPerform: { ref: 'BP 512', value: 86400, note: 'Our own bid, priced in Trades mode.' },
          sow: null,
          bidTab: null,
        },
        {
          id: 'hvac',
          trade: 'HVAC',
          budget: 142000,
          carried: null,
          scope: [
            { id: 'hvac-1', label: 'Rooftop units' },
            { id: 'hvac-2', label: 'Ductwork' },
            { id: 'hvac-3', label: 'Controls' },
            { id: 'hvac-4', label: 'Test and balance' },
          ],
          invites: [
            {
              id: 'hvac-coolbreeze',
              partnerId: 'coolbreeze',
              status: 'bid',
              invitedOn: '2026-09-19',
              bid: {
                amount: 148900,
                basedOnRev: 0,
                submittedOn: '2026-09-25',
                includes: { 'hvac-1': 'yes', 'hvac-2': 'yes', 'hvac-3': 'yes', 'hvac-4': 'yes' },
                plugs: {},
                note: '',
              },
              contacts: [
                {
                  on: '2026-09-22',
                  by: 'Robert',
                  how: 'call',
                  note: 'Andre will quote by Friday the 26th.',
                  promisedBy: '2026-09-26',
                },
              ],
              seenRev: 0,
            },
            {
              id: 'hvac-kendall',
              partnerId: 'kendall',
              status: 'bid',
              invitedOn: '2026-09-19',
              bid: {
                amount: 139200,
                basedOnRev: 1,
                submittedOn: '2026-10-01',
                includes: { 'hvac-1': 'yes', 'hvac-2': 'yes', 'hvac-3': 'yes', 'hvac-4': 'no' },
                plugs: { 'hvac-4': 4800 },
                note: 'Test and balance by an independent firm.',
              },
              seenRev: 1,
            },
          ],
          awardedInviteId: null,
          selfPerform: null,
          sow: null,
          bidTab: null,
        },
        {
          id: 'elec',
          trade: 'Electrical',
          budget: 171000,
          carried: null,
          scope: [
            { id: 'elec-1', label: 'Service and gear' },
            { id: 'elec-2', label: 'Panels and feeders' },
            { id: 'elec-3', label: 'Lighting' },
            { id: 'elec-4', label: 'Fire alarm' },
            { id: 'elec-5', label: 'Site lighting' },
          ],
          invites: [
            {
              id: 'elec-voltage',
              partnerId: 'voltage',
              status: 'bid',
              invitedOn: '2026-09-19',
              bid: {
                amount: 166000,
                basedOnRev: 0,
                submittedOn: '2026-09-26',
                includes: { 'elec-1': 'yes', 'elec-2': 'yes', 'elec-3': 'yes', 'elec-4': 'no', 'elec-5': 'yes' },
                plugs: { 'elec-4': 14000 },
                note: 'Fire alarm excluded.',
              },
              seenRev: 0,
            },
            {
              id: 'elec-brightline',
              partnerId: 'brightline',
              status: 'bid',
              invitedOn: '2026-09-19',
              bid: {
                amount: 182500,
                basedOnRev: 1,
                submittedOn: '2026-10-01',
                includes: { 'elec-1': 'yes', 'elec-2': 'yes', 'elec-3': 'yes', 'elec-4': 'yes', 'elec-5': 'yes' },
                plugs: {},
                note: '',
              },
              seenRev: 1,
            },
            {
              id: 'elec-tejas',
              partnerId: 'tejas',
              status: 'opened',
              invitedOn: '2026-09-19',
              bid: null,
              contacts: [
                {
                  on: '2026-10-01',
                  by: 'Wendi',
                  how: 'text',
                  note: 'Bill texted back: quote by end of day Friday.',
                  promisedBy: '2026-10-02',
                },
              ],
              seenRev: 0,
            },
          ],
          awardedInviteId: null,
          selfPerform: null,
          sow: null,
          bidTab: null,
        },
        {
          id: 'fire',
          trade: 'Fire sprinkler',
          budget: 44000,
          carried: null,
          scope: [
            { id: 'fire-1', label: 'Design and permit' },
            { id: 'fire-2', label: 'Mains and branch lines' },
            { id: 'fire-3', label: 'Heads and trim' },
          ],
          invites: [],
          awardedInviteId: null,
          selfPerform: null,
          sow: null,
          bidTab: null,
        },
      ],
      stage: 'pursuing',
      owner: 'Cibolo Creek Partners',
      town: 'Boerne',
      customerId: 'cibolo',
      address: '1420 River Rd, Boerne',
      architect: 'Marsh & Vale Architects',
      ownerBilling: null,
      ourBidSentOn: null,
      bidDue: '2026-10-08',
      planSets: [
        { rev: 0, touches: [], label: 'Bid set', issuedOn: '2026-09-18' },
        { rev: 1, touches: ['elec', 'hvac', 'plumb'], label: 'Addendum 1', issuedOn: '2026-09-29' },
      ],
      generalConditions: 138000,
      contingencyPct: 3,
      feePct: 8,
      team: [
        {
          role: 'projectManager',
          name: 'Dana Whitaker',
          phone: '(210) 555-0131',
          email: 'dana@clickconstruction.example',
        },
      ],
      ownerContractSignedOn: null,
      permitOn: null,
      startDate: null,
      architectId: 'marshvale',
      questions: [
        {
          id: 'q-elec-1',
          packageId: 'elec',
          partnerId: 'brightline',
          text: 'E-301 shows a 400 amp service. The panel schedules add up to 520 amps. Which is right?',
          askedOn: '2026-09-30',
          answeredOn: null,
          answer: null,
          sentToArchitectOn: '2026-09-30',
        },
        {
          id: 'q-roof-1',
          packageId: 'roof',
          partnerId: 'summit',
          text: 'Who sets the roof curbs, the roofer or the mechanical contractor? A-401 and M-101 disagree.',
          askedOn: '2026-09-27',
          answeredOn: null,
          answer: null,
          sentToArchitectOn: '2026-09-27',
        },
        {
          id: 'q-site-1',
          packageId: 'site',
          partnerId: 'lonestar',
          text: 'Is striping part of sitework?',
          askedOn: '2026-09-24',
          answeredOn: '2026-09-26',
          answer: 'Yes. Striping and signs are in sitework. See note 14 on C-101.',
        },
      ],
      sizeNote: '8,400 sq ft shell, three tenant bays',
    },
    {
      id: 'padb',
      name: 'Boerne Retail Pad B',
      startedOn: null,
      packages: [
        {
          id: 'bsite',
          trade: 'Sitework',
          budget: 96000,
          carried: null,
          scope: [
            { id: 'bsite-1', label: 'Clearing and grading' },
            { id: 'bsite-2', label: 'Utilities to 5 ft of the building' },
            { id: 'bsite-3', label: 'Paving' },
          ],
          invites: [],
          awardedInviteId: null,
          selfPerform: null,
          sow: null,
          bidTab: null,
        },
        {
          id: 'bconc',
          trade: 'Concrete',
          budget: 118000,
          carried: null,
          scope: [
            { id: 'bconc-1', label: 'Foundations' },
            { id: 'bconc-2', label: 'Slab on grade' },
            { id: 'bconc-3', label: 'Drive-through lane' },
          ],
          invites: [],
          awardedInviteId: null,
          selfPerform: null,
          sow: null,
          bidTab: null,
        },
        {
          id: 'bplumb',
          trade: 'Plumbing',
          budget: 61000,
          carried: 'self',
          scope: [
            { id: 'bplumb-1', label: 'Underground' },
            { id: 'bplumb-2', label: 'Rough in' },
            { id: 'bplumb-3', label: 'Top out' },
            { id: 'bplumb-4', label: 'Trim' },
          ],
          invites: [],
          awardedInviteId: null,
          selfPerform: { ref: 'BP 518', value: 61000, note: 'Our own bid, priced in Trades mode.' },
          sow: null,
          bidTab: null,
        },
      ],
      stage: 'pursuing',
      owner: 'Cibolo Creek Partners',
      town: 'Boerne',
      customerId: 'cibolo',
      address: '1436 River Rd, Boerne',
      architect: 'Marsh & Vale Architects',
      ownerBilling: null,
      ourBidSentOn: null,
      bidDue: '2026-10-22',
      planSets: [{ rev: 0, touches: [], label: 'Pricing set', issuedOn: '2026-10-01' }],
      generalConditions: 74000,
      contingencyPct: 5,
      feePct: 8,
      team: [
        {
          role: 'projectManager',
          name: 'Dana Whitaker',
          phone: '(210) 555-0131',
          email: 'dana@clickconstruction.example',
        },
      ],
      ownerContractSignedOn: null,
      permitOn: null,
      startDate: null,
      architectId: 'marshvale',
      questions: [],
      sizeNote: '4,200 sq ft drive-through pad building',
    },
    {
      id: 'helotes',
      name: 'Helotes Dental Office',
      startedOn: null,
      packages: [
        {
          id: 'dry',
          trade: 'Framing and drywall',
          budget: 66000,
          carried: 'dry-hillcountry',
          scope: [
            { id: 'dry-1', label: 'Framing' },
            { id: 'dry-2', label: 'Hang and tape' },
            { id: 'dry-3', label: 'Ceilings' },
          ],
          invites: [
            {
              id: 'dry-hillcountry',
              partnerId: 'hillcountry',
              status: 'bid',
              invitedOn: '2026-09-19',
              bid: {
                amount: 64200,
                basedOnRev: 0,
                submittedOn: '2026-08-20',
                includes: { 'dry-1': 'yes', 'dry-2': 'yes', 'dry-3': 'yes' },
                plugs: {},
                note: '',
              },
              seenRev: 0,
            },
          ],
          awardedInviteId: 'dry-hillcountry',
          selfPerform: null,
          sow: {
            status: 'signed',
            price: 64200,
            retainagePct: 10,
            sov: [
              { id: 'dry-1', label: 'Framing', amount: 22000, pctReported: 100, pctBilled: 100 },
              { id: 'dry-2', label: 'Hang and tape', amount: 27200, pctReported: 60, pctBilled: 0 },
              { id: 'dry-3', label: 'Ceilings', amount: 15000, pctReported: 0, pctBilled: 0 },
            ],
            draws: [
              {
                id: 'dry-draw-1',
                number: 1,
                requestedOn: '2026-09-19',
                gross: 22000,
                retainage: 2200,
                net: 19800,
                status: 'paid',
                waiver: 'unconditional',
                lines: [{ sovId: 'dry-1', toPct: 100 }],
                approvedOn: '2026-09-21',
                paidOn: '2026-09-28',
              },
            ],
            basedOnRev: 0,
            signedOn: '2026-08-29',
          },
          bidTab: null,
        },
        {
          id: 'delec',
          trade: 'Electrical',
          budget: 58000,
          carried: 'delec-brightline',
          scope: [
            { id: 'delec-1', label: 'Panels and feeders' },
            { id: 'delec-2', label: 'Lighting' },
            { id: 'delec-3', label: 'Devices' },
            { id: 'delec-4', label: 'Low voltage rough' },
          ],
          invites: [
            {
              id: 'delec-brightline',
              partnerId: 'brightline',
              status: 'bid',
              invitedOn: '2026-09-19',
              bid: {
                amount: 56900,
                basedOnRev: 0,
                submittedOn: '2026-08-21',
                includes: { 'delec-1': 'yes', 'delec-2': 'yes', 'delec-3': 'yes', 'delec-4': 'yes' },
                plugs: {},
                note: '',
              },
              seenRev: 0,
            },
            {
              id: 'delec-voltage',
              partnerId: 'voltage',
              status: 'bid',
              invitedOn: '2026-09-19',
              bid: {
                amount: 61400,
                basedOnRev: 0,
                submittedOn: '2026-08-22',
                includes: { 'delec-1': 'yes', 'delec-2': 'yes', 'delec-3': 'yes', 'delec-4': 'yes' },
                plugs: {},
                note: '',
              },
              seenRev: 0,
            },
          ],
          awardedInviteId: 'delec-brightline',
          selfPerform: null,
          sow: {
            status: 'sent',
            price: 56900,
            retainagePct: 10,
            sov: [
              { id: 'delec-1', label: 'Panels and feeders', amount: 14200, pctReported: 0, pctBilled: 0 },
              { id: 'delec-2', label: 'Lighting', amount: 14200, pctReported: 0, pctBilled: 0 },
              { id: 'delec-3', label: 'Devices', amount: 14200, pctReported: 0, pctBilled: 0 },
              { id: 'delec-4', label: 'Low voltage rough', amount: 14300, pctReported: 0, pctBilled: 0 },
            ],
            draws: [],
            sentOn: '2026-09-30',
            basedOnRev: 0,
            signedOn: null,
          },
          bidTab: null,
        },
        {
          id: 'dhvac',
          trade: 'HVAC',
          budget: 49000,
          carried: 'dhvac-kendall',
          scope: [
            { id: 'dhvac-1', label: 'Split systems' },
            { id: 'dhvac-2', label: 'Ductwork' },
            { id: 'dhvac-3', label: 'Controls' },
          ],
          invites: [
            {
              id: 'dhvac-kendall',
              partnerId: 'kendall',
              status: 'bid',
              invitedOn: '2026-09-19',
              bid: {
                amount: 47600,
                basedOnRev: 0,
                submittedOn: '2026-08-22',
                includes: { 'dhvac-1': 'yes', 'dhvac-2': 'yes', 'dhvac-3': 'yes' },
                plugs: {},
                note: '',
              },
              seenRev: 0,
            },
          ],
          awardedInviteId: 'dhvac-kendall',
          selfPerform: null,
          sow: {
            status: 'draft',
            price: 47600,
            retainagePct: 10,
            sov: [
              { id: 'dhvac-1', label: 'Split systems', amount: 15800, pctReported: 0, pctBilled: 0 },
              { id: 'dhvac-2', label: 'Ductwork', amount: 15800, pctReported: 0, pctBilled: 0 },
              { id: 'dhvac-3', label: 'Controls', amount: 16000, pctReported: 0, pctBilled: 0 },
            ],
            draws: [],
            basedOnRev: 0,
            signedOn: null,
          },
          bidTab: null,
        },
        {
          id: 'dplumb',
          trade: 'Plumbing',
          budget: 38500,
          carried: 'self',
          scope: [
            { id: 'dplumb-1', label: 'Underground' },
            { id: 'dplumb-2', label: 'Rough in' },
            { id: 'dplumb-3', label: 'Top out' },
            { id: 'dplumb-4', label: 'Trim' },
          ],
          invites: [],
          awardedInviteId: null,
          selfPerform: { ref: 'J 1042', value: 38500, note: 'Our own crew. The job runs on the Pipeline.' },
          sow: null,
          bidTab: null,
        },
        {
          id: 'mill',
          trade: 'Millwork',
          budget: 41000,
          carried: 'mill-cedar',
          scope: [
            { id: 'mill-1', label: 'Reception desk' },
            { id: 'mill-2', label: 'Operatory cabinets' },
            { id: 'mill-3', label: 'Break room' },
          ],
          invites: [
            {
              id: 'mill-cedar',
              partnerId: 'cedar',
              status: 'bid',
              invitedOn: '2026-09-19',
              bid: {
                amount: 39800,
                basedOnRev: 0,
                submittedOn: '2026-08-25',
                includes: { 'mill-1': 'yes', 'mill-2': 'yes', 'mill-3': 'yes' },
                plugs: {},
                note: '',
              },
              seenRev: 0,
            },
            {
              id: 'mill-sawtooth',
              partnerId: 'sawtooth',
              status: 'bid',
              invitedOn: '2026-09-19',
              bid: {
                amount: 43100,
                basedOnRev: 0,
                submittedOn: '2026-08-26',
                includes: { 'mill-1': 'yes', 'mill-2': 'yes', 'mill-3': 'yes' },
                plugs: {},
                note: '',
              },
              seenRev: 0,
            },
          ],
          awardedInviteId: null,
          selfPerform: null,
          sow: null,
          bidTab: null,
        },
      ],
      stage: 'buyout',
      owner: 'Dr. Priya Raman',
      town: 'Helotes',
      customerId: 'raman',
      address: '9811 Bandera Rd, Suite 140, Helotes',
      architect: 'Studio Ocotillo',
      ownerBilling: null,
      ourBidSentOn: '2026-08-27',
      bidDue: null,
      planSets: [{ rev: 0, touches: [], label: 'Permit set', issuedOn: '2026-08-11' }],
      generalConditions: 52000,
      contingencyPct: 3,
      feePct: 10,
      team: [
        { role: 'superintendent', name: 'Marcy Pruett', phone: '(210) 555-0152' },
        {
          role: 'projectManager',
          name: 'Dana Whitaker',
          phone: '(210) 555-0131',
          email: 'dana@clickconstruction.example',
        },
      ],
      ownerContractWorth: { dry: 64200, delec: 56900, dhvac: 47600, dplumb: 38500, mill: 39800, gc: 52000, contingency: 8970, fee: 30797 },
      ownerContractSignedOn: '2026-09-04',
      permitOn: null,
      startDate: null,
      architectId: 'ocotillo',
      questions: [
        {
          id: 'q-dry-1',
          packageId: 'dry',
          partnerId: 'hillcountry',
          text: 'Are the operatory walls full height to the deck?',
          askedOn: '2026-08-18',
          answeredOn: '2026-08-19',
          answer: 'Yes, to the deck, with sound batts. See detail 4 on A-201.',
        },
      ],
      sizeNote: '3,100 sq ft tenant finish out, six operatories',
    },
    {
      id: 'fairoaksd',
      name: 'Fair Oaks Shops, Building D',
      startedOn: '2026-07-01',
      packages: [
        {
          id: 'fsite',
          trade: 'Sitework',
          budget: 172000,
          carried: 'fsite-tricounty',
          scope: [
            { id: 'fsite-1', label: 'Clearing and grading' },
            { id: 'fsite-2', label: 'Utilities to 5 ft of the building' },
            { id: 'fsite-3', label: 'Paving' },
            { id: 'fsite-4', label: 'Striping and signs' },
          ],
          invites: [
            {
              id: 'fsite-tricounty',
              partnerId: 'tricounty',
              status: 'bid',
              invitedOn: '2026-04-30',
              bid: {
                amount: 168000,
                basedOnRev: 0,
                submittedOn: '2026-05-07',
                includes: { 'fsite-1': 'yes', 'fsite-2': 'yes', 'fsite-3': 'yes', 'fsite-4': 'yes' },
                plugs: {},
                note: '',
              },
              seenRev: 0,
            },
          ],
          awardedInviteId: 'fsite-tricounty',
          selfPerform: null,
          sow: {
            status: 'signed',
            price: 168000,
            retainagePct: 10,
            sov: [
              { id: 'fsite-1', label: 'Clearing and grading', amount: 42000, pctReported: 100, pctBilled: 100 },
              {
                id: 'fsite-2',
                label: 'Utilities to 5 ft of the building',
                amount: 56000,
                pctReported: 100,
                pctBilled: 100,
              },
              { id: 'fsite-3', label: 'Paving', amount: 54000, pctReported: 100, pctBilled: 100 },
              { id: 'fsite-4', label: 'Striping and signs', amount: 16000, pctReported: 100, pctBilled: 100 },
            ],
            draws: [
              {
                id: 'fsite-draw-1',
                number: 1,
                requestedOn: '2026-07-24',
                gross: 98000,
                retainage: 9800,
                net: 88200,
                status: 'paid',
                waiver: 'unconditional',
                lines: [{ sovId: 'fsite-1', toPct: 100 }, { sovId: 'fsite-2', toPct: 100 }],
                payApp: {
                  periodTo: '2026-07-24',
                  address: '2210 Old San Antonio Rd, Boerne, TX 78006',
                  license: '',
                  signedBy: 'Marisol Vega',
                  signedTitle: 'Owner',
                  signedOn: '2026-07-24',
                },
                approvedOn: '2026-07-26',
                paidOn: '2026-08-02',
              },
              {
                id: 'fsite-draw-2',
                number: 2,
                requestedOn: '2026-08-25',
                gross: 70000,
                retainage: 7000,
                net: 63000,
                status: 'paid',
                waiver: 'unconditional',
                lines: [{ sovId: 'fsite-3', toPct: 100 }, { sovId: 'fsite-4', toPct: 100 }],
                payApp: {
                  periodTo: '2026-08-25',
                  address: '2210 Old San Antonio Rd, Boerne, TX 78006',
                  license: '',
                  signedBy: 'Marisol Vega',
                  signedTitle: 'Owner',
                  signedOn: '2026-08-25',
                },
                approvedOn: '2026-08-27',
                paidOn: '2026-09-03',
              },
            ],
            acceptedOn: '2026-09-08',
            basedOnRev: 0,
            signedOn: '2026-06-08',
          },
          bidTab: null,
        },
        {
          id: 'fconc',
          trade: 'Concrete',
          budget: 220000,
          carried: 'fconc-guadalupe',
          scope: [
            { id: 'fconc-1', label: 'Foundations' },
            { id: 'fconc-2', label: 'Slab on grade' },
            { id: 'fconc-3', label: 'Sidewalks and curbs' },
          ],
          invites: [
            {
              id: 'fconc-guadalupe',
              partnerId: 'guadalupe',
              status: 'bid',
              invitedOn: '2026-04-30',
              bid: {
                amount: 214000,
                basedOnRev: 0,
                submittedOn: '2026-05-09',
                includes: { 'fconc-1': 'yes', 'fconc-2': 'yes', 'fconc-3': 'yes' },
                plugs: {},
                note: '',
              },
              seenRev: 0,
            },
          ],
          awardedInviteId: 'fconc-guadalupe',
          selfPerform: null,
          sow: {
            status: 'signed',
            price: 214000,
            retainagePct: 10,
            sov: [
              { id: 'fconc-1', label: 'Foundations', amount: 78000, pctReported: 100, pctBilled: 100 },
              { id: 'fconc-2', label: 'Slab on grade', amount: 96000, pctReported: 100, pctBilled: 100 },
              { id: 'fconc-3', label: 'Sidewalks and curbs', amount: 40000, pctReported: 100, pctBilled: 100 },
            ],
            draws: [
              {
                id: 'fconc-draw-1',
                number: 1,
                requestedOn: '2026-07-31',
                gross: 78000,
                retainage: 7800,
                net: 70200,
                status: 'paid',
                waiver: 'unconditional',
                lines: [{ sovId: 'fconc-1', toPct: 100 }],
                payApp: {
                  periodTo: '2026-07-31',
                  address: '4415 Rittiman Rd, San Antonio, TX 78218',
                  license: '',
                  signedBy: 'Ines Barrera',
                  signedTitle: 'President',
                  signedOn: '2026-07-31',
                },
                approvedOn: '2026-08-02',
                paidOn: '2026-08-09',
              },
              {
                id: 'fconc-draw-2',
                number: 2,
                requestedOn: '2026-08-29',
                gross: 136000,
                retainage: 13600,
                net: 122400,
                status: 'paid',
                waiver: 'unconditional',
                lines: [{ sovId: 'fconc-2', toPct: 100 }, { sovId: 'fconc-3', toPct: 100 }],
                payApp: {
                  periodTo: '2026-08-29',
                  address: '4415 Rittiman Rd, San Antonio, TX 78218',
                  license: '',
                  signedBy: 'Ines Barrera',
                  signedTitle: 'President',
                  signedOn: '2026-08-29',
                },
                approvedOn: '2026-08-31',
                paidOn: '2026-09-07',
              },
            ],
            acceptedOn: null,
            basedOnRev: 0,
            signedOn: '2026-06-09',
          },
          bidTab: null,
        },
        {
          id: 'fsteel',
          trade: 'Structural steel',
          budget: 190000,
          carried: 'fsteel-ironhorse',
          scope: [
            { id: 'fsteel-1', label: 'Structural steel' },
            { id: 'fsteel-2', label: 'Joists and deck' },
            { id: 'fsteel-3', label: 'Erection' },
          ],
          invites: [
            {
              id: 'fsteel-ironhorse',
              partnerId: 'ironhorse',
              status: 'bid',
              invitedOn: '2026-04-30',
              bid: {
                amount: 186000,
                basedOnRev: 0,
                submittedOn: '2026-05-11',
                includes: { 'fsteel-1': 'yes', 'fsteel-2': 'yes', 'fsteel-3': 'yes' },
                plugs: {},
                note: '',
              },
              seenRev: 0,
            },
          ],
          awardedInviteId: 'fsteel-ironhorse',
          selfPerform: null,
          sow: {
            status: 'signed',
            price: 186000,
            retainagePct: 10,
            sov: [
              { id: 'fsteel-1', label: 'Structural steel', amount: 92000, pctReported: 100, pctBilled: 100 },
              { id: 'fsteel-2', label: 'Joists and deck', amount: 64000, pctReported: 100, pctBilled: 0 },
              { id: 'fsteel-3', label: 'Erection', amount: 30000, pctReported: 80, pctBilled: 0 },
            ],
            draws: [
              {
                id: 'fsteel-draw-1',
                number: 1,
                requestedOn: '2026-08-21',
                gross: 92000,
                retainage: 9200,
                net: 82800,
                status: 'paid',
                waiver: 'unconditional',
                lines: [{ sovId: 'fsteel-1', toPct: 100 }],
                payApp: {
                  periodTo: '2026-08-21',
                  address: '9030 Rigsby Ave, San Antonio, TX 78263',
                  license: '',
                  signedBy: 'Luz Carrasco',
                  signedTitle: 'Project manager',
                  signedOn: '2026-08-21',
                },
                approvedOn: '2026-08-23',
                paidOn: '2026-08-30',
              },
              {
                id: 'fsteel-draw-2',
                number: 2,
                requestedOn: '2026-09-30',
                gross: 88000,
                retainage: 8800,
                net: 79200,
                status: 'requested',
                waiver: 'conditional',
                lines: [{ sovId: 'fsteel-2', toPct: 100 }, { sovId: 'fsteel-3', toPct: 80 }],
                payApp: {
                  periodTo: '2026-09-30',
                  address: '9030 Rigsby Ave, San Antonio, TX 78263',
                  license: '',
                  signedBy: 'Luz Carrasco',
                  signedTitle: 'Project manager',
                  signedOn: '2026-09-30',
                },
              },
            ],
            basedOnRev: 0,
            signedOn: '2026-06-11',
            backCharges: [
              {
                id: 'fsteel-bc-1',
                amount: 1250,
                reason: 'Your crew cut the temporary power line on the north side while setting joists. Our electrician spliced it the same day.',
                photo: 'north-temp-power.jpg',
                sentOn: '2026-09-30',
                answerBy: '2026-10-05',
                status: 'open',
              },
            ],
          },
          bidTab: null,
        },
        {
          id: 'felec',
          trade: 'Electrical',
          budget: 252000,
          carried: 'felec-pecanvalley',
          scope: [
            { id: 'felec-1', label: 'Service and gear' },
            { id: 'felec-2', label: 'Panels and feeders' },
            { id: 'felec-3', label: 'Lighting' },
            { id: 'felec-4', label: 'Fire alarm' },
            { id: 'felec-5', label: 'Site lighting' },
          ],
          invites: [
            {
              id: 'felec-pecanvalley',
              partnerId: 'pecanvalley',
              status: 'bid',
              invitedOn: '2026-04-30',
              bid: {
                amount: 248000,
                basedOnRev: 0,
                submittedOn: '2026-05-12',
                includes: { 'felec-1': 'yes', 'felec-2': 'yes', 'felec-3': 'yes', 'felec-4': 'yes', 'felec-5': 'yes' },
                plugs: {},
                note: '',
                sov: [
                  { label: 'Underground and gear', amount: 70000 },
                  { label: 'Rough-in', amount: 98000 },
                  { label: 'Trim', amount: 56000 },
                  { label: 'Site lighting', amount: 24000 },
                ],
              },
              seenRev: 0,
            },
          ],
          awardedInviteId: 'felec-pecanvalley',
          selfPerform: null,
          sow: {
            status: 'signed',
            price: 248000,
            retainagePct: 10,
            sov: [
              { id: 'felec-1', label: 'Service and gear', amount: 62000, pctReported: 100, pctBilled: 100 },
              { id: 'felec-2', label: 'Panels and feeders', amount: 54000, pctReported: 80, pctBilled: 50 },
              { id: 'felec-3', label: 'Lighting', amount: 72000, pctReported: 40, pctBilled: 0 },
              { id: 'felec-4', label: 'Fire alarm', amount: 36000, pctReported: 0, pctBilled: 0 },
              { id: 'felec-5', label: 'Site lighting', amount: 24000, pctReported: 0, pctBilled: 0 },
            ],
            draws: [
              {
                id: 'felec-draw-1',
                number: 1,
                requestedOn: '2026-08-20',
                gross: 89000,
                retainage: 8900,
                net: 80100,
                status: 'paid',
                waiver: 'conditional',
                lines: [{ sovId: 'felec-1', toPct: 100 }, { sovId: 'felec-2', toPct: 50 }],
                payApp: {
                  periodTo: '2026-08-20',
                  address: '1817 Austin Hwy, San Antonio, TX 78218',
                  license: '',
                  signedBy: 'Marcus Bell',
                  signedTitle: 'Owner',
                  signedOn: '2026-08-20',
                },
                approvedOn: '2026-08-22',
                paidOn: '2026-08-29',
              },
              {
                id: 'felec-draw-2',
                number: 2,
                requestedOn: '2026-10-01',
                gross: 45000,
                retainage: 4500,
                net: 40500,
                status: 'requested',
                waiver: 'conditional',
                lines: [{ sovId: 'felec-2', toPct: 80 }, { sovId: 'felec-3', toPct: 40 }],
                payApp: {
                  periodTo: '2026-09-30',
                  address: '1817 Austin Hwy, San Antonio, TX 78218',
                  license: '',
                  signedBy: 'Marcus Bell',
                  signedTitle: 'Owner',
                  signedOn: '2026-10-01',
                },
              },
            ],
            basedOnRev: 0,
            signedOn: '2026-06-12',
          },
          bidTab: null,
        },
        {
          id: 'froof',
          trade: 'Roofing',
          budget: 136000,
          carried: 'froof-summit',
          scope: [
            { id: 'froof-1', label: 'TPO membrane' },
            { id: 'froof-2', label: 'Insulation' },
            { id: 'froof-3', label: 'Sheet metal and flashing' },
            { id: 'froof-4', label: 'Roof curbs' },
          ],
          invites: [
            {
              id: 'froof-summit',
              partnerId: 'summit',
              status: 'bid',
              invitedOn: '2026-04-30',
              bid: {
                amount: 132000,
                basedOnRev: 0,
                submittedOn: '2026-05-11',
                includes: { 'froof-1': 'yes', 'froof-2': 'yes', 'froof-3': 'yes', 'froof-4': 'yes' },
                plugs: {},
                note: '',
              },
              seenRev: 0,
            },
            {
              id: 'froof-bluebonnet',
              partnerId: 'bluebonnet',
              status: 'bid',
              invitedOn: '2026-04-30',
              bid: {
                amount: 139800,
                basedOnRev: 0,
                submittedOn: '2026-05-12',
                includes: { 'froof-1': 'yes', 'froof-2': 'yes', 'froof-3': 'yes', 'froof-4': 'yes' },
                plugs: {},
                note: '',
              },
              seenRev: 0,
            },
          ],
          awardedInviteId: 'froof-summit',
          selfPerform: null,
          sow: {
            status: 'signed',
            price: 132000,
            retainagePct: 10,
            sov: [
              { id: 'froof-1', label: 'TPO membrane', amount: 64000, pctReported: 100, pctBilled: 0 },
              { id: 'froof-2', label: 'Insulation', amount: 28000, pctReported: 100, pctBilled: 0 },
              { id: 'froof-3', label: 'Sheet metal and flashing', amount: 26000, pctReported: 0, pctBilled: 0 },
              { id: 'froof-4', label: 'Roof curbs', amount: 14000, pctReported: 0, pctBilled: 0 },
            ],
            draws: [],
            sentBack: [
              {
                draw: {
                  id: 'froof-draw-1',
                  number: 1,
                  requestedOn: '2026-09-26',
                  gross: 92000,
                  retainage: 9200,
                  net: 82800,
                  status: 'requested',
                  waiver: 'conditional',
                  lines: [{ sovId: 'froof-1', toPct: 100 }, { sovId: 'froof-2', toPct: 100 }],
                  payApp: {
                    periodTo: '2026-09-25',
                    address: '640 FM 306, New Braunfels, TX 78130',
                    license: '',
                    signedBy: 'Carla Nguyen',
                    signedTitle: 'Office manager',
                    signedOn: '2026-09-26',
                  },
                },
                on: '2026-09-29',
                note: 'The membrane is down on the east half only. The west half is still insulation board.',
                lines: [{ sovId: 'froof-1', weSee: 50 }],
              },
            ],
            basedOnRev: 0,
            signedOn: '2026-06-15',
          },
          bidTab: null,
        },
        {
          id: 'fplumb',
          trade: 'Plumbing',
          budget: 112000,
          carried: 'self',
          scope: [
            { id: 'fplumb-1', label: 'Underground' },
            { id: 'fplumb-2', label: 'Rough in' },
            { id: 'fplumb-3', label: 'Top out' },
            { id: 'fplumb-4', label: 'Trim' },
          ],
          invites: [],
          awardedInviteId: null,
          selfPerform: {
            ref: 'J 1088',
            value: 112000,
            note: 'Our own crew. The job runs on the Pipeline.',
            pctDone: 65,
            pctByLine: { 'fplumb-1': 100, 'fplumb-2': 100, 'fplumb-3': 40, 'fplumb-4': 0 },
          },
          sow: null,
          bidTab: null,
        },
        {
          id: 'fhvac',
          trade: 'HVAC',
          budget: 160000,
          carried: 'fhvac-coolbreeze',
          scope: [
            { id: 'fhvac-1', label: 'Rooftop units' },
            { id: 'fhvac-2', label: 'Ductwork' },
            { id: 'fhvac-3', label: 'Controls' },
            { id: 'fhvac-4', label: 'Test and balance' },
          ],
          invites: [
            {
              id: 'fhvac-coolbreeze',
              partnerId: 'coolbreeze',
              status: 'bid',
              invitedOn: '2026-04-30',
              bid: {
                amount: 158000,
                basedOnRev: 0,
                submittedOn: '2026-05-12',
                includes: { 'fhvac-1': 'yes', 'fhvac-2': 'yes', 'fhvac-3': 'yes', 'fhvac-4': 'yes' },
                plugs: {},
                note: '',
              },
              seenRev: 0,
            },
          ],
          awardedInviteId: 'fhvac-coolbreeze',
          selfPerform: null,
          sow: {
            status: 'signed',
            price: 158000,
            retainagePct: 10,
            sov: [
              { id: 'fhvac-1', label: 'Rooftop units', amount: 72000, pctReported: 0, pctBilled: 0 },
              { id: 'fhvac-2', label: 'Ductwork', amount: 54000, pctReported: 80, pctBilled: 60 },
              { id: 'fhvac-3', label: 'Controls', amount: 18000, pctReported: 0, pctBilled: 0 },
              { id: 'fhvac-4', label: 'Test and balance', amount: 14000, pctReported: 0, pctBilled: 0 },
            ],
            draws: [
              {
                id: 'fhvac-draw-1',
                number: 1,
                requestedOn: '2026-09-22',
                gross: 32400,
                retainage: 3240,
                net: 29160,
                status: 'paid',
                waiver: 'unconditional',
                lines: [{ sovId: 'fhvac-2', toPct: 60 }],
                payApp: {
                  periodTo: '2026-09-22',
                  address: '12700 Toepperwein Rd, Live Oak, TX 78233',
                  license: '',
                  signedBy: 'Andre Wallace',
                  signedTitle: 'Owner',
                  signedOn: '2026-09-22',
                },
                approvedOn: '2026-09-24',
                paidOn: '2026-10-01',
              },
            ],
            basedOnRev: 0,
            signedOn: '2026-06-16',
          },
          bidTab: null,
        },
      ],
      schedule: {
        activities: [
          { lineId: 'fsite-1', packageId: 'fsite', start: '2026-07-06', finish: '2026-07-17', after: [] },
          { lineId: 'fsite-2', packageId: 'fsite', start: '2026-07-13', finish: '2026-07-31', after: [] },
          { lineId: 'fsite-3', packageId: 'fsite', start: '2026-08-10', finish: '2026-08-21', after: ['fsite-2'] },
          { lineId: 'fsite-4', packageId: 'fsite', start: '2026-08-24', finish: '2026-08-28', after: ['fsite-3'] },
          { lineId: 'fconc-1', packageId: 'fconc', start: '2026-07-20', finish: '2026-08-07', after: ['fsite-1'] },
          { lineId: 'fplumb-1', packageId: 'fplumb', start: '2026-07-27', finish: '2026-08-07', after: ['fsite-1'] },
          {
            lineId: 'fconc-2',
            packageId: 'fconc',
            start: '2026-08-10',
            finish: '2026-08-28',
            after: ['fconc-1', 'fplumb-1'],
          },
          { lineId: 'fconc-3', packageId: 'fconc', start: '2026-08-31', finish: '2026-09-11', after: ['fsite-3'] },
          { lineId: 'fsteel-1', packageId: 'fsteel', start: '2026-08-17', finish: '2026-09-04', after: ['fconc-1'] },
          { lineId: 'fsteel-2', packageId: 'fsteel', start: '2026-09-07', finish: '2026-09-18', after: ['fsteel-1'] },
          { lineId: 'fsteel-3', packageId: 'fsteel', start: '2026-09-07', finish: '2026-10-02', after: ['fsteel-1'] },
          { lineId: 'froof-2', packageId: 'froof', start: '2026-09-21', finish: '2026-09-30', after: ['fsteel-2'] },
          { lineId: 'froof-1', packageId: 'froof', start: '2026-09-21', finish: '2026-10-09', after: ['fsteel-2'] },
          { lineId: 'froof-3', packageId: 'froof', start: '2026-10-12', finish: '2026-10-21', after: ['froof-1'] },
          { lineId: 'froof-4', packageId: 'froof', start: '2026-10-05', finish: '2026-10-09', after: ['fsteel-2'] },
          { lineId: 'felec-1', packageId: 'felec', start: '2026-08-24', finish: '2026-09-11', after: ['fconc-1'] },
          { lineId: 'felec-2', packageId: 'felec', start: '2026-09-14', finish: '2026-10-02', after: ['felec-1'] },
          { lineId: 'felec-3', packageId: 'felec', start: '2026-09-14', finish: '2026-10-23', after: ['felec-1'] },
          { lineId: 'felec-5', packageId: 'felec', start: '2026-10-19', finish: '2026-10-30', after: ['fconc-3'] },
          {
            lineId: 'felec-4',
            packageId: 'felec',
            start: '2026-11-02',
            finish: '2026-11-20',
            after: ['felec-3', 'fairoaksd-insp-roughin'],
          },
          { lineId: 'fplumb-2', packageId: 'fplumb', start: '2026-09-14', finish: '2026-09-25', after: ['fconc-2'] },
          { lineId: 'fplumb-3', packageId: 'fplumb', start: '2026-09-28', finish: '2026-10-09', after: ['fplumb-2'] },
          { lineId: 'fhvac-2', packageId: 'fhvac', start: '2026-09-14', finish: '2026-10-09', after: ['fsteel-1'] },
          { lineId: 'fhvac-1', packageId: 'fhvac', start: '2026-10-12', finish: '2026-10-23', after: ['froof-1'] },
          {
            lineId: 'fhvac-3',
            packageId: 'fhvac',
            start: '2026-11-02',
            finish: '2026-11-13',
            after: ['fhvac-1', 'fairoaksd-insp-roughin'],
          },
          {
            lineId: 'fplumb-4',
            packageId: 'fplumb',
            start: '2026-11-30',
            finish: '2026-12-04',
            after: ['fplumb-3', 'fairoaksd-insp-roughin'],
          },
          { lineId: 'fhvac-4', packageId: 'fhvac', start: '2026-11-30', finish: '2026-12-04', after: ['fhvac-3'] },
          {
            lineId: 'fairoaksd-insp-roughin',
            packageId: '',
            start: '2026-10-12',
            finish: '2026-10-13',
            after: ['felec-2', 'fplumb-3', 'fhvac-2'],
            inspection: { label: 'Rough-in inspection' },
          },
          {
            lineId: 'fairoaksd-insp-service',
            packageId: '',
            start: '2026-10-02',
            finish: '2026-10-02',
            after: ['felec-1'],
            inspection: {
              label: 'Electrical service inspection',
              failed: [
                {
                  on: '2026-09-28',
                  note: 'The main bonding jumper is missing at the service panel.',
                  packageIds: ['felec'],
                  reinspectOn: '2026-10-02',
                },
              ],
            },
          },
          {
            lineId: 'fairoaksd-insp-final',
            packageId: '',
            start: '2026-12-07',
            finish: '2026-12-08',
            after: [
              'fsite-4',
              'fsteel-3',
              'froof-2',
              'froof-3',
              'froof-4',
              'felec-5',
              'felec-4',
              'fplumb-4',
              'fhvac-4',
              'fairoaksd-insp-service',
            ],
            inspection: { label: 'Final inspection' },
          },
        ],
        milestones: [
          { id: 'fo-slab', label: 'Slab poured', planned: '2026-08-28', packageId: 'fconc', metOn: '2026-08-27' },
          { id: 'fo-dryin', label: 'Dry-in', planned: '2026-09-25', packageId: 'froof', metOn: null },
          { id: 'fo-roughin', label: 'Rough-in inspection', planned: '2026-10-13', packageId: null, metOn: null },
          { id: 'fo-substantial', label: 'Substantial completion', planned: '2026-12-11', packageId: null, metOn: null },
        ],
        baseline: {
          lockedOn: '2026-07-01',
          activities: {
            'fsite-1': { start: '2026-07-06', finish: '2026-07-17' },
            'fsite-2': { start: '2026-07-13', finish: '2026-07-31' },
            'fsite-3': { start: '2026-08-10', finish: '2026-08-21' },
            'fsite-4': { start: '2026-08-24', finish: '2026-08-28' },
            'fconc-1': { start: '2026-07-20', finish: '2026-08-07' },
            'fplumb-1': { start: '2026-07-27', finish: '2026-08-07' },
            'fconc-2': { start: '2026-08-10', finish: '2026-08-28' },
            'fconc-3': { start: '2026-08-31', finish: '2026-09-11' },
            'fsteel-1': { start: '2026-08-17', finish: '2026-09-04' },
            'fsteel-2': { start: '2026-09-07', finish: '2026-09-18' },
            'fsteel-3': { start: '2026-09-07', finish: '2026-10-02' },
            'froof-2': { start: '2026-09-21', finish: '2026-09-30' },
            'froof-1': { start: '2026-09-14', finish: '2026-10-02' },
            'froof-3': { start: '2026-10-05', finish: '2026-10-14' },
            'froof-4': { start: '2026-10-05', finish: '2026-10-09' },
            'felec-1': { start: '2026-08-24', finish: '2026-09-11' },
            'felec-2': { start: '2026-09-14', finish: '2026-10-02' },
            'felec-3': { start: '2026-09-14', finish: '2026-10-23' },
            'felec-5': { start: '2026-10-19', finish: '2026-10-30' },
            'felec-4': { start: '2026-11-02', finish: '2026-11-20' },
            'fplumb-2': { start: '2026-09-14', finish: '2026-09-25' },
            'fplumb-3': { start: '2026-09-28', finish: '2026-10-09' },
            'fhvac-2': { start: '2026-09-14', finish: '2026-10-09' },
            'fhvac-1': { start: '2026-10-12', finish: '2026-10-23' },
            'fhvac-3': { start: '2026-11-02', finish: '2026-11-13' },
            'fplumb-4': { start: '2026-11-30', finish: '2026-12-04' },
            'fhvac-4': { start: '2026-11-30', finish: '2026-12-04' },
            'fairoaksd-insp-roughin': { start: '2026-10-12', finish: '2026-10-13' },
            'fairoaksd-insp-service': { start: '2026-09-28', finish: '2026-09-28' },
            'fairoaksd-insp-final': { start: '2026-12-07', finish: '2026-12-08' },
          },
        },
        lookAhead: [
          {
            weekOf: '2026-09-14',
            lineId: 'fsteel-2',
            packageId: 'fsteel',
            done: true,
            markedOn: '2026-09-18',
            verifiedOn: '2026-09-21',
          },
          {
            weekOf: '2026-09-14',
            lineId: 'fsteel-3',
            packageId: 'fsteel',
            done: true,
            markedOn: '2026-09-18',
            verifiedOn: '2026-09-21',
          },
          {
            weekOf: '2026-09-14',
            lineId: 'felec-2',
            packageId: 'felec',
            done: false,
            reason: 'materials',
            markedOn: '2026-09-18',
            verifiedOn: '2026-09-21',
          },
          {
            weekOf: '2026-09-14',
            lineId: 'fplumb-2',
            packageId: 'fplumb',
            done: true,
            markedOn: '2026-09-18',
            verifiedOn: '2026-09-21',
          },
          {
            weekOf: '2026-09-14',
            lineId: 'fhvac-2',
            packageId: 'fhvac',
            done: true,
            markedOn: '2026-09-18',
            verifiedOn: '2026-09-21',
          },
          {
            weekOf: '2026-09-21',
            lineId: 'froof-1',
            packageId: 'froof',
            done: false,
            reason: 'weather',
            markedOn: '2026-09-25',
            verifiedOn: '2026-09-28',
          },
          {
            weekOf: '2026-09-21',
            lineId: 'froof-2',
            packageId: 'froof',
            done: true,
            markedOn: '2026-09-25',
            verifiedOn: '2026-09-28',
          },
          {
            weekOf: '2026-09-21',
            lineId: 'fsteel-3',
            packageId: 'fsteel',
            done: false,
            reason: 'crew',
            markedOn: '2026-09-25',
            verifiedOn: '2026-09-28',
          },
          {
            weekOf: '2026-09-21',
            lineId: 'fplumb-2',
            packageId: 'fplumb',
            done: true,
            markedOn: '2026-09-25',
            verifiedOn: '2026-09-28',
          },
          {
            weekOf: '2026-09-21',
            lineId: 'fhvac-2',
            packageId: 'fhvac',
            done: true,
            markedOn: '2026-09-25',
            verifiedOn: '2026-09-28',
          },
          {
            weekOf: '2026-09-28',
            lineId: 'froof-1',
            packageId: 'froof',
            done: true,
            markedOn: '2026-10-02',
            verifiedOn: null,
          },
          {
            weekOf: '2026-09-28',
            lineId: 'fsteel-3',
            packageId: 'fsteel',
            done: false,
            reason: 'crew',
            markedOn: '2026-10-02',
            verifiedOn: null,
          },
          {
            weekOf: '2026-09-28',
            lineId: 'felec-2',
            packageId: 'felec',
            done: false,
            reason: 'materials',
            markedOn: '2026-10-02',
            verifiedOn: null,
          },
          {
            weekOf: '2026-09-28',
            lineId: 'fplumb-3',
            packageId: 'fplumb',
            done: true,
            markedOn: '2026-10-02',
            verifiedOn: '2026-10-02',
          },
          {
            weekOf: '2026-09-28',
            lineId: 'fhvac-2',
            packageId: 'fhvac',
            done: true,
            markedOn: '2026-10-02',
            verifiedOn: null,
          },
        ],
      },
      stage: 'building',
      owner: 'Cibolo Creek Partners',
      town: 'Boerne',
      waits: [
        {
          id: 'fairoaksd-wait-1',
          kind: 'delivery',
          title: 'Rooftop units',
          packageId: 'fhvac',
          who: 'Cool Breeze Mechanical\'s supplier',
          lineIds: ['fhvac-1'],
          askedOn: '2026-09-01',
          expectedOn: '2026-10-20',
          shippedOn: null,
          doneOn: null,
          note: 'Carrier: two of the four are built; the rest ship Oct 15.',
        },
        {
          id: 'fairoaksd-wait-2',
          kind: 'decision',
          title: 'the restroom tile',
          packageId: 'fplumb',
          who: 'Cibolo Creek Partners',
          lineIds: ['fplumb-4'],
          askedOn: '2026-09-28',
          expectedOn: '2026-10-30',
          doneOn: null,
        },
        {
          id: 'fairoaksd-wait-3',
          kind: 'utility',
          title: 'The transformer',
          packageId: null,
          who: 'CPS Energy',
          lineIds: ['felec-5'],
          askedOn: '2026-09-15',
          expectedOn: '2026-10-15',
          doneOn: null,
        },
      ],
      dailyLogs: [
        {
          date: '2026-09-21',
          sky: 'clear',
          high: 88,
          low: 68,
          weatherStop: false,
          crews: [
            { packageId: 'fsteel', workers: 5 },
            { packageId: 'froof', workers: 4 },
            { packageId: 'felec', workers: 3 },
            { packageId: 'fplumb', workers: 3 },
            { packageId: 'fhvac', workers: 3 },
          ],
          done: 'Deck welded on the north half. Roofers set insulation on the east bays. Panels B and C hung.',
          delays: [],
          visitors: '',
          writtenOn: '2026-09-21',
        },
        {
          date: '2026-09-22',
          sky: 'clear',
          high: 90,
          low: 70,
          weatherStop: false,
          crews: [
            { packageId: 'fsteel', workers: 5 },
            { packageId: 'froof', workers: 5 },
            { packageId: 'felec', workers: 3 },
            { packageId: 'fplumb', workers: 3 },
            { packageId: 'fhvac', workers: 3 },
          ],
          done: 'Insulation down on all four bays. Duct mains run in bays 1 and 2.',
          delays: [],
          visitors: '',
          writtenOn: '2026-09-22',
        },
        {
          date: '2026-09-23',
          sky: 'cloudy',
          high: 86,
          low: 71,
          weatherStop: false,
          crews: [
            { packageId: 'fsteel', workers: 3 },
            { packageId: 'froof', workers: 5 },
            { packageId: 'felec', workers: 3 },
            { packageId: 'fplumb', workers: 3 },
            { packageId: 'fhvac', workers: 3 },
          ],
          done: 'Membrane started on the east half.',
          delays: [{ packageId: 'fsteel', reason: 'crew', note: 'Iron Horse came with three ironworkers, not five.' }],
          visitors: '',
          writtenOn: '2026-09-23',
        },
        {
          date: '2026-09-24',
          sky: 'rain',
          high: 78,
          low: 69,
          weatherStop: false,
          crews: [{ packageId: 'felec', workers: 3 }, { packageId: 'fplumb', workers: 3 }, { packageId: 'fhvac', workers: 2 }],
          done: 'Inside work only. Feeders pulled in bay 3.',
          delays: [{ packageId: 'froof', reason: 'weather', note: 'Rain all day. The membrane cannot go down wet.' }],
          visitors: '',
          writtenOn: '2026-09-24',
        },
        {
          date: '2026-09-25',
          sky: 'storm',
          high: 75,
          low: 66,
          weatherStop: true,
          crews: [{ packageId: 'felec', workers: 2 }],
          done: 'Lightning by noon. Everyone off the site at 12:30.',
          delays: [{ packageId: null, reason: 'weather', note: 'Work stopped at 12:30 for lightning.' }],
          visitors: '',
          writtenOn: '2026-09-25',
        },
        {
          date: '2026-09-28',
          sky: 'clear',
          high: 87,
          low: 67,
          weatherStop: false,
          crews: [
            { packageId: 'fsteel', workers: 4 },
            { packageId: 'froof', workers: 5 },
            { packageId: 'felec', workers: 3 },
            { packageId: 'fplumb', workers: 3 },
            { packageId: 'fhvac', workers: 3 },
          ],
          done: 'Membrane down on the east half. Canopy steel set.',
          delays: [],
          visitors: 'City inspector: the electrical service inspection failed, the bonding jumper is missing.',
          writtenOn: '2026-09-28',
        },
        {
          date: '2026-09-29',
          sky: 'clear',
          high: 89,
          low: 69,
          weatherStop: false,
          crews: [
            { packageId: 'fsteel', workers: 4 },
            { packageId: 'froof', workers: 5 },
            { packageId: 'felec', workers: 2 },
            { packageId: 'fplumb', workers: 3 },
            { packageId: 'fhvac', workers: 3 },
          ],
          done: 'Membrane started on the west half.',
          delays: [{ packageId: 'felec', reason: 'materials', note: 'Panel boards are two weeks out.' }],
          visitors: '',
          writtenOn: '2026-09-29',
        },
        {
          date: '2026-10-01',
          sky: 'cloudy',
          high: 85,
          low: 70,
          weatherStop: false,
          crews: [
            { packageId: 'fsteel', workers: 3 },
            { packageId: 'froof', workers: 4 },
            { packageId: 'felec', workers: 2 },
            { packageId: 'fplumb', workers: 3 },
            { packageId: 'fhvac', workers: 3 },
          ],
          done: 'West half membrane half down. Ductwork in bay 4.',
          delays: [],
          visitors: 'Cibolo\'s rep walked bays 1 and 2.',
          writtenOn: '2026-10-01',
        },
      ],
      customerId: 'cibolo',
      address: '7920 Fair Oaks Pkwy, Fair Oaks Ranch',
      architect: 'Marsh & Vale Architects',
      punch: [
        {
          id: 'fairoaksd-punch-1',
          packageId: 'fconc',
          text: 'Patch the spalled corner on the column footing',
          where: 'Grid C-4',
          addedOn: '2026-09-28',
          fixedOn: null,
          checkedOn: null,
        },
        {
          id: 'fairoaksd-punch-2',
          packageId: 'fconc',
          text: 'Seal the control joints in the stockroom slab',
          where: 'Stockroom',
          addedOn: '2026-09-28',
          fixedOn: '2026-10-01',
          checkedOn: null,
        },
        {
          id: 'fairoaksd-punch-3',
          packageId: 'fconc',
          text: 'Clean the curb paint off the sidewalk',
          where: 'East entry',
          addedOn: '2026-09-28',
          fixedOn: '2026-09-30',
          checkedOn: '2026-10-01',
        },
      ],
      submittals: [
        {
          id: 'fairoaksd-sub-1',
          number: '26 24 16-01',
          packageId: 'felec',
          title: 'Panelboards',
          kind: 'product data',
          specSection: '26 24 16',
          lineIds: ['felec-2'],
          leadDays: 21,
          askedOn: '2026-08-03',
          rounds: [
            {
              sentOn: '2026-08-10',
              file: 'PVE-panelboards.pdf',
              note: '',
              toArchitectOn: '2026-08-11',
              answeredOn: '2026-08-18',
              answer: 'revise',
              answerNote: 'Show the 22kA rating on each panel.',
            },
            {
              sentOn: '2026-08-28',
              file: 'PVE-panelboards-r1.pdf',
              note: 'Ratings added.',
              toArchitectOn: '2026-08-29',
              answeredOn: '2026-09-08',
              answer: 'approved as noted',
              answerNote: 'Label the spare breakers.',
            },
          ],
        },
        {
          id: 'fairoaksd-sub-2',
          number: '28 31 11-01',
          packageId: 'felec',
          title: 'Fire alarm',
          kind: 'shop drawings',
          specSection: '28 31 11',
          lineIds: ['felec-4'],
          leadDays: 14,
          askedOn: '2026-09-01',
          rounds: [
            {
              sentOn: '2026-09-29',
              file: 'PVE-fire-alarm.pdf',
              note: 'Device layout and riser.',
              toArchitectOn: '2026-09-30',
              answeredOn: null,
              answer: null,
              answerNote: '',
            },
          ],
        },
        {
          id: 'fairoaksd-sub-3',
          number: '23 81 19-01',
          packageId: 'fhvac',
          title: 'Rooftop units',
          kind: 'product data',
          specSection: '23 81 19',
          lineIds: ['fhvac-1'],
          leadDays: 30,
          askedOn: '2026-08-03',
          rounds: [
            {
              sentOn: '2026-08-20',
              file: 'CBM-RTU-submittal.pdf',
              note: '',
              toArchitectOn: '2026-08-21',
              answeredOn: '2026-08-28',
              answer: 'approved',
              answerNote: '',
            },
          ],
        },
        {
          id: 'fairoaksd-sub-4',
          number: '23 09 23-01',
          packageId: 'fhvac',
          title: 'Controls',
          kind: 'shop drawings',
          specSection: '23 09 23',
          lineIds: ['fhvac-3'],
          leadDays: 10,
          askedOn: '2026-09-15',
          rounds: [],
        },
        {
          id: 'fairoaksd-sub-5',
          number: '07 54 23-01',
          packageId: 'froof',
          title: 'TPO membrane',
          kind: 'samples',
          specSection: '07 54 23',
          lineIds: ['froof-1'],
          leadDays: 7,
          askedOn: '2026-08-03',
          rounds: [
            {
              sentOn: '2026-08-25',
              file: 'Summit-TPO-samples',
              note: 'Two samples sent by courier.',
              toArchitectOn: '2026-08-26',
              answeredOn: '2026-09-01',
              answer: 'approved',
              answerNote: '',
            },
          ],
        },
        {
          id: 'fairoaksd-sub-6',
          number: '07 62 00-01',
          packageId: 'froof',
          title: 'Sheet metal and flashing',
          kind: 'shop drawings',
          specSection: '07 62 00',
          lineIds: ['froof-3'],
          leadDays: 10,
          askedOn: '2026-09-15',
          rounds: [
            {
              sentOn: '2026-10-01',
              file: 'Summit-flashing.pdf',
              note: 'Coping detail per A-501.',
              toArchitectOn: null,
              answeredOn: null,
              answer: null,
              answerNote: '',
            },
          ],
        },
      ],
      rfis: [
        {
          id: 'fairoaksd-rfi-1',
          number: 1,
          question: 'Digging for the bay 4 sidewalk we found an old gas line that is not on C-101. Do we remove it or cap it?',
          sheets: ['C-101'],
          packageId: 'fsite',
          partnerId: null,
          askedOn: '2026-09-02',
          holds: ['fconc-3'],
          neededDays: 3,
          sentToArchitectOn: '2026-09-02',
          answer: {
            on: '2026-09-08',
            text: 'Cap it at the property line and take out the rest.',
            by: 'architect',
            impact: 'cost',
            cost: 3800,
            days: 2,
          },
          changeOrderId: null,
        },
        {
          id: 'fairoaksd-rfi-2',
          number: 2,
          question: 'The roof drain at grid C-4 lands on a joist on S-201. Can it move east one joist bay?',
          sheets: ['S-201'],
          packageId: 'froof',
          partnerId: 'summit',
          askedOn: '2026-09-21',
          holds: ['froof-1'],
          neededDays: 3,
          sentToArchitectOn: '2026-09-21',
          answer: {
            on: '2026-09-25',
            text: 'Yes. Move it 18 inches east. No change in cost.',
            by: 'architect',
            impact: 'none',
            cost: 0,
            days: 0,
          },
          changeOrderId: null,
        },
        {
          id: 'fairoaksd-rfi-3',
          number: 3,
          question: 'A-201 shows the storefront at bay 3 where M-101 runs the RTU-2 condensate line. Which one moves?',
          sheets: ['A-201', 'M-101'],
          packageId: 'fhvac',
          partnerId: 'coolbreeze',
          askedOn: '2026-09-29',
          holds: ['fhvac-1'],
          neededDays: 3,
          sentToArchitectOn: '2026-09-30',
          answer: null,
          changeOrderId: null,
        },
        {
          id: 'fairoaksd-rfi-4',
          number: 4,
          question: 'The roof curb on A-501 is 48 by 60 inches. The approved rooftop unit needs 54 by 72. Which size do we set?',
          sheets: ['A-501', 'M-101'],
          packageId: 'froof',
          partnerId: 'summit',
          askedOn: '2026-10-01',
          holds: ['froof-4'],
          neededDays: 3,
          sentToArchitectOn: null,
          answer: null,
          changeOrderId: null,
        },
      ],
      ownerBilling: {
        billed: 956327.91,
        paid: 571816.61,
        retainageHeld: 95632.79,
        payApps: [
          {
            number: 1,
            periodTo: '2026-07-25',
            sentOn: '2026-07-25',
            doneToDate: {
              fsite: 98000,
              fconc: 46800,
              fsteel: 0,
              felec: 0,
              froof: 0,
              fplumb: 22400,
              fhvac: 0,
              gc: 13178.33,
              contingency: 5411.35,
              fee: 18578.97,
            },
            workToDate: 204368.65,
            retainagePct: 10,
            retainage: 20436.87,
            due: 183931.78,
            paidOn: '2026-09-01',
          },
          {
            number: 2,
            periodTo: '2026-08-25',
            sentOn: '2026-08-25',
            doneToDate: {
              fsite: 168000,
              fconc: 126000,
              fsteel: 92000,
              felec: 89000,
              froof: 0,
              fplumb: 44800,
              fhvac: 0,
              gc: 40969.46,
              contingency: 16823.08,
              fee: 57759.25,
            },
            workToDate: 635351.79,
            retainagePct: 10,
            retainage: 63535.18,
            due: 387884.83,
            paidOn: '2026-10-01',
          },
          {
            number: 3,
            periodTo: '2026-09-25',
            sentOn: '2026-09-25',
            doneToDate: {
              fsite: 168000,
              fconc: 214000,
              fsteel: 171000,
              felec: 103400,
              froof: 32000,
              fplumb: 61600,
              fhvac: 32400,
              gc: 61667,
              contingency: 25322.01,
              fee: 86938.9,
            },
            workToDate: 956327.91,
            retainagePct: 10,
            retainage: 95632.79,
            due: 288878.51,
            paidOn: null,
            promises: [
              {
                by: '2026-09-30',
                madeOn: '2026-09-26',
                note: 'Their controller said checks go out Wednesday the 30th',
                who: 'office',
              },
            ],
          },
        ],
      },
      ourBidSentOn: '2026-05-14',
      bidDue: null,
      planSets: [{ rev: 0, touches: [], label: 'Permit set', issuedOn: '2026-04-28' }],
      generalConditions: 96000,
      contingencyPct: 3,
      feePct: 10,
      team: [
        { role: 'superintendent', name: 'Luis Ortega', phone: '(210) 555-0147' },
        {
          role: 'projectManager',
          name: 'Dana Whitaker',
          phone: '(210) 555-0131',
          email: 'dana@clickconstruction.example',
        },
      ],
      ownerContractWorth: {
        fsite: 168000,
        fconc: 214000,
        fsteel: 186000,
        felec: 248000,
        froof: 132000,
        fplumb: 112000,
        fhvac: 158000,
        gc: 96000,
        contingency: 39420,
        fee: 135342,
      },
      ownerContractSignedOn: '2026-06-02',
      permitOn: '2026-06-20',
      startDate: '2026-07-06',
      architectId: 'marshvale',
      questions: [],
      changeRequests: [
        {
          id: 'fairoaksd-cr-1',
          packageId: 'fsite',
          partnerId: 'tricounty',
          askedOn: '2026-09-30',
          description: 'Rock at the north footings, about 390 cubic yards to break out and haul off',
          reason: 'field',
          amount: 14820,
          days: 2,
          file: 'north-footings-rock.jpg',
          changeOrderId: null,
          turnedDown: null,
        },
      ],
      sizeNote: '9,600 sq ft retail shell, four bays',
    },
    {
      id: 'stoneoak',
      name: 'Stone Oak Pharmacy',
      startedOn: '2026-06-12',
      packages: [
        {
          id: 'sdry',
          trade: 'Framing and drywall',
          budget: 43000,
          carried: 'sdry-liveoak',
          scope: [
            { id: 'sdry-1', label: 'Framing' },
            { id: 'sdry-2', label: 'Hang and tape' },
            { id: 'sdry-3', label: 'Ceilings' },
          ],
          invites: [
            {
              id: 'sdry-liveoak',
              partnerId: 'liveoak',
              status: 'bid',
              invitedOn: '2026-09-19',
              bid: {
                amount: 42000,
                basedOnRev: 0,
                submittedOn: '2026-05-06',
                includes: { 'sdry-1': 'yes', 'sdry-2': 'yes', 'sdry-3': 'yes' },
                plugs: {},
                note: '',
              },
              seenRev: 0,
            },
          ],
          awardedInviteId: 'sdry-liveoak',
          selfPerform: null,
          sow: {
            status: 'signed',
            price: 42000,
            retainagePct: 10,
            sov: [
              { id: 'sdry-1', label: 'Framing', amount: 21000, pctReported: 100, pctBilled: 100 },
              { id: 'sdry-2', label: 'Hang and tape', amount: 12000, pctReported: 100, pctBilled: 100 },
              { id: 'sdry-3', label: 'Ceilings', amount: 9000, pctReported: 100, pctBilled: 100 },
            ],
            draws: [
              {
                id: 'sdry-draw-1',
                number: 1,
                requestedOn: '2026-07-20',
                gross: 21000,
                retainage: 2100,
                net: 18900,
                status: 'paid',
                waiver: 'unconditional',
                lines: [{ sovId: 'sdry-1', toPct: 100 }],
                approvedOn: '2026-07-22',
                paidOn: '2026-07-29',
              },
              {
                id: 'sdry-draw-2',
                number: 2,
                requestedOn: '2026-09-18',
                gross: 21000,
                retainage: 2100,
                net: 18900,
                status: 'paid',
                waiver: 'unconditional',
                lines: [{ sovId: 'sdry-2', toPct: 100 }, { sovId: 'sdry-3', toPct: 100 }],
                approvedOn: '2026-09-20',
                paidOn: '2026-09-27',
              },
              {
                id: 'sdry-draw-3',
                number: 3,
                requestedOn: '2026-09-30',
                gross: 0,
                retainage: -4200,
                net: 4200,
                status: 'requested',
                waiver: 'conditional',
                lines: [],
                payApp: {
                  periodTo: '2026-09-30',
                  address: '5410 Bandera Rd, San Antonio, TX 78238',
                  license: '',
                  signedBy: 'Darnell Pruitt',
                  signedTitle: 'Owner',
                  signedOn: '2026-09-30',
                },
                final: true,
              },
            ],
            acceptedOn: '2026-09-24',
            basedOnRev: 0,
            signedOn: '2026-06-02',
          },
          bidTab: null,
        },
        {
          id: 'selec',
          trade: 'Electrical',
          budget: 39000,
          carried: 'selec-westside',
          scope: [
            { id: 'selec-1', label: 'Panels and feeders' },
            { id: 'selec-2', label: 'Lighting' },
            { id: 'selec-3', label: 'Devices' },
          ],
          invites: [
            {
              id: 'selec-westside',
              partnerId: 'westside',
              status: 'bid',
              invitedOn: '2026-09-19',
              bid: {
                amount: 38000,
                basedOnRev: 0,
                submittedOn: '2026-05-07',
                includes: { 'selec-1': 'yes', 'selec-2': 'yes', 'selec-3': 'yes' },
                plugs: {},
                note: '',
              },
              seenRev: 0,
            },
          ],
          awardedInviteId: 'selec-westside',
          selfPerform: null,
          sow: {
            status: 'signed',
            price: 38000,
            retainagePct: 10,
            sov: [
              { id: 'selec-1', label: 'Panels and feeders', amount: 14000, pctReported: 100, pctBilled: 100 },
              { id: 'selec-2', label: 'Lighting', amount: 14000, pctReported: 100, pctBilled: 100 },
              { id: 'selec-3', label: 'Devices', amount: 10000, pctReported: 100, pctBilled: 100 },
            ],
            draws: [
              {
                id: 'selec-draw-1',
                number: 1,
                requestedOn: '2026-07-22',
                gross: 14000,
                retainage: 1400,
                net: 12600,
                status: 'paid',
                waiver: 'unconditional',
                lines: [{ sovId: 'selec-1', toPct: 100 }],
                approvedOn: '2026-07-24',
                paidOn: '2026-07-31',
              },
              {
                id: 'selec-draw-2',
                number: 2,
                requestedOn: '2026-09-19',
                gross: 24000,
                retainage: 2400,
                net: 21600,
                status: 'paid',
                waiver: 'unconditional',
                lines: [{ sovId: 'selec-2', toPct: 100 }, { sovId: 'selec-3', toPct: 100 }],
                approvedOn: '2026-09-21',
                paidOn: '2026-09-28',
              },
              {
                id: 'selec-draw-3',
                number: 3,
                requestedOn: '2026-09-30',
                gross: 0,
                retainage: -3800,
                net: 3800,
                status: 'requested',
                waiver: 'conditional',
                lines: [],
                payApp: {
                  periodTo: '2026-09-30',
                  address: '2210 Fredericksburg Rd, San Antonio, TX 78201',
                  license: 'TECL 31876',
                  signedBy: 'Ana Flores',
                  signedTitle: 'Owner',
                  signedOn: '2026-09-30',
                },
                final: true,
              },
            ],
            acceptedOn: '2026-09-24',
            basedOnRev: 0,
            signedOn: '2026-06-03',
          },
          bidTab: null,
        },
        {
          id: 'shvac',
          trade: 'HVAC',
          budget: 32000,
          carried: 'shvac-coolbreeze',
          scope: [
            { id: 'shvac-1', label: 'Split systems' },
            { id: 'shvac-2', label: 'Ductwork' },
            { id: 'shvac-3', label: 'Controls' },
          ],
          invites: [
            {
              id: 'shvac-coolbreeze',
              partnerId: 'coolbreeze',
              status: 'bid',
              invitedOn: '2026-09-19',
              bid: {
                amount: 31000,
                basedOnRev: 0,
                submittedOn: '2026-05-08',
                includes: { 'shvac-1': 'yes', 'shvac-2': 'yes', 'shvac-3': 'yes' },
                plugs: {},
                note: '',
              },
              seenRev: 0,
            },
          ],
          awardedInviteId: 'shvac-coolbreeze',
          selfPerform: null,
          sow: {
            status: 'signed',
            price: 31000,
            retainagePct: 10,
            sov: [
              { id: 'shvac-1', label: 'Split systems', amount: 13000, pctReported: 100, pctBilled: 100 },
              { id: 'shvac-2', label: 'Ductwork', amount: 12000, pctReported: 100, pctBilled: 100 },
              { id: 'shvac-3', label: 'Controls', amount: 6000, pctReported: 100, pctBilled: 100 },
            ],
            draws: [
              {
                id: 'shvac-draw-1',
                number: 1,
                requestedOn: '2026-08-18',
                gross: 25000,
                retainage: 2500,
                net: 22500,
                status: 'paid',
                waiver: 'unconditional',
                lines: [{ sovId: 'shvac-1', toPct: 100 }, { sovId: 'shvac-2', toPct: 100 }],
                approvedOn: '2026-08-20',
                paidOn: '2026-08-27',
              },
              {
                id: 'shvac-draw-2',
                number: 2,
                requestedOn: '2026-09-22',
                gross: 6000,
                retainage: 600,
                net: 5400,
                status: 'paid',
                waiver: 'unconditional',
                lines: [{ sovId: 'shvac-3', toPct: 100 }],
                approvedOn: '2026-09-24',
                paidOn: '2026-10-01',
              },
            ],
            acceptedOn: '2026-09-29',
            basedOnRev: 0,
            signedOn: '2026-06-04',
          },
          bidTab: null,
        },
        {
          id: 'splumb',
          trade: 'Plumbing',
          budget: 26000,
          carried: 'self',
          scope: [
            { id: 'splumb-1', label: 'Underground' },
            { id: 'splumb-2', label: 'Rough in' },
            { id: 'splumb-3', label: 'Top out' },
            { id: 'splumb-4', label: 'Trim' },
          ],
          invites: [],
          awardedInviteId: null,
          selfPerform: { ref: 'J 1071', value: 26000, note: 'Our own crew. The job runs on the Pipeline.', pctDone: 100 },
          sow: null,
          bidTab: null,
        },
      ],
      stage: 'building',
      owner: 'Hollis Family Pharmacy',
      town: 'San Antonio',
      customerId: 'hollis',
      address: '20811 Stone Oak Pkwy, Suite 104, San Antonio',
      architect: 'Mesquite Design Studio',
      ownerBilling: {
        billed: 182413,
        paid: 164171.7,
        retainageHeld: 18241.3,
        payApps: [
          {
            number: 1,
            periodTo: '2026-07-25',
            sentOn: '2026-07-25',
            doneToDate: { sdry: 21000, selec: 14000, shvac: 0, splumb: 10400, gc: 7953.28, contingency: 1600.6, fee: 5495.39 },
            workToDate: 60449.27,
            retainagePct: 10,
            retainage: 6044.93,
            due: 54404.34,
            paidOn: '2026-08-14',
          },
          {
            number: 2,
            periodTo: '2026-08-25',
            sentOn: '2026-08-25',
            doneToDate: { sdry: 21000, selec: 14000, shvac: 25000, splumb: 18200, gc: 13699.27, contingency: 2756.98, fee: 9465.62 },
            workToDate: 104121.87,
            retainagePct: 10,
            retainage: 10412.19,
            due: 39305.34,
            paidOn: '2026-09-15',
          },
          {
            number: 3,
            periodTo: '2026-09-25',
            sentOn: '2026-09-25',
            doneToDate: { sdry: 42000, selec: 38000, shvac: 31000, splumb: 26000, gc: 24000, contingency: 4830, fee: 16583 },
            workToDate: 182413,
            retainagePct: 10,
            retainage: 18241.3,
            due: 70462.02,
            paidOn: '2026-10-01',
          },
        ],
      },
      ourBidSentOn: '2026-05-14',
      bidDue: null,
      planSets: [{ rev: 0, touches: [], label: 'Permit set', issuedOn: '2026-05-01' }],
      generalConditions: 24000,
      contingencyPct: 3,
      feePct: 10,
      team: [
        { role: 'superintendent', name: 'Marcy Pruett', phone: '(210) 555-0152' },
        {
          role: 'projectManager',
          name: 'Dana Whitaker',
          phone: '(210) 555-0131',
          email: 'dana@clickconstruction.example',
        },
      ],
      ownerContractWorth: { sdry: 42000, selec: 38000, shvac: 31000, splumb: 26000, gc: 24000, contingency: 4830, fee: 16583 },
      ownerContractSignedOn: '2026-05-29',
      permitOn: '2026-06-05',
      startDate: '2026-06-15',
      architectId: 'mesquite',
      questions: [],
      sizeNote: '2,400 sq ft pharmacy finish out',
    },
  ],
  partners: [
    {
      id: 'lonestar',
      company: 'Lonestar Earthworks',
      coiExpires: '2027-03-01',
      contact: 'Dale Whitfield',
      trades: ['Sitework'],
      msa: 'signed',
      msaSignedOn: '2026-06-12',
      w9: true,
      invited: 6,
      bids: 5,
      promisesMade: 3,
      promisesKept: 2,
      base: 'San Antonio',
      maxMiles: 75,
      won: 2,
    },
    {
      id: 'tricounty',
      company: 'Tri-County Site',
      coiExpires: '2027-01-15',
      contact: 'Marisol Vega',
      trades: ['Sitework'],
      msa: 'signed',
      msaSignedOn: '2026-06-12',
      w9: true,
      invited: 4,
      bids: 4,
      promisesMade: 0,
      promisesKept: 0,
      base: 'New Braunfels',
      maxMiles: 100,
      won: 1,
    },
    {
      id: 'hillside',
      company: 'Hillside Excavation',
      coiExpires: null,
      contact: 'Greg Paulk',
      trades: ['Sitework'],
      msa: 'none',
      msaSignedOn: null,
      w9: false,
      invited: 2,
      bids: 0,
      promisesMade: 2,
      promisesKept: 0,
      base: 'Kerrville',
      maxMiles: 50,
      won: 0,
    },
    {
      id: 'alamo',
      company: 'Alamo Concrete',
      coiExpires: '2026-12-20',
      contact: 'Hector Luna',
      trades: ['Concrete'],
      msa: 'signed',
      msaSignedOn: '2026-06-12',
      w9: true,
      invited: 7,
      bids: 6,
      promisesMade: 0,
      promisesKept: 0,
      base: 'San Antonio',
      maxMiles: 100,
      won: 3,
    },
    {
      id: 'guadalupe',
      company: 'Guadalupe Flatwork',
      coiExpires: '2027-02-10',
      contact: 'Ines Barrera',
      trades: ['Concrete'],
      msa: 'signed',
      msaSignedOn: '2026-06-12',
      w9: true,
      invited: 3,
      bids: 3,
      promisesMade: 0,
      promisesKept: 0,
      base: 'Seguin',
      maxMiles: 75,
      won: 0,
    },
    {
      id: 'bexar',
      company: 'Bexar Steel Erectors',
      coiExpires: '2027-04-30',
      contact: 'Tom Riddle',
      trades: ['Structural steel'],
      msa: 'signed',
      msaSignedOn: '2026-06-12',
      w9: true,
      invited: 3,
      bids: 1,
      promisesMade: 2,
      promisesKept: 1,
      base: 'San Antonio',
      maxMiles: 150,
      won: 1,
    },
    {
      id: 'comal',
      company: 'Comal Iron',
      coiExpires: null,
      contact: 'Ray Odom',
      trades: ['Structural steel'],
      msa: 'none',
      msaSignedOn: null,
      w9: true,
      invited: 2,
      bids: 0,
      promisesMade: 0,
      promisesKept: 0,
      base: 'New Braunfels',
      maxMiles: 50,
      won: 0,
    },
    {
      id: 'ironhorse',
      company: 'Iron Horse Fabrication',
      coiExpires: '2027-05-05',
      contact: 'Luz Carrasco',
      trades: ['Structural steel'],
      msa: 'signed',
      msaSignedOn: '2026-06-12',
      w9: true,
      invited: 1,
      bids: 1,
      promisesMade: 0,
      promisesKept: 0,
      base: 'Austin',
      maxMiles: 150,
      won: 0,
    },
    {
      id: 'summit',
      company: 'Summit Roofing',
      coiExpires: '2027-06-01',
      contact: 'Carla Nguyen',
      trades: ['Roofing'],
      msa: 'signed',
      msaSignedOn: '2026-06-12',
      w9: true,
      invited: 5,
      bids: 5,
      promisesMade: 2,
      promisesKept: 2,
      base: 'San Antonio',
      maxMiles: 100,
      won: 2,
    },
    {
      id: 'bluebonnet',
      company: 'Bluebonnet Roofing',
      coiExpires: '2026-11-30',
      contact: 'Wes Hartley',
      trades: ['Roofing'],
      msa: 'sent',
      msaSignedOn: null,
      w9: true,
      invited: 2,
      bids: 1,
      promisesMade: 2,
      promisesKept: 1,
      msaSentOn: '2026-09-30',
      base: 'Austin',
      maxMiles: 75,
      won: 0,
    },
    {
      id: 'coolbreeze',
      company: 'Cool Breeze Mechanical',
      coiExpires: '2027-01-31',
      contact: 'Andre Wallace',
      trades: ['HVAC'],
      msa: 'signed',
      msaSignedOn: '2026-06-12',
      w9: true,
      invited: 5,
      bids: 4,
      promisesMade: 3,
      promisesKept: 3,
      base: 'San Antonio',
      maxMiles: 100,
      won: 1,
    },
    {
      id: 'kendall',
      company: 'Kendall Air',
      coiExpires: '2027-02-28',
      contact: 'Josie Tran',
      trades: ['HVAC'],
      msa: 'sent',
      msaSignedOn: null,
      w9: true,
      invited: 4,
      bids: 4,
      promisesMade: 3,
      promisesKept: 3,
      msaSentOn: '2026-09-29',
      base: 'Boerne',
      maxMiles: 75,
      won: 1,
    },
    {
      id: 'voltage',
      company: 'Voltage Brothers',
      coiExpires: '2026-09-15',
      contact: 'Sam Okafor',
      trades: ['Electrical'],
      msa: 'signed',
      msaSignedOn: '2026-06-12',
      w9: true,
      invited: 8,
      bids: 7,
      promisesMade: 5,
      promisesKept: 4,
      base: 'San Antonio',
      maxMiles: 120,
      won: 2,
    },
    {
      id: 'brightline',
      company: 'Brightline Electric',
      coiExpires: '2027-03-20',
      contact: 'Nora Castillo',
      trades: ['Electrical'],
      msa: 'signed',
      msaSignedOn: '2026-06-12',
      w9: true,
      invited: 6,
      bids: 6,
      promisesMade: 4,
      promisesKept: 4,
      base: 'San Marcos',
      maxMiles: 100,
      won: 3,
    },
    {
      id: 'tejas',
      company: 'Tejas Power',
      coiExpires: null,
      contact: 'Bill Sorrell',
      trades: ['Electrical'],
      msa: 'none',
      msaSignedOn: null,
      w9: false,
      invited: 1,
      bids: 0,
      promisesMade: 1,
      promisesKept: 0,
      base: 'Laredo',
      maxMiles: 200,
      won: 0,
    },
    {
      id: 'redline',
      company: 'Redline Fire Protection',
      coiExpires: '2027-02-01',
      contact: 'Mina Shah',
      trades: ['Fire sprinkler'],
      msa: 'signed',
      msaSignedOn: '2026-06-12',
      w9: true,
      invited: 3,
      bids: 3,
      promisesMade: 0,
      promisesKept: 0,
      base: 'San Antonio',
      maxMiles: 100,
      won: 2,
    },
    {
      id: 'aquashield',
      company: 'AquaShield Sprinkler',
      coiExpires: null,
      contact: 'Pete Doyle',
      trades: ['Fire sprinkler'],
      msa: 'none',
      msaSignedOn: null,
      w9: false,
      invited: 0,
      bids: 0,
      promisesMade: 0,
      promisesKept: 0,
      base: 'Waco',
      maxMiles: 100,
      won: 0,
    },
    {
      id: 'hillcountry',
      company: 'Hill Country Interiors',
      coiExpires: '2027-04-12',
      contact: 'Rosa Medina',
      trades: ['Framing and drywall'],
      msa: 'signed',
      msaSignedOn: '2026-06-12',
      w9: true,
      invited: 4,
      bids: 4,
      promisesMade: 0,
      promisesKept: 0,
      base: 'Boerne',
      maxMiles: 60,
      won: 3,
    },
    {
      id: 'cedar',
      company: 'Cedar & Pine Millwork',
      coiExpires: '2027-01-08',
      contact: 'Owen Blake',
      trades: ['Millwork'],
      msa: 'none',
      msaSignedOn: null,
      w9: true,
      invited: 2,
      bids: 2,
      promisesMade: 0,
      promisesKept: 0,
      base: 'Fredericksburg',
      maxMiles: 80,
      won: 0,
    },
    {
      id: 'sawtooth',
      company: 'Sawtooth Cabinet Co',
      coiExpires: '2027-03-03',
      contact: 'Jill Arnett',
      trades: ['Millwork'],
      msa: 'signed',
      msaSignedOn: '2026-06-12',
      w9: true,
      invited: 2,
      bids: 2,
      promisesMade: 0,
      promisesKept: 0,
      base: 'San Antonio',
      maxMiles: 100,
      won: 1,
    },
    {
      id: 'pecanvalley',
      company: 'Pecan Valley Electric',
      coiExpires: '2026-09-15',
      contact: 'Marcus Bell',
      trades: ['Electrical'],
      msa: 'signed',
      msaSignedOn: '2026-06-12',
      w9: true,
      invited: 3,
      bids: 3,
      promisesMade: 0,
      promisesKept: 0,
      base: null,
      maxMiles: null,
      people: [
        {
          id: 'pecanvalley-p-1',
          name: 'Dana Whitfield',
          email: 'dana@pecanvalleyelectric.example',
          role: 'Bookkeeper',
          gets: ['pay'],
        },
      ],
      contactGets: ['quotes', 'job', 'contracts'],
      won: 1,
    },
    {
      id: 'liveoak',
      company: 'Live Oak Drywall',
      coiExpires: '2027-05-01',
      contact: 'Darnell Pruitt',
      trades: ['Framing and drywall'],
      msa: 'signed',
      msaSignedOn: '2026-06-12',
      w9: true,
      invited: 3,
      bids: 3,
      promisesMade: 0,
      promisesKept: 0,
      base: 'San Antonio',
      maxMiles: 60,
      won: 1,
    },
    {
      id: 'westside',
      company: 'Westside Electric',
      coiExpires: '2027-04-15',
      contact: 'Ana Flores',
      trades: ['Electrical'],
      msa: 'signed',
      msaSignedOn: '2026-06-12',
      w9: true,
      invited: 3,
      bids: 3,
      promisesMade: 0,
      promisesKept: 0,
      base: 'San Antonio',
      maxMiles: 80,
      won: 1,
    },
  ],
}

/** A fresh copy each call, like the prototype's `initialGcState`, so a test may change what it gets. */
export function initialGcState(): GcState {
  return structuredClone(DATA)
}
