// GENERATED by scripts/edge-kernels.mjs from src/lib/gc/schedule/schedule.ts. Do not edit: change the file in src and run
// `npm run gen:edge-kernels`. Imported by gc-trade-portal (the schedule's PR 14b).
/**
 * GC mode, the real build, the schedule's PR 1a: the schedule and its measures, moved word for word
 * from the GC mode prototype (branch spike/gc-mode, `gcBuildingSchedule.ts`), where the owner decided
 * each rule by using it. The items with their trade, worth and percent, the plan to date, what a move
 * pushes, the projected finish, work against the plan, the dates to meet, the look-ahead and its
 * reliability, the summary, and the first draft's entry. No database and no screen reads it yet; the
 * Schedule tab on real data does (PR 7 of to-dos/gc-mode/SCHEDULE_REAL_BUILD.md, on branch spike/gc-mode).
 */
import { addDays } from '../building.ts'
import { partnerById } from '../lookups.ts'
import { contractDaysAdded } from '../ownerBilling.ts'
import { scheduleDraft } from './draft.ts'
import { dayNumber, daysBetween, isoOf, lagOf, lineOf, scheduleFloat, waitOrder } from './network.ts'
import type { InspectionFailure, LookAheadMark, LookAheadReason, ProjectSchedule, ScheduleActivity, ScheduleMilestone, TemplateLine } from '../../../../../../../src/lib/gc/schedule/types'
import type { GcProject, GcState, TradePackage } from '../../../../../../../src/lib/gc/types'
import { shortDate, weekdayDate } from '../words.ts'

// The days, the links, the spare days and the pushes live in `network.ts` (G-130); their readers keep importing them from here.
export { daysBetween, lagOf, pushAfter, pushedAfterWords, scheduleFloat, wouldLoop } from './network.ts'
export type { PushedAfter } from './network.ts'

/** How many weeks the look-ahead shows (owner, 2026-10-02: three). */
export const LOOKAHEAD_WEEKS = 3

/** A milestone counts as hit up to this many days after its planned day (owner: "a few days"; 3 is the default). */
export const MILESTONE_GRACE_DAYS = 3

/** How many past weeks the look-ahead's reliability is read over. My default. */
export const RELIABILITY_WEEKS = 4

/** The Monday of the week `iso` falls in. */
export function mondayOf(iso: string): string {
  const dow = new Date(dayNumber(iso) * 86_400_000).getUTCDay()
  return addDays(iso, -((dow + 6) % 7))
}

/** How much of an activity a plan has done by `on`, straight across its days: 0 before, 100 after. */
export function plannedPct(start: string, finish: string, on: string): number {
  const days = daysBetween(start, finish) + 1
  const done = daysBetween(start, on) + 1
  if (done <= 0) return 0
  if (done >= days) return 100
  return (done / days) * 100
}

/** Who an inspection belongs to, in the chart's words: the city inspects, not a trade. */
export const INSPECTION_TRADE = 'Inspections'

export const INSPECTION_COMPANY = 'The city'

/** Any activity on the chart: a trade's line (a ScheduleRow) or an inspection. */
export interface ScheduleItem {
  activity: ScheduleActivity
  /** The trade it belongs to. Null: an inspection, the job's own. */
  pkg: TradePackage | null
  trade: string
  label: string
  /** The company doing it, or "Our own crew". */
  company: string
  /** What the line is worth, in dollars. */
  worth: number
  /** Percent done: what the trade reported, or what we see on a line we sent back. */
  actual: number
  /** The plan the baseline locked at Start. The current plan when nothing is locked yet. */
  baseline: { start: string; finish: string }
  /** Percent the baseline planned by today. */
  plannedToday: number
  /** Days the current finish moved past the baseline's. */
  slipDays: number
}

/** A trade's line on the schedule: what work done against the plan, the look-ahead and the portal read. */
export interface ScheduleRow extends ScheduleItem {
  pkg: TradePackage
}

/** An activity in a sentence: "Plumbing · Trim", or an inspection by its own name. */
export function activityName(item: ScheduleItem): string {
  return item.activity.inspection ? item.label : `${item.trade} · ${item.label}`
}

/** The lines a trade's activities are drawn from: its schedule of values, or its scope before one. */
export function scheduleLinesOf(pkg: TradePackage): { lineId: string; label: string }[] {
  if (pkg.sow && !pkg.selfPerform) return pkg.sow.sov.map((l) => ({ lineId: l.id, label: l.label }))
  return pkg.scope.map((l) => ({ lineId: l.id, label: l.label }))
}

/**
 * The first draft to draw from: the New Project lane's draft from the stages of the job
 * (`scheduleDraft` in gcNewProject.ts: the rough-ins side by side after framing, close-in after
 * the inspection, the trims after the finishes). The Draw a first draft button calls this, with a
 * template's lines when it starts from one (G-44).
 */
export function draftSchedule(project: GcProject, start: string, stageDays?: Partial<Record<string, number>>, like?: TemplateLine[]): ProjectSchedule {
  return scheduleDraft(project, start, stageDays, like)
}

/**
 * The plan at Start, kept as the baseline (owner: Start locks it). The Board lane's Start does not
 * touch the schedule, so the first change after Start keeps the plan as it stood: until a change,
 * the plan is the plan at Start.
 */
export function withBaselineKept(project: GcProject, schedule: ProjectSchedule): ProjectSchedule {
  if (!project.startedOn || schedule.baseline) return schedule
  return {
    ...schedule,
    baseline: { lockedOn: project.startedOn, activities: Object.fromEntries(schedule.activities.map((a) => [a.lineId, { start: a.start, finish: a.finish }])) },
  }
}

function companyOf(state: GcState, pkg: TradePackage): string {
  if (pkg.selfPerform) return 'Our own crew'
  const invite = pkg.invites.find((i) => i.id === pkg.awardedInviteId)
  return (invite ? partnerById(state, invite.partnerId)?.company : undefined) ?? pkg.trade
}

function rowOf(state: GcState, project: GcProject, schedule: ProjectSchedule, activity: ScheduleActivity): ScheduleRow | null {
  const pkg = project.packages.find((k) => k.id === activity.packageId)
  const line = pkg ? lineOf(pkg, activity.lineId) : null
  if (!pkg || !line) return null
  const baseline = schedule.baseline?.activities[activity.lineId] ?? { start: activity.start, finish: activity.finish }
  return {
    activity,
    pkg,
    trade: pkg.trade,
    label: line.label,
    company: companyOf(state, pkg),
    worth: line.worth,
    actual: line.actual,
    baseline,
    plannedToday: plannedPct(baseline.start, baseline.finish, state.today),
    slipDays: daysBetween(baseline.finish, activity.finish),
  }
}

/** An inspection as a chart row: no dollars, done once it passed. Null: not an inspection. */
function inspectionOf(schedule: ProjectSchedule, activity: ScheduleActivity, today: string): ScheduleItem | null {
  const inspection = activity.inspection
  if (!inspection) return null
  const baseline = schedule.baseline?.activities[activity.lineId] ?? { start: activity.start, finish: activity.finish }
  return {
    activity,
    pkg: null,
    trade: INSPECTION_TRADE,
    label: inspection.label,
    company: INSPECTION_COMPANY,
    worth: 0,
    actual: inspection.passedOn ? 100 : 0,
    baseline,
    plannedToday: plannedPct(baseline.start, baseline.finish, today),
    slipDays: daysBetween(baseline.finish, activity.finish),
  }
}

/** Every trade's activity on the schedule with its trade, worth, percent done and what the baseline planned by today. */
export function scheduleRows(state: GcState, project: GcProject): ScheduleRow[] {
  const schedule = project.schedule
  if (!schedule) return []
  return schedule.activities.flatMap((activity) => {
    const row = rowOf(state, project, schedule, activity)
    return row ? [row] : []
  })
}

/** An added activity as a chart row (G-38): no dollars, done when the office marks it. Null: not one. */
function addedOf(schedule: ProjectSchedule, activity: ScheduleActivity, today: string): ScheduleItem | null {
  const added = activity.added
  if (!added) return null
  const baseline = schedule.baseline?.activities[activity.lineId] ?? { start: activity.start, finish: activity.finish }
  return {
    activity,
    pkg: null,
    trade: ADDED_TRADE,
    label: added.label,
    company: added.who,
    worth: 0,
    actual: added.doneOn ? 100 : 0,
    baseline,
    plannedToday: plannedPct(baseline.start, baseline.finish, today),
    slipDays: daysBetween(baseline.finish, activity.finish),
  }
}

/** The trade an added activity shows under: the job's own, like an inspection. */
export const ADDED_TRADE = "The job's own"

/** Every activity on the chart, in the order drawn: the trades' lines, the inspections and the added ones. */
export function scheduleItems(state: GcState, project: GcProject): ScheduleItem[] {
  const schedule = project.schedule
  if (!schedule) return []
  return schedule.activities.flatMap((activity) => {
    const item = activity.inspection ? inspectionOf(schedule, activity, state.today) : activity.added ? addedOf(schedule, activity, state.today) : rowOf(state, project, schedule, activity)
    return item ? [item] : []
  })
}

export interface OpenFailure {
  activity: ScheduleActivity
  label: string
  /** The last time it failed. */
  failure: InspectionFailure
  /** How many times it has failed. */
  times: number
}

/**
 * Inspections that failed and have not passed since (owner, 2026-10-03), with the last failure.
 * With a trade: only those whose last failure names its work.
 */
export function openInspectionFailures(project: GcProject, packageId?: string): OpenFailure[] {
  return (project.schedule?.activities ?? []).flatMap((activity) => {
    const inspection = activity.inspection
    const failed = inspection?.failed ?? []
    const failure = failed[failed.length - 1]
    if (!inspection || inspection.passedOn || !failure) return []
    if (packageId && !failure.packageIds.includes(packageId)) return []
    return [{ activity, label: inspection.label, failure, times: failed.length }]
  })
}

/** The trades an inspection waits on, the ones whose work it inspects: the first to name when it fails. */
export function inspectedTrades(project: GcProject, activity: ScheduleActivity): TradePackage[] {
  const ids = new Set((project.schedule?.activities ?? []).filter((a) => activity.after.includes(a.lineId)).map((a) => a.packageId))
  return project.packages.filter((k) => ids.has(k.id))
}

/** The inspections on the schedule, in the order drawn. */
export function inspectionItems(project: GcProject, today: string): ScheduleItem[] {
  const schedule = project.schedule
  if (!schedule) return []
  return schedule.activities.flatMap((activity) => {
    const item = inspectionOf(schedule, activity, today)
    return item ? [item] : []
  })
}

/**
 * Work done against the plan, weighted by dollars the way the Building ring weighs work. Days
 * behind: how long ago the baseline planned to have this much done (negative: ahead).
 */
export function workVsPlan(rows: ScheduleRow[], today: string): { donePct: number; plannedPct: number; daysBehind: number } {
  const total = rows.reduce((s, r) => s + r.worth, 0)
  if (total === 0) return { donePct: 0, plannedPct: 0, daysBehind: 0 }
  const done = rows.reduce((s, r) => s + (r.worth * r.actual) / 100, 0)
  const plannedOn = (on: string) => rows.reduce((s, r) => s + (r.worth * plannedPct(r.baseline.start, r.baseline.finish, on)) / 100, 0)
  const first = rows.reduce((m, r) => (r.baseline.start < m ? r.baseline.start : m), rows[0]?.baseline.start ?? today)
  const last = rows.reduce((m, r) => (r.baseline.finish > m ? r.baseline.finish : m), rows[0]?.baseline.finish ?? today)
  // The first day the baseline had this much done. Done is never above everything, so one is found.
  let when = last
  for (let on = first; on <= last; on = addDays(on, 1)) {
    if (plannedOn(on) >= done - 0.5) {
      when = on
      break
    }
  }
  return { donePct: (done / total) * 100, plannedPct: (plannedOn(today) / total) * 100, daysBehind: daysBetween(when, today) }
}

/** When the job will finish as the schedule stands today, and why. */
export interface ProjectedFinish {
  on: string
  /** Days past the baseline's last finish. 0: on the plan locked at Start, or ahead of it. */
  behind: number
  /** What set it: the current plan with the work not done moved to today, or the pace of the work. */
  from: 'plan' | 'pace'
  /** The reason in a sentence or two. */
  why: string
}

/**
 * The day the job will finish as the schedule stands today (for the Owner Billing lane's
 * late-finish warning, 2026-10-04). Two readings, and the later one wins:
 * - plan: the current plan, worked through what waits on what, where nothing unfinished finishes
 *   before today. Work whose start has come needs the rest of its days from today.
 * - pace: the baseline's last finish moved by how far the work runs behind it (`workVsPlan`).
 * Null: no schedule drawn. `more`: days added to some activities' work left, by line (G-57's weather
 * and crews), through the same walk so what waits on them moves too. The measure's own line has none.
 */
export function projectedFinish(project: GcProject, today: string, more?: Map<string, number>): ProjectedFinish | null {
  const schedule = project.schedule
  if (!schedule || schedule.activities.length === 0) return null
  const t = dayNumber(today)
  const info = (a: ScheduleActivity): { name: string; done: number; worth: number; actual: number } => {
    if (a.inspection) return { name: `The ${a.inspection.label.toLowerCase()}`, done: a.inspection.passedOn ? 100 : 0, worth: 0, actual: 0 }
    if (a.added) return { name: a.added.label, done: a.added.doneOn ? 100 : 0, worth: 0, actual: 0 }
    const pkg = project.packages.find((k) => k.id === a.packageId)
    const line = pkg ? lineOf(pkg, a.lineId) : null
    return { name: pkg && line ? `${pkg.trade} · ${line.label}` : a.lineId, done: line?.actual ?? 0, worth: line?.worth ?? 0, actual: line?.actual ?? 0 }
  }
  const finish = new Map<string, number>()
  // For each activity: what set its start (the activity it waits on that finishes last, when that
  // is later than its own planned start), and whether today set its finish (work not done in time).
  const setBy = new Map<string, string>()
  const lateNow = new Set<string>()
  const byId = new Map(schedule.activities.map((a) => [a.lineId, a]))
  for (const a of waitOrder(schedule.activities)) {
    const { done } = info(a)
    const days = daysBetween(a.start, a.finish) + 1
    if (done >= 100) {
      finish.set(a.lineId, Math.min(dayNumber(a.finish), t))
      continue
    }
    let start = dayNumber(a.start)
    for (const id of a.after) {
      const f = finish.get(id)
      if (f !== undefined && f + 1 + lagOf(a, id) > start) {
        start = f + 1 + lagOf(a, id)
        setBy.set(a.lineId, id)
      }
    }
    const extra = more?.get(a.lineId) ?? 0
    const left = Math.max(1, Math.ceil((days * (100 - done)) / 100)) + extra
    const end = start >= t ? start + days + extra - 1 : Math.max(start + days - 1, t + left - 1)
    if (end > start + days - 1) lateNow.add(a.lineId)
    finish.set(a.lineId, end)
  }
  const planEnd = Math.max(...finish.values())
  const drawnEnd = Math.max(...schedule.activities.map((a) => dayNumber(a.finish)))
  const baselineEnd = Math.max(...schedule.activities.map((a) => dayNumber(schedule.baseline?.activities[a.lineId]?.finish ?? a.finish)))
  const rows = schedule.activities.flatMap((activity): ScheduleRow[] => {
    if (activity.inspection) return []
    const pkg = project.packages.find((k) => k.id === activity.packageId)
    const line = pkg ? lineOf(pkg, activity.lineId) : null
    if (!pkg || !line) return []
    const baseline = schedule.baseline?.activities[activity.lineId] ?? { start: activity.start, finish: activity.finish }
    return [{ activity, pkg, trade: pkg.trade, label: line.label, company: '', worth: line.worth, actual: line.actual, baseline, plannedToday: plannedPct(baseline.start, baseline.finish, today), slipDays: daysBetween(baseline.finish, activity.finish) }]
  })
  const late = Math.max(0, workVsPlan(rows, today).daysBehind)
  const paceEnd = baselineEnd + late
  const fromPace = paceEnd > planEnd
  const end = fromPace ? paceEnd : planEnd
  const on = isoOf(end)
  const n = (d: number) => `${d} ${d === 1 ? 'day' : 'days'}`
  let why: string
  if (fromPace) {
    why = `The work runs ${n(late)} behind the plan. At that pace it finishes ${weekdayDate(on)}.`
  } else if (planEnd > drawnEnd) {
    // Walk back from the last finish through what set each start, to what moves it: work late by
    // today, or work planned to run past what waits on it.
    const last = schedule.activities.find((a) => finish.get(a.lineId) === planEnd)
    let cause = last
    while (cause && !lateNow.has(cause.lineId) && setBy.has(cause.lineId)) cause = byId.get(setBy.get(cause.lineId) ?? '')
    if (cause) {
      const d = info(cause)
      const state = d.done > 0 ? `is ${Math.round(d.done)}% done` : cause.inspection ? 'is not passed yet' : 'has not started'
      why = lateNow.has(cause.lineId)
        ? `${d.name} ${state}. It was planned to finish ${weekdayDate(cause.finish)}.`
        : `${d.name} is planned to finish ${weekdayDate(cause.finish)}.`
      why += cause === last ? ` So the job finishes ${weekdayDate(on)}.` : ` What comes after it moves the finish to ${weekdayDate(on)}.`
    } else {
      why = `The plan finishes ${weekdayDate(on)}.`
    }
  } else if (end > baselineEnd) {
    // The plan itself moved since Start: walk back from the last finish through what it starts
    // right after, to where the slip begins.
    const slip = (a: ScheduleActivity) => daysBetween(schedule.baseline?.activities[a.lineId]?.finish ?? a.finish, a.finish)
    let cause = schedule.activities.find((a) => dayNumber(a.finish) === drawnEnd)
    for (let guard = 0; cause && guard < schedule.activities.length; guard++) {
      const here: ScheduleActivity = cause
      const before = here.after.map((id) => byId.get(id)).find((b) => b && dayNumber(b.finish) + 1 === dayNumber(here.start) && slip(b) >= slip(here))
      if (!before) break
      cause = before
    }
    const was = cause ? schedule.baseline?.activities[cause.lineId]?.finish : undefined
    why =
      cause && was && cause.finish > was
        ? `${info(cause).name} now finishes ${weekdayDate(cause.finish)}. The plan at Start had ${weekdayDate(was)}.${dayNumber(cause.finish) === drawnEnd ? '' : ` What comes after it moves the finish to ${weekdayDate(on)}.`}`
        : `The plan finishes ${weekdayDate(on)}. That is ${n(end - baselineEnd)} past the plan at Start.`
  } else {
    why = `The plan finishes ${weekdayDate(on)}.`
  }
  return { on, behind: Math.max(0, end - baselineEnd), from: fromPace ? 'pace' : 'plan', why }
}

export type MilestoneState = 'hit' | 'missed' | 'late' | 'due'

export interface MilestoneRow {
  milestone: ScheduleMilestone
  state: MilestoneState
  /** The company it belongs to, through its trade. Null: the job's own. */
  company: string | null
  /** Days past the day it is due: when met, or by today when not. */
  daysLate: number
  /** The day it is due: its planned day, moved by signed change orders' days when it is substantial completion. */
  due: string
  /** Days signed change orders added to it. 0: none. */
  addedDays: number
}

/** The milestone the contract's end is: Substantial completion, by its name. */
export function isSubstantial(m: ScheduleMilestone): boolean {
  return /substantial completion/i.test(m.label)
}

/**
 * Substantial completion as the contract has it now (owner, 2026-10-04, question 28): the
 * milestone's planned day, pushed back by the days the signed change orders add
 * (`contractDaysAdded`, the Owner Billing lane's). Worked out, never written: the signed change
 * orders are the one source. Null: no schedule, or no Substantial completion milestone.
 */
export function substantialCompletionOn(project: GcProject): { planned: string; days: number; on: string } | null {
  const m = project.schedule?.milestones.find(isSubstantial)
  if (!m) return null
  const days = contractDaysAdded(project)
  return { planned: m.planned, days, on: days > 0 ? addDays(m.planned, days) : m.planned }
}

/** The day a milestone is due: substantial completion moves with signed change orders' days. */
function dueOf(project: GcProject, m: ScheduleMilestone): { due: string; addedDays: number } {
  if (!isSubstantial(m)) return { due: m.planned, addedDays: 0 }
  const days = contractDaysAdded(project)
  return { due: days > 0 ? addDays(m.planned, days) : m.planned, addedDays: days }
}

/**
 * Each milestone: hit when met within the grace days, missed when met later, late when the grace
 * passed and it is not met, due otherwise.
 */
export function milestoneRows(state: GcState, project: GcProject): MilestoneRow[] {
  return (project.schedule?.milestones ?? []).map((milestone) => {
    const pkg = milestone.packageId ? project.packages.find((k) => k.id === milestone.packageId) : undefined
    const company = pkg ? companyOf(state, pkg) : null
    const { due, addedDays } = dueOf(project, milestone)
    const daysLate = daysBetween(due, milestone.metOn ?? state.today)
    const stateOf: MilestoneState = milestone.metOn
      ? daysLate <= MILESTONE_GRACE_DAYS
        ? 'hit'
        : 'missed'
      : daysLate > MILESTONE_GRACE_DAYS
        ? 'late'
        : 'due'
    return { milestone, state: stateOf, company, daysLate, due, addedDays }
  })
}

/** Hit out of every milestone already decided (hit, missed, or late with the grace passed). */
export function milestoneHitRate(rows: MilestoneRow[]): { hit: number; of: number } {
  const decided = rows.filter((r) => r.state !== 'due')
  return { hit: decided.filter((r) => r.state === 'hit').length, of: decided.length }
}

export type LookAheadState = 'done' | 'not' | 'waiting' | 'unmarked'

/** A look-ahead mark as it counts: the superintendent's mark once verified, else waiting. */
export function markState(mark: LookAheadMark | null): LookAheadState {
  if (!mark) return 'unmarked'
  if (!mark.verifiedOn) return 'waiting'
  return (mark.verifiedDone ?? mark.done) ? 'done' : 'not'
}

export interface LookAheadWeek {
  weekOf: string
  items: { row: ScheduleRow; mark: LookAheadMark | null; state: LookAheadState }[]
  /** The inspections planned that week. Nobody marks them: they pass, or not yet. */
  inspections: ScheduleItem[]
}

/**
 * The look-ahead: this week and the next two (LOOKAHEAD_WEEKS), each listing the activities the
 * current plan has running that week and not finished, with the week's mark when there is one.
 */
export function lookAheadWeeks(project: GcProject, rows: ScheduleRow[], today: string): LookAheadWeek[] {
  const marks = project.schedule?.lookAhead ?? []
  const first = mondayOf(today)
  return Array.from({ length: LOOKAHEAD_WEEKS }, (_, i) => {
    const weekOf = addDays(first, i * 7)
    const weekEnd = addDays(weekOf, 6)
    const items = rows
      .filter((r) => {
        const mark = marks.find((m) => m.weekOf === weekOf && m.lineId === r.activity.lineId)
        const running = r.activity.start <= weekEnd && r.activity.finish >= weekOf
        return mark !== undefined || (running && r.actual < 100)
      })
      .map((row) => {
        const mark = marks.find((m) => m.weekOf === weekOf && m.lineId === row.activity.lineId) ?? null
        return { row, mark, state: markState(mark) }
      })
    const inspections = inspectionItems(project, today).filter((i) => i.activity.start <= weekEnd && i.activity.finish >= weekOf)
    return { weekOf, items, inspections }
  })
}

/** Why not, as it counts: the superintendent's reason when they corrected the mark, else the trade's. */
export function markReason(mark: LookAheadMark): LookAheadReason | null {
  return mark.verifiedReason ?? mark.reason ?? null
}

export interface VerifyItem {
  mark: LookAheadMark
  row: ScheduleRow
}

/**
 * The superintendent's verify list (owner, 2026-10-02): every trade mark not verified yet, oldest
 * week first, with its activity. And our own crew's activities in this week's look-ahead with no
 * mark yet: we mark those ourselves, and our mark counts as verified. And each inspection planned
 * to start by this week's end that has not passed: our superintendent records the pass.
 */
export function verifyList(
  project: GcProject,
  rows: ScheduleRow[],
  today: string,
): { waiting: VerifyItem[]; ourCrew: ScheduleRow[]; inspections: ScheduleItem[] } {
  const marks = project.schedule?.lookAhead ?? []
  const byLine = new Map(rows.map((r) => [r.activity.lineId, r]))
  const waiting = marks
    .filter((m) => !m.verifiedOn)
    .flatMap((mark) => {
      const row = byLine.get(mark.lineId)
      return row ? [{ mark, row }] : []
    })
    .sort((a, b) => (a.mark.weekOf < b.mark.weekOf ? -1 : a.mark.weekOf > b.mark.weekOf ? 1 : 0))
  const thisWeek = lookAheadWeeks(project, rows, today)[0]
  const ourCrew = (thisWeek?.items ?? []).filter((i) => i.row.pkg.selfPerform && !i.mark).map((i) => i.row)
  const weekEnd = addDays(mondayOf(today), 6)
  const inspections = inspectionItems(project, today).filter((i) => !i.activity.inspection?.passedOn && i.activity.start <= weekEnd)
  return { waiting, ourCrew, inspections }
}

/**
 * How reliable the look-ahead has been: of the verified marks in the last weeks (RELIABILITY_WEEKS,
 * this week counted once its marks are verified), how many were done as planned. Per company too.
 * Marks not yet verified are counted apart.
 */
export function lookAheadReliability(
  state: GcState,
  project: GcProject,
): { done: number; of: number; waiting: number; byCompany: { company: string; done: number; of: number }[] } {
  const marks = project.schedule?.lookAhead ?? []
  const thisWeek = mondayOf(state.today)
  const from = addDays(thisWeek, -7 * (RELIABILITY_WEEKS - 1))
  const counted = marks.filter((m) => m.weekOf <= thisWeek && m.weekOf >= from && m.verifiedOn)
  const companies = new Map<string, { done: number; of: number }>()
  for (const m of counted) {
    const pkg = project.packages.find((k) => k.id === m.packageId)
    const company = pkg ? companyOf(state, pkg) : m.packageId
    const c = companies.get(company) ?? { done: 0, of: 0 }
    c.of += 1
    if (markState(m) === 'done') c.done += 1
    companies.set(company, c)
  }
  return {
    done: counted.filter((m) => markState(m) === 'done').length,
    of: counted.length,
    waiting: marks.filter((m) => !m.verifiedOn).length,
    byCompany: [...companies].map(([company, c]) => ({ company, ...c })),
  }
}

/** Everything the Schedule tab reads, in one place. */
export function scheduleMeasures(state: GcState, project: GcProject) {
  const rows = scheduleRows(state, project)
  const items = scheduleItems(state, project)
  const float = scheduleFloat(project.schedule?.activities ?? [])
  const milestones = milestoneRows(state, project)
  return {
    /** The trades' lines: work done against the plan, the look-ahead, the verify list. */
    rows,
    /** Every activity, the inspections too: the chart, the editor, the critical path. */
    items,
    float,
    work: workVsPlan(rows, state.today),
    critical: items.filter((r) => float.get(r.activity.lineId) === 0 && r.actual < 100),
    milestones,
    hitRate: milestoneHitRate(milestones),
    lookAhead: lookAheadWeeks(project, rows, state.today),
    reliability: lookAheadReliability(state, project),
    /** When the job finishes as the schedule stands today, against the contract's day. */
    finish: projectedFinish(project, state.today),
    contract: substantialCompletionOn(project),
  }
}

/** A milestone's state on `today`: hit, missed, late, or still due (MILESTONE_GRACE_DAYS of grace). */
function milestoneStateOn(m: ScheduleMilestone, due: string, today: string): { state: MilestoneState; daysLate: number } {
  const daysLate = daysBetween(due, m.metOn ?? today)
  const state: MilestoneState = m.metOn ? (daysLate <= MILESTONE_GRACE_DAYS ? 'hit' : 'missed') : daysLate > MILESTONE_GRACE_DAYS ? 'late' : 'due'
  return { state, daysLate }
}

export interface ScheduleSummary {
  /** Days behind the baseline (negative: ahead). */
  daysBehind: number
  donePct: number
  plannedPct: number
  milestones: { hit: number; of: number; late: { label: string; daysLate: number }[]; next: { label: string; planned: string } | null }
  lookAhead: { done: number; of: number; waiting: number }
}

/**
 * The schedule in a few words, for a won job's board row and the ring's card (owner, 2026-10-03:
 * the row shows the schedule's measures on Building). It reads only the project and today, so
 * the row can draw it. Null: no schedule drawn.
 */
export function scheduleSummary(project: GcProject, today: string): ScheduleSummary | null {
  const schedule = project.schedule
  if (!schedule || schedule.activities.length === 0) return null
  const rows: ScheduleRow[] = schedule.activities.flatMap((activity) => {
    const pkg = project.packages.find((k) => k.id === activity.packageId)
    const line = pkg ? lineOf(pkg, activity.lineId) : null
    if (!pkg || !line) return []
    const baseline = schedule.baseline?.activities[activity.lineId] ?? { start: activity.start, finish: activity.finish }
    return [{ activity, pkg, trade: pkg.trade, label: line.label, company: '', worth: line.worth, actual: line.actual, baseline, plannedToday: plannedPct(baseline.start, baseline.finish, today), slipDays: daysBetween(baseline.finish, activity.finish) }]
  })
  const work = workVsPlan(rows, today)
  const states = schedule.milestones.map((m) => {
    const { due } = dueOf(project, m)
    return { m, due, ...milestoneStateOn(m, due, today) }
  })
  const decided = states.filter((x) => x.state !== 'due')
  const next = states.filter((x) => x.state === 'due').sort((a, b) => (a.due < b.due ? -1 : 1))[0]
  const thisWeek = mondayOf(today)
  const from = addDays(thisWeek, -7 * (RELIABILITY_WEEKS - 1))
  const counted = schedule.lookAhead.filter((m) => m.weekOf <= thisWeek && m.weekOf >= from && m.verifiedOn)
  return {
    daysBehind: work.daysBehind,
    donePct: work.donePct,
    plannedPct: work.plannedPct,
    milestones: {
      hit: decided.filter((x) => x.state === 'hit').length,
      of: decided.length,
      late: states.filter((x) => x.state === 'late' || x.state === 'missed').map((x) => ({ label: x.m.label, daysLate: x.daysLate })),
      next: next ? { label: next.m.label, planned: next.due } : null,
    },
    lookAhead: {
      done: counted.filter((m) => markState(m) === 'done').length,
      of: counted.length,
      waiting: schedule.lookAhead.filter((m) => !m.verifiedOn).length,
    },
  }
}

/** The summary as sentences: the board row's hover and the ring's card. */
export function scheduleSummaryWords(sum: ScheduleSummary): string {
  const d = sum.daysBehind
  const pace = d > 0 ? `${d} ${d === 1 ? 'day' : 'days'} behind the plan` : d < 0 ? `${-d} ${d === -1 ? 'day' : 'days'} ahead of the plan` : 'on plan'
  const parts = [`The schedule: ${pace}, ${Math.round(sum.donePct)}% done where ${Math.round(sum.plannedPct)}% was planned.`]
  for (const l of sum.milestones.late) parts.push(`${l.label} is ${l.daysLate} days late.`)
  if (sum.milestones.next) parts.push(`Next: ${sum.milestones.next.label}, ${shortDate(sum.milestones.next.planned)}.`)
  if (sum.lookAhead.waiting > 0) parts.push(`${sum.lookAhead.waiting} look-ahead ${sum.lookAhead.waiting === 1 ? 'mark waits' : 'marks wait'} on our superintendent.`)
  return parts.join(' ')
}
