// GENERATED by scripts/edge-kernels.mjs from src/lib/gc/schedule/waits.ts. Do not edit: change the file in src and run
// `npm run gen:edge-kernels`. Imported by gc-trade-portal (the schedule's PR 14b).
/**
 * GC mode, the real build, the schedule's PR 1b: what the work waits on from outside the trades (G-73 to G-75), moved word for word from the GC mode prototype
 * (branch spike/gc-mode, `gcScheduleWaits.ts`).
 */
import { partnerById } from '../lookups.ts'
import type { GanttHold } from '../../../../../../../src/lib/gc/schedule/gantt'
import { moveActivityName } from './moves.ts'
import { daysBetween } from './schedule.ts'
import type { ScheduleWait, WaitKind } from '../../../../../../../src/lib/gc/schedule/types'
import type { GcProject, GcState } from '../../../../../../../src/lib/gc/types'
import { shortDate, weekdayDate } from '../words.ts'

/** The four kinds, with the words each one's steps go by. */
export const WAIT_KINDS: { key: WaitKind; label: string; who: string; asked: string; done: string }[] = [
  { key: 'delivery', label: 'A delivery', who: 'the supplier', asked: 'ordered', done: 'on site' },
  { key: 'decision', label: "The customer's decision", who: 'the customer', asked: 'asked', done: 'decided' },
  { key: 'permit', label: 'A permit', who: 'the city', asked: 'applied for', done: 'issued' },
  { key: 'utility', label: "The utility's work", who: 'the utility', asked: 'requested', done: 'done' },
]

export function waitKind(kind: WaitKind): (typeof WAIT_KINDS)[number] {
  return WAIT_KINDS.find((k) => k.key === kind) ?? (WAIT_KINDS[0] as (typeof WAIT_KINDS)[number])
}

export type WaitState = 'notAsked' | 'asked' | 'shipped' | 'done'

export interface WaitRow {
  wait: ScheduleWait
  state: WaitState
  /** "not ordered yet", "ordered Sep 12", "shipped Sep 30", "on site Oct 2". */
  stateWords: string
  tone: 'green' | 'red' | 'amber' | 'grey'
  /** The trade's name, or "the job's own". */
  trade: string
  /** The first day the work that waits on it starts. Null: it holds nothing on the chart. */
  neededBy: string | null
  /** Days from the day it is needed to the day it is expected. Positive: it comes after the work was to start. */
  daysLate: number
  /** Expected after the day it is needed, or its day passed with nothing in. */
  late: boolean
  holds: { lineId: string; name: string; start: string }[]
  /** "Expected Oct 20 from Carrier, 8 days after Rooftop units starts." */
  words: string
  /** The next step's name, for the button: "Ordered", "Shipped", "On site". Null when it is in. */
  nextStep: { step: 'asked' | 'shipped' | 'done'; label: string } | null
}

function cap(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

export function waitState(w: ScheduleWait): WaitState {
  if (w.doneOn) return 'done'
  if (w.kind === 'delivery' && w.shippedOn) return 'shipped'
  if (w.askedOn) return 'asked'
  return 'notAsked'
}

/** The step after this one, in the kind's words. */
export function waitNextStep(w: ScheduleWait): WaitRow['nextStep'] {
  const k = waitKind(w.kind)
  const state = waitState(w)
  if (state === 'done') return null
  if (state === 'notAsked') return { step: 'asked', label: cap(k.asked) }
  if (state === 'asked' && w.kind === 'delivery') return { step: 'shipped', label: 'Shipped' }
  return { step: 'done', label: cap(k.done) }
}

function stateWords(w: ScheduleWait): string {
  const k = waitKind(w.kind)
  const state = waitState(w)
  if (state === 'done') return `${k.done} ${shortDate(w.doneOn ?? '')}`
  if (state === 'shipped') return `shipped ${shortDate(w.shippedOn ?? '')}`
  if (state === 'asked') return `${k.asked} ${shortDate(w.askedOn ?? '')}`
  return `not ${k.asked} yet`
}

/** Every wait with where it stands: open ones first by the day they are needed, then the ones in, newest first. */
export function waitRows(state: GcState, project: GcProject, today = state.today): WaitRow[] {
  const activities = project.schedule?.activities ?? []
  const rows = (project.waits ?? []).map((wait): WaitRow => {
    const held = wait.lineIds.flatMap((lineId) => {
      const a = activities.find((x) => x.lineId === lineId)
      return a ? [{ lineId, name: moveActivityName(project, lineId), start: a.start }] : []
    })
    const neededBy = held.reduce<string | null>((m, h) => (m === null || h.start < m ? h.start : m), null)
    const st = waitState(wait)
    const daysLate = neededBy ? daysBetween(neededBy, wait.expectedOn) : 0
    const passed = st !== 'done' && today > wait.expectedOn
    const late = st !== 'done' && (passed || (neededBy !== null && wait.expectedOn >= neededBy))
    const pkg = wait.packageId ? project.packages.find((k) => k.id === wait.packageId) : undefined
    const when = st === 'done' ? `${cap(waitKind(wait.kind).done)} ${weekdayDate(wait.doneOn ?? '')}` : passed ? `Expected ${shortDate(wait.expectedOn)} from ${wait.who}, and not in` : `Expected ${weekdayDate(wait.expectedOn)} from ${wait.who}`
    const need =
      held.length === 0
        ? 'Nothing on the chart waits on it.'
        : st === 'done'
          ? `${held.map((h) => h.name).join(', ')} ${held.length === 1 ? 'waited' : 'waited'} on it.`
          : daysLate > 0
            ? `${daysLate} ${daysLate === 1 ? 'day' : 'days'} after ${held[0]?.name} starts.`
            : daysLate === 0
              ? `the day ${held[0]?.name} starts.`
              : `${-daysLate} ${daysLate === -1 ? 'day' : 'days'} before ${held[0]?.name} starts.`
    return {
      wait,
      state: st,
      stateWords: stateWords(wait),
      tone: st === 'done' ? 'green' : late ? 'red' : st === 'notAsked' ? 'amber' : 'grey',
      trade: pkg?.trade ?? "the job's own",
      neededBy,
      daysLate,
      late,
      holds: held,
      words: `${when}${held.length > 0 && st !== 'done' ? `, ${need}` : `. ${need}`}`,
      nextStep: waitNextStep(wait),
    }
  })
  const open = rows.filter((r) => r.state !== 'done').sort((a, b) => (a.neededBy ?? a.wait.expectedOn).localeCompare(b.neededBy ?? b.wait.expectedOn))
  const done = rows.filter((r) => r.state === 'done').sort((a, b) => (b.wait.doneOn ?? '').localeCompare(a.wait.doneOn ?? ''))
  return [...open, ...done]
}

/**
 * The holds on the chart (G-16): a line is held by a wait that is not in and is expected on or
 * after the day the line starts, or whose day has passed. One expected well before the work is no
 * hold; it is a row to watch.
 */
export function waitHolds(state: GcState, project: GcProject, today = state.today): Map<string, GanttHold> {
  const holds = new Map<string, GanttHold>()
  const activities = project.schedule?.activities ?? []
  for (const row of waitRows(state, project, today)) {
    if (row.state === 'done' || !row.late) continue
    for (const h of row.holds) {
      if (holds.has(h.lineId)) continue
      const a = activities.find((x) => x.lineId === h.lineId)
      const passed = today > row.wait.expectedOn
      const after = a ? daysBetween(a.start, row.wait.expectedOn) : 0
      const words = passed
        ? `${row.wait.title}, expected ${shortDate(row.wait.expectedOn)} and not in`
        : `${row.wait.title}, expected ${shortDate(row.wait.expectedOn)}, ${after === 0 ? 'the day this starts' : `${after} ${after === 1 ? 'day' : 'days'} after this starts`}`
      holds.set(h.lineId, { kind: row.wait.kind, words, late: passed || after > 0 })
    }
  }
  return holds
}

/** The decisions the customer owes, for What we need from you (G-74, G-92): each with the day it starts costing time. */
export function customerDecisions(project: GcProject): { words: string; by: string | null }[] {
  const activities = project.schedule?.activities ?? []
  return (project.waits ?? [])
    .filter((w) => w.kind === 'decision' && !w.doneOn)
    .map((w) => {
      const starts = w.lineIds.flatMap((id) => {
        const a = activities.find((x) => x.lineId === id)
        return a ? [a.start] : []
      })
      const by = starts.length > 0 ? starts.reduce((m, s) => (s < m ? s : m)) : w.expectedOn
      const work = w.lineIds.map((id) => moveActivityName(project, id).replace(/^.* · /, '')).filter(Boolean)
      return { words: `Your decision on ${w.title}, needed by ${weekdayDate(by)}${work.length > 0 ? `: ${work.join(', ')} ${work.length === 1 ? 'waits' : 'wait'} on it` : ''}.`, by }
    })
}

/** Who we wait on by default: the trade's company for a delivery, the customer, the city, or the utility. */
export function waitWhoDefault(state: GcState, project: GcProject, kind: WaitKind, packageId: string | null): string {
  if (kind === 'decision') return project.owner
  if (kind === 'permit') return `City of ${project.town}`
  if (kind === 'utility') return 'The utility'
  const pkg = packageId ? project.packages.find((k) => k.id === packageId) : undefined
  const invite = pkg?.invites.find((i) => i.id === pkg.awardedInviteId)
  const company = invite ? partnerById(state, invite.partnerId)?.company : undefined
  return company ? `${company}'s supplier` : 'The supplier'
}

export function nextWaitId(project: GcProject): string {
  const n = (project.waits ?? []).reduce((m, w) => Math.max(m, Number(w.id.split('-').pop()) || 0), 0) + 1
  return `${project.id}-wait-${n}`
}

/** The counts for the Schedule tab's card: open, late. */
export function waitCounts(state: GcState, project: GcProject): { open: number; late: number } {
  const rows = waitRows(state, project)
  return { open: rows.filter((r) => r.state !== 'done').length, late: rows.filter((r) => r.state !== 'done' && r.late).length }
}
