/**
 * Client door to the test-report kernel (v2.3296). The Deno file is dependency-free, so the
 * modal, the jsPDF renderer, and the portal all read one source — the same precedent as the
 * estimate letterhead email and the contract forms schema.
 */
export {
  DEFAULT_TEST_REPORT_SETTINGS,
  GAS_FIXTURE_QUICK_PICKS,
  GAS_IN_WC_PER_PSI,
  GAS_MM_WC_PER_PSI,
  GAS_OZ_PER_PSI,
  TEST_REPORT_AUTO_SEND_CHOICES,
  TEST_REPORT_AUTO_SEND_GRACE_MINUTES,
  TEST_REPORT_DEFAULT_DURATION_MIN,
  TEST_REPORT_DURATION_CHOICES,
  TEST_REPORT_TYPES,
  VERDICT_LINE,
  buildTestReportBlocks,
  certificationSignatureBlock,
  emptyTestReportData,
  formatBtu,
  formatTestReportDate,
  formatTestType,
  gasFixturesForPaper,
  gasFixturesTotalBtu,
  gasPressureFromPsi,
  gasPressureToPsi,
  inferTestReportDraft,
  isHydrostaticType,
  parseEmailList,
  parseTestReportSettings,
  resolveTestReportText,
  splitTestReportAddress,
  testReportDataFromRowLike,
  testReportPdfFilename,
  testReportSendBlockers,
  testReportServiceDescription,
  testReportShortLabel,
  testReportTitle,
  type GasFixture,
  type GasPressure,
  type GasPressureUnit,
  type TestReportBlock,
  type TestReportColumn,
  type TestReportData,
  type TestReportDraftHint,
  type TestReportJobInfo,
  type TestReportResolvedText,
  type TestReportResult,
  type TestReportSettings,
  type TestReportSystem,
  type TestReportType,
} from '../../../supabase/functions/_shared/testReport'
