// Generated by `npm run check:todo-drift -- --fix` from the to-dos' front matter. Do not edit;
// change the to-do file and re-render. CI (`npm run check:todo-drift`) fails when this is stale.
import type { BoardData } from '../lib/todos/todoBoard'

const data: BoardData = {
  "validated": {
    "date": "2026-09-19",
    "version": "v2.3613"
  },
  "openItems": 26,
  "items": [
    {
      "slug": "day-book",
      "group": "ready",
      "name": "Day book",
      "file": "to-dos/day-book/README.md",
      "pointer": false,
      "summary": "Day book: a People tab that says what each office person and estimator got done on any day, read from the actor-stamped records the app already writes — Billed 3 · J102 J258 J273, Applied 4 deposits, Sent 2 contracts, Approved 12 clock sessions, Sent 2 bids · $412k — with a week list, a person door, a month grid by kind of work that flags gaps rather than scoring volume, today's lines ending in what is left, and an estimating strip measured against the person's own trailing months. Nothing is typed; a quiet day says what the app cannot see.",
      "next": "PR 1b (the send functions stamp sent_by_user_id so invoice sends attribute), PR 3 the month rhythm grid, PR 4 estimator lines + range strip, PR 5 the schedule-block ledger, PR 6 the Crew Day one-liner + email, PR 7 the nightly queue snapshot.",
      "size": "L (7 PRs, 3 migrations, 1 trigger table, 1 cron)",
      "blocker": "None for PRs 0–3. Five proposed defaults below stand until the owner says otherwise.",
      "ver": "designed 09-16",
      "opinion": "later — seven PRs and a cron for management oversight; wait until Grace says she would read it weekly.",
      "mockups": [
        "to-dos/day-book/mockup.html"
      ],
      "artifacts": [
        {
          "label": "Office Days",
          "url": "https://claude.ai/artifact/6hhWGCLhYZWGNQLbPyj5f2"
        },
        {
          "label": "Office Day Outcomes",
          "url": "https://claude.ai/artifact/6GoxkNC4G9K3Bxy1V13HUA"
        }
      ],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "helper-tryout-loop",
      "group": "ready",
      "name": "Hiring: the helper try-out loop",
      "file": "to-dos/helper-tryout-loop/README.md",
      "pointer": false,
      "summary": "An assistant feeds helpers to the master plumbers; the masters (or the subs the helper is placed with) try them on jobs and say, by name and the same day, which ones they want back; the office hires the ones the leaders keep asking for. The Hiring board does the feeding half (Screen) and the paperwork half (Hire) and nothing in between: a helper has to be hired to be scheduled, the only field feedback is the anonymous fortnightly crew deck, and nothing on a card says how the try-out went. This adds a Try-out stage (on the roster as a trial helper, card still linked), a one-tap verdict card for whoever led the helper that day — dealt when the helper clocks out, since masters do not clock (take them again: yes / no / not sure + a word), a tally on the card (days, which master said what), a nudge to Hire or Pass — and, so the assistant can feed without seeing the rest of the board, a share list per column enforced in RLS.",
      "next": "PR 1 — the Try-out stage: team_prospects.trial_user_id, users.trial_prospect_id, status trial; Try out on a helper card creates the roster user (existing create-user hand-off) flagged trial; the stage strip gains Try-out. Then PR 2 the leader's verdict card (push at the helper's clock-out + a Dashboard card for the derived lead) and team_prospect_trial_verdicts, PR 3 the tally + Hire / Pass / Keep trying, PR 4–6 the column share (table + policies, Share with…, the helper's tab).",
      "size": "S · S · S · S · S · M",
      "blocker": "None — Who's where shipped (v2.3607 the day, v2.3609 the week by crew), so derivedLead exists to read. Owner calls taken as drawn: the verdict is asked of the helper's lead for the day — a master or a sub — when the helper clocks out, once per helper per day, by name; Try out writes no leader link; a helper column skips the Interview call; the office presses Hire, the leaders never do.",
      "ver": "",
      "opinion": "build — PRs 1–3 are the purpose and ride the derived lead and the clock-out webhook that already exist; the share (4–6) is what lets the assistant feed the column at all.",
      "mockups": [
        "to-dos/helper-tryout-loop/mockup-share.html",
        "to-dos/helper-tryout-loop/mockup.html"
      ],
      "artifacts": [],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "po-generator-stated-need",
      "group": "ready",
      "name": "PO code — what they said they need",
      "file": "to-dos/po-generator-stated-need.md",
      "pointer": false,
      "summary": "When the office mints a counter PO code, the tech has just said what it is for — \"40 ft of ¾\" PEX\", \"a drain machine\" — and nothing writes that down. The row already has a notes column and both forms already write it; the desktop form calls it \"Optional notes…\" and nothing reads it back. Option A: relabel Notes as What they said they need on both doors with a concrete placeholder, put the claim in the text to the tech, rename the ledger column, and show the matched ledger entry (job, person, claim) on the supply-house invoice form under the PO check — so $612 against \"40 ft of PEX and two valves\" is a question the office can ask the day the invoice arrives. No migration.",
      "next": "Merge PR 1; watch whether the field gets filled for a couple of weeks; then decide PR 2 (the kind chip) or close the to-do.",
      "size": "S",
      "blocker": "None.",
      "ver": "v2.3599",
      "opinion": "your call after PR 1 merges — PR 2 only if tool purchases on job POs turn out to be real.",
      "mockups": [
        "to-dos/po-generator-stated-need-mockups.html"
      ],
      "artifacts": [
        {
          "label": "artifact 1",
          "url": "https://claude.ai/artifact/5vbUpa3ufx1JU8ZSrbX8TN"
        }
      ],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "contract-paper-lane",
      "group": "ready",
      "name": "Signing it on paper",
      "file": "to-dos/contract-paper-lane/README.md",
      "pointer": false,
      "summary": "Signing it on paper: prod says the sweep's only outcome is the one that has never worked — 0 contracts ever signed through the e-signing link, 3 of 3 finished ones signed on paper, 0 customer documents in the Contract Book so the Terms dropdown has exactly one option (a source constant). The lane runs one way: the app files signed paper but cannot produce the page to sign. Proposed: How this one gets signed per row (email the PDF to sign by hand · email a signing link · download to print), a gc_job row collapsing to File their subcontract, terms as two labelled levers with the built-in wording seeded into the Book, and Edit & re-send while a sent agreement is still unopened. Reach, counted live 2026-09-16: 24 of the 105 rows are ready and are what this sends; 21 need an email or amount first; 59 are builder rows that nothing here sends to — their lever is the owner's customer-level agreements decision. Mock-up carries the rejected first pass and the five-point critique.",
      "next": "Ask Taunya which terms she means (legal paragraphs or the payment line) — one message, it resizes PR 4. Then PR 2 the hand-off stamp (one migration); PR 3 email the PDF; PR 4 terms as two levers; PR 5 the three-way block; PR 6 Edit & re-send.",
      "size": "L (5 PRs left)",
      "blocker": "The owner's approval of the design for PRs 2–6. Five owner decisions listed.",
      "ver": "proposed 09-15 · endorsed 09-16 · PR 1 v2.3527",
      "opinion": "your call — zero contracts ever e-signed says the lane is wrong, but PRs 2–6 are five PRs on a design you have not approved.",
      "mockups": [
        "to-dos/contract-paper-lane/mockup.html"
      ],
      "artifacts": [],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "submittals",
      "group": "ready",
      "name": "Submittals",
      "file": "to-dos/submittals/README.md",
      "pointer": false,
      "summary": "Submittals: the product decision as one row per fixture tag from the plan's schedule to the GC's approval — a Specified column and status chips on the quote compare, a Submittals tab after Cover Letter (rows, revisions, the package PDF), the house's cut-sheet page, the GC's review page and decisions, four Needs You cards, the won question, then the customer portal: the submittal line and card, a We need you strip, one conversation per job, a push when a revision lands; robots read the schedule, split PDFs by tag and lift redlines. Nine artboards in the folder.",
      "next": "Run the robot half of gate 6b from a twin seat (BP398 has a read_redlines task queued); then first real use on SpaceX Rev 4; 3b when the owner says so. Owed live checks: Wendi pastes the schedule on one live bid she is pricing this week (gate 1's second half) and the SpaceX Rev 3 rebuild on B375 (gate 2's second half).",
      "size": "S (live checks and SpaceX; 3b gated)",
      "blocker": "A twin key for the robot half of gate 6b; the live gates need Wendi on one live bid and the SpaceX Rev 3 on B375.",
      "ver": "stages 1 → 6c shipped",
      "opinion": "later — everything shippable shipped; what is left is live gates that need Wendi and a twin key, not code.",
      "mockups": [
        "to-dos/submittals/before-after-5b.html",
        "to-dos/submittals/mockup.html"
      ],
      "artifacts": [
        {
          "label": "design canvas 1",
          "url": "https://claude.ai/artifact/2tUmSFQPqNaedEhQbeJVaX"
        },
        {
          "label": "design canvas 2",
          "url": "https://claude.ai/artifact/JHb3f7Tr7LVPfjMg6sdNLf"
        }
      ],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "supervision",
      "group": "ready",
      "name": "Supervision: one switch instead of team leads",
      "file": "to-dos/supervision/README.md",
      "pointer": false,
      "summary": "A job-day is covered when someone on it does not need supervision. That is the whole org chart for hourly, per-job work, and it replaces the Team leads list (leader → member links nobody maintains, three archived leaders still in it). One switch per helper and per sub — needs supervision, on by default, off when the office decides they can run a job — and everything else is read: the supervisor of a job-day is whoever is listed on it and does not need supervising; Dispatch warns when a block has nobody like that; Who's where marks supervising and unsupervised; the supervisors of the day own the reports, see (not approve) the crew's hours, and rate the crew monthly with the three sliders. The helper try-out loop asks them the verdict.",
      "next": "PR 4 — Rate my crew: a monthly deck on the Dashboard for supervisors, one card per person they supervised for two or more days that month, the three sliders + remarks, written to team_member_reviews as one more reviewer (by name; the Review stage gains a supervisor chip). Then PR 5 retire Team leads.",
      "size": "S (done) · S (done) · M (done) · S · S",
      "blocker": "None. Owner calls taken as drawn (2026-09-19): two levels per helper and per sub — supervision required / not required; masters never need it; superintendents and office roles are not supervision; Dispatch warns, never refuses; ratings monthly; subs who do not need supervision count as coverage for their own helpers.",
      "ver": "v2.3611 · 3612 · 3613",
      "opinion": "build — five small PRs that delete a maintained list and answer the question the owner actually asked (\"does every job have someone competent on it\").",
      "mockups": [
        "to-dos/supervision/before-after.html"
      ],
      "artifacts": [],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "pay-run-payments-view",
      "group": "close",
      "name": "Pay run: a Payments view",
      "file": "to-dos/pay-run-payments-view/README.md",
      "pointer": false,
      "summary": "A view of just the payments made on People → Pay → Payroll: a third pill beside Pay run · Balances — Payments — one row per payment (paid on, person, period, amount, memo, who recorded it), every header a sort, a window (30 d · 90 d · this year · all), the same name box also matching memo text, a total for what is visible, and by week paid / by person bands like the ledger's. Reads pay_stub_payments joined to pay_stubs; no new writes.",
      "next": "Once #3377 lands, use it for a week. The two follow-ups the owner did not pick stay here as the options they are: the by-week-paid / by-person band modes (S), and a real method field on Record payment with a chip filter (M, one migration). Delete the folder when neither is wanted.",
      "size": "S (bands) · M (a method field)",
      "blocker": "A week of use; the two follow-ups are the owner's to want.",
      "ver": "mock-up 09-17",
      "opinion": "later — the flat list answers the ask; add bands or a method field only when the list shows it needs them.",
      "mockups": [
        "to-dos/pay-run-payments-view/before-after.html"
      ],
      "artifacts": [],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "gc-on-notice",
      "group": "close",
      "name": "Put a GC on notice",
      "file": "to-dos/gc-on-notice/README.md",
      "pointer": false,
      "summary": "Put a GC on notice: one modal that sends the § 53.056 notice (the notice of intent to lien — fund trapping, § 53.081) to every owner on every job with a failing GC, for every unnoticed month, no 30-day window: find the owners first, months and claim amounts named, one cover letter for all, one decision (reason on the record + the GC's standing rule, payment terms, a Legal desk account) → the run. Three doors (Pipeline GC filter ⋯, Customer review, the desk header). Mock-up in the folder.",
      "next": "The first real run on a TEST GC (approve, print, record), then delete the folder. Residuals stay listed: a GC-wide demand letter, one envelope for two notices to one owner, the attorney's § 53.081 wording.",
      "size": "XS",
      "blocker": "A live run.",
      "ver": "v2.3469 · 3470 · 3482 · 3479",
      "opinion": "your call — the code is done; the first real run on a test GC is yours to sit through.",
      "mockups": [
        "to-dos/gc-on-notice/mockup.html"
      ],
      "artifacts": [],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "test-reports",
      "group": "close",
      "name": "Test reports (retire plumbingtooling.com)",
      "file": "to-dos/test-reports/README.md",
      "pointer": false,
      "summary": "The hydrostatic / gas test report and its email (report PDF + Stripe pay link to the GC), rebuilt inside PipeTooling from the plumbingtooling.com app: kernel + real-text PDF, job_test_reports, the modal on the Stages door, Send to the GC, drafts from the clock-out report, Needs You line, portal; retire the external app. Mock-up in the folder.",
      "next": "Around Oct 11: drop the footer link + buildClickToolingUrl, archive the repo.",
      "size": "XS",
      "blocker": "Dated ~2026-10-11.",
      "ver": "v2.3296–3331",
      "opinion": "later — dated October 11; nothing to do until then.",
      "mockups": [
        "to-dos/test-reports/mockup-portal.html",
        "to-dos/test-reports/mockup.html"
      ],
      "artifacts": [],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "crew-pnl-and-wheels",
      "group": "gated",
      "name": "Crew P&L: wheels and the $50 default",
      "file": "to-dos/crew-pnl-and-wheels.md",
      "pointer": false,
      "summary": "Vehicle rates on Crew P&L and Bids; the $50 sub-equivalent default; the backlog lines still true.",
      "next": "Wheels PR 3 yes / no.",
      "size": "S + S",
      "blocker": "Optional, your call.",
      "ver": "from v2.2735",
      "opinion": "drop — vehicle rates on Crew P&L move numbers nobody has asked to see, and the $50 default already stands.",
      "mockups": [
        "to-dos/crew-pnl-and-wheels-before-after.html"
      ],
      "artifacts": [],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "division-22-rules-manager",
      "group": "gated",
      "name": "Division 22 rules manager",
      "file": "to-dos/division-22-rules-manager.md",
      "pointer": false,
      "summary": "Rules manager UI; RH / EDF / med-gas seed call. Gas and the Needs You card shipped.",
      "next": "Wendi: is pinning enough? You: seed RH / EDF, rule on med gas?",
      "size": "M",
      "blocker": "Wendi + you.",
      "ver": "coverage 73%",
      "opinion": "later — coverage is 73% and gas shipped; ask Wendi once whether pinning is enough before building a manager.",
      "mockups": [
        "to-dos/division-22-rules-manager-before-after.html"
      ],
      "artifacts": [],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "owner-decisions-pending",
      "group": "gated",
      "name": "Owner decisions pending (the standing list)",
      "file": "to-dos/owner-decisions-pending.md",
      "pointer": true,
      "summary": "Every yes/no the docs are waiting on, one line each.",
      "next": "Walk the table in one sitting; each answer deletes a line.",
      "size": "a sitting",
      "blocker": "You.",
      "ver": "re-verified 09-17",
      "opinion": "",
      "mockups": [],
      "artifacts": [],
      "mockup": "not-required",
      "mockupNote": ""
    },
    {
      "slug": "partnerships-off-toggles",
      "group": "gated",
      "name": "Partnerships: the off toggles",
      "file": "to-dos/partnerships-off-toggles.md",
      "pointer": false,
      "summary": "Notice delivery, estimating cap, W2 watch (modeled); runway floor (not modeled); the notes preview.",
      "next": "You + the attorney first; then one scoped PR per toggle.",
      "size": "M each",
      "blocker": "You + attorney.",
      "ver": "plan decision 6",
      "opinion": "your call — attorney-dependent, and nothing in the app is wrong without them.",
      "mockups": [
        "to-dos/partnerships-off-toggles-before-after.html"
      ],
      "artifacts": [],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "stage-plan-residuals",
      "group": "gated",
      "name": "Stage Plan: items 3–4",
      "file": "to-dos/stage-plan-residuals.md",
      "pointer": false,
      "summary": "What the Stage Plan train (v2.3083–v2.3134) left: capable-to-bill reading billable(), retiring offered_to_gc / bundles, plain rows on the final draw, the Any-done rule, the drawer's mint door.",
      "next": "Items 3–4 are yours — the final-draw sweep of plain rows, and an office-marked done.",
      "size": "S each",
      "blocker": "Both remaining items are owner calls.",
      "ver": "3 of 5 shipped",
      "opinion": "later — both are final-draw conveniences no one has asked for twice.",
      "mockups": [
        "to-dos/stage-plan-residuals-before-after.html"
      ],
      "artifacts": [],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "weekly-money-later",
      "group": "gated",
      "name": "Weekly Money phase 6",
      "file": "to-dos/weekly-money-later.md",
      "pointer": false,
      "summary": "Phase 6: drilldowns, GC lens, month roll-up, timeline feed, wider access.",
      "next": "Any of these wanted?",
      "size": "M",
      "blocker": "Optional, your call.",
      "ver": "plan phase 6",
      "opinion": "drop — drilldowns on a report read once a week; build the piece when someone names the question it answers.",
      "mockups": [
        "to-dos/weekly-money-later-before-after.html"
      ],
      "artifacts": [],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "job-summary-follow-ups",
      "group": "waiting",
      "name": "Job Summary: what is left",
      "file": "to-dos/job-summary-follow-ups.md",
      "pointer": false,
      "summary": "What the Job Summary train left: overtime as its own Capacity slice and travel on Days both wait on ledger fields the day ledger does not carry; Crew P&L still credits gross bill by hours rather than the earned-revenue kernel the Jobs view reads since v2.3575.",
      "next": "Nothing until the day ledger carries per-person weekly hours (overtime) and per-session start times (travel). Crew P&L onto the kernel is a sitting when Crew P&L is next opened.",
      "size": "M each, gated",
      "blocker": "Ledger fields for items 2 and 4; a Crew P&L sitting for the kernel's other half.",
      "ver": "5 of 8 shipped · kernel v2.3575",
      "opinion": "later — nothing on Job Summary is wrong today; the two field additions follow the ledger, not the other way round.",
      "mockups": [
        "to-dos/job-summary-follow-ups-earned-revenue.html"
      ],
      "artifacts": [
        {
          "label": "design canvas",
          "url": "https://claude.ai/artifact/JHb3f7Tr7LVPfjMg6sdNLf"
        }
      ],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "journey-map-tier-1",
      "group": "waiting",
      "name": "Journey map: J31-N4",
      "file": "to-dos/journey-map-tier-1.md",
      "pointer": true,
      "summary": "Which drift rows are closed here; the list lives in the private repo.",
      "next": "Read _DRIFT-2 in the private repo first.",
      "size": "S",
      "blocker": "Private repo context.",
      "ver": "tiers 1–4 mostly closed",
      "opinion": "",
      "mockups": [],
      "artifacts": [],
      "mockup": "not-required",
      "mockupNote": ""
    },
    {
      "slug": "per-gc-bid-retirement",
      "group": "waiting",
      "name": "Per-GC bids: retire submitted_to / itb_links",
      "file": "to-dos/per-gc-bid-retirement.md",
      "pointer": false,
      "summary": "Retire bids.submitted_to / itb_links behind bid_gcs; the auto-derive question.",
      "next": "One mechanical PR after real per-GC usage.",
      "size": "M",
      "blocker": "Usage.",
      "ver": "v2.2416 base",
      "opinion": "later — a mechanical PR once real per-GC usage shows the two columns are dead.",
      "mockups": [],
      "artifacts": [],
      "mockup": "not-required",
      "mockupNote": "retires two columns — no screen changes"
    },
    {
      "slug": "person-identity-phase-e",
      "group": "waiting",
      "name": "Person identity phase E",
      "file": "to-dos/person-identity-phase-e.md",
      "pointer": false,
      "summary": "NOT NULL, re-PK off person_name, retire the name cascade — after a quiet quarter.",
      "next": "Revisit in December.",
      "size": "M",
      "blocker": "A quiet quarter.",
      "ver": "phases A–D done",
      "opinion": "later — a primary-key change on people in a busy quarter is risk without payoff; December as written.",
      "mockups": [],
      "artifacts": [],
      "mockup": "not-required",
      "mockupNote": "a schema change — no screen changes"
    },
    {
      "slug": "review-into-the-bridge",
      "group": "waiting",
      "name": "Review folds into the Bridge: step 3",
      "file": "to-dos/review-into-the-bridge.md",
      "pointer": false,
      "summary": "People → Review folds into the Bridge: one earned convention + the Vectors row as the door (v2.3360, v2.3366), retire Team Summary once the tables agree (gated). Teammates get money-free Needs You items only.",
      "next": "Explain Tristen's $201 gap for Sep 6–12 (five jobs — JP1007, JP931, JP878, JP523, JP1004 — against the Bridge's per-session earned), then check Sep 13–19 after it closes; if both agree, ship the redirect.",
      "size": "M",
      "blocker": "One gap to explain, and the Sep 13–19 week to close.",
      "ver": "v2.3360 / 66 / 68",
      "opinion": "build — once two more pay weeks agree it is a redirect and a retirement, and it removes a duplicate surface people still open.",
      "mockups": [],
      "artifacts": [
        {
          "label": "Step Three, Redrawn",
          "url": "https://claude.ai/code/artifact/9c72e792-f8ea-43c9-8b92-6afca365c376"
        }
      ],
      "mockup": "not-required",
      "mockupNote": "step 3 is a redirect and a retirement once the tables agree — no new screen"
    },
    {
      "slug": "decomposition-residuals",
      "group": "residual",
      "name": "Decomposition residuals: the Workbench block, the picker sweep",
      "file": "to-dos/decomposition-residuals.md",
      "pointer": false,
      "summary": "What the two decomposition trains left on purpose: the Pricing tab's Workbench block (P2 — 1,975 lines over 77 state values, re-mapped into nine blocks in the architecture map, not worth cutting until a Workbench feature train needs a smaller file), the shared bid-picker sweep (~15 lines × fourteen tabs, a quiet-week mechanical PR), the L4 box components (18 props for 253 lines — the formulas were the duplication and they are one kernel now), and the optional renderStagesFieldAndBillingLines component on the Stages map.",
      "next": "Nothing scheduled. The Workbench cut starts as PR 1 of the next Workbench feature train, from the nine-block table in the map's P2 dossier; the picker sweep goes the next day the Bids surface has no open PR.",
      "size": "XS (sweep) · L (Workbench, only inside a feature train)",
      "blocker": "None. Each is a judgment about value, recorded in the map.",
      "ver": "closed 09-17",
      "opinion": "drop — left by decision; the Workbench cut only pays inside a Workbench feature train.",
      "mockups": [],
      "artifacts": [],
      "mockup": "not-required",
      "mockupNote": "refactors — no screen changes"
    },
    {
      "slug": "dispatch-residuals",
      "group": "residual",
      "name": "Dispatch residuals",
      "file": "to-dos/dispatch-residuals.md",
      "pointer": false,
      "summary": "Dispatch blocks / nudge history on the sheet rows, the tag-slice refresh. The phone-request self-heal shipped v2.3567 (the inbox sweep covers add_job_phone as it covers link_job_pictures).",
      "next": "The sheet-row history when the feed or the email log grows a per-sheet key; the tag-slice sum server-side.",
      "size": "S",
      "blocker": "None.",
      "ver": "from v2.2880 / 83 · item 1 v2.3567",
      "opinion": "later — the self-heal shipped; the two left wait on data the sheet rows do not carry yet.",
      "mockups": [],
      "artifacts": [],
      "mockup": "not-required",
      "mockupNote": "draw the sheet-row history when it is picked up"
    },
    {
      "slug": "robots-residuals",
      "group": "residual",
      "name": "Robots residuals (client side)",
      "file": "to-dos/robots-residuals.md",
      "pointer": false,
      "summary": "Client-side leftovers only; the twins program runs from docs/twins/HANDOFF.md.",
      "next": "The CI route / slug test (S).",
      "size": "S",
      "blocker": "CT-side work for the rest.",
      "ver": "program in HANDOFF",
      "opinion": "later — the CI route test is S but nothing is broken; fold it into the next twin PR.",
      "mockups": [],
      "artifacts": [],
      "mockup": "not-required",
      "mockupNote": "a CI route / slug test — no screen changes"
    },
    {
      "slug": "sub-payment-move-remove",
      "group": "residual",
      "name": "Sub payments — move or remove, the rest",
      "file": "to-dos/sub-payment-move-remove/README.md",
      "pointer": false,
      "summary": "A payment recorded on the wrong job can now be moved to the right one instead of deleted and retyped. Shipped for sub sheets (Jobs → Subs → Pay): every payment and backcharge row carries Edit · Move… · Remove, Move lists the same sub's other sheets first and previews both sheets' paid and owed, Remove asks why and can be undone for 30 days, and both sheets keep a grey trace line. Two pieces are left — carrying that trace to the sub's own portal so a sub does not phone about a payment that vanished, and putting the same Move to job… on customer payments in Edit Job, where only a sent bill may refuse the move.",
      "next": "Someone runs one real move on a throwaway sheet and one on a throwaway job (the recipe below), then the folder closes; the three wording / policy calls stay open until asked.",
      "size": "XS — a live test",
      "blocker": "None for PR 2. Three wording / policy calls in Open questions are the owner's and change one constant each.",
      "ver": "v2.3562 · v2.3576 · v2.3605",
      "opinion": "",
      "mockups": [
        "to-dos/sub-payment-move-remove/before-after.html"
      ],
      "artifacts": [
        {
          "label": "design canvas — Delete or move a payment",
          "url": "https://claude.ai/artifact/KevTT7eXyDAi4MENU5GAa8"
        }
      ],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "subs-residuals",
      "group": "residual",
      "name": "Subs residuals",
      "file": "to-dos/subs-residuals.md",
      "pointer": false,
      "summary": "Derived sheet stage (now unblocked), Spanish signature form, compliance chips, offer templates, benched subs in the sheet form, roster hygiene.",
      "next": "The bench flag (S); the Spanish pass with the next portal change.",
      "size": "S each",
      "blocker": "None.",
      "ver": "board polish done v2.3395",
      "opinion": "later — the bench flag is S; the Spanish pass rides with the next portal change.",
      "mockups": [],
      "artifacts": [],
      "mockup": "waiting",
      "mockupNote": ""
    },
    {
      "slug": "supply-house-credit-residuals",
      "group": "residual",
      "name": "Supply house credits: what the train left",
      "file": "to-dos/supply-house-credit-residuals.md",
      "pointer": false,
      "summary": "What the supply-house credits train left. The feature is done: a return is recorded as its own document with a negative amount and a document_kind, the aging table carries credits in their own column, and the two edges that would double-count a credit refuse it. One thing outlives it — pairing a credit to the invoice it credits, deferred until the office says it wants the field. The card-refund sign bug found alongside it shipped as v2.3519 / v2.3525.",
      "next": "Nothing urgent. Ask the office in a few weeks whether they reach for a pairing field.",
      "size": "S (pairing)",
      "blocker": "The pairing waits on real usage.",
      "ver": "v2.3500 · 3501 · 3502 · 3503 shipped",
      "opinion": "drop — pairing a credit to its invoice is a field nobody has reached for; build it the day someone does.",
      "mockups": [],
      "artifacts": [],
      "mockup": "waiting",
      "mockupNote": ""
    },
    {
      "slug": "supply-house-job-account-aging",
      "group": "residual",
      "name": "Supply houses: aging heat map + the Job accounts leftovers",
      "file": "to-dos/supply-house-job-account-aging.md",
      "pointer": false,
      "summary": "The May follow-ups (an editable Paid On date, Last Paid sortable); after the Job accounts train (v2.3423–v2.3440): Curly's missing phone, the Job Accounts tab rename question, a mark-all back-fill. The heat map's job-account line shipped v2.3568.",
      "next": "Curly's phone and email are an office fix (item 4); the tab rename (item 5) is an owner call; items 2 and 6 only if the pile of unflagged invoices stays big.",
      "size": "S",
      "blocker": "None.",
      "ver": "item 1 v2.3568 · item 3 v2.3604 · items 4–6 added 09-14",
      "opinion": "later — what is left is an office fix, a naming call and two back-fills nobody has asked for twice.",
      "mockups": [
        "to-dos/supply-house-job-account-aging-before-after.html"
      ],
      "artifacts": [],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "what-customers-see-residuals",
      "group": "residual",
      "name": "What customers see — residuals",
      "file": "to-dos/what-customers-see-residuals.md",
      "pointer": false,
      "summary": "What the What-customers-see train left: a full sample matter on the law firm's portal (today the sample is the portal before its first matter), the signed-copy agreement email as its own step, and the Job window's Their journey door (the Customer page has it).",
      "next": "Any of the three in a quiet hour; the firm's sample matter is the largest (a fixture that satisfies parseLegalPortalPayload).",
      "size": "S each",
      "blocker": "None.",
      "ver": "shipped 09-16",
      "opinion": "later — the firm's sample matter is a fixture worth having before the next demo, not before.",
      "mockups": [],
      "artifacts": [],
      "mockup": "waiting",
      "mockupNote": ""
    }
  ]
}

export default data
