// Generated by `npm run check:todo-drift -- --fix` from the to-dos' front matter. Do not edit;
// change the to-do file and re-render. CI (`npm run check:todo-drift`) fails when this is stale.
import type { BoardData } from '../lib/todos/todoBoard'

const data: BoardData = {
  "validated": {
    "date": "2026-09-18",
    "version": "v2.3591"
  },
  "openItems": 31,
  "items": [
    {
      "slug": "day-book",
      "group": "ready",
      "name": "Day book",
      "file": "to-dos/day-book/README.md",
      "pointer": false,
      "summary": "Day book: a People tab that says what each office person and estimator got done on any day, read from the actor-stamped records the app already writes — Billed 3 · J102 J258 J273, Applied 4 deposits, Sent 2 contracts, Approved 12 clock sessions, Sent 2 bids · $412k — with a week list, a person door, a month grid by kind of work that flags gaps rather than scoring volume, today's lines ending in what is left, and an estimating strip measured against the person's own trailing months. Nothing is typed; a quiet day says what the app cannot see.",
      "next": "PR 1b (the send functions stamp sent_by_user_id so invoice sends attribute), PR 3 the month rhythm grid, PR 4 estimator lines + range strip, PR 5 the schedule-block ledger, PR 6 the Crew Day one-liner + email, PR 7 the nightly queue snapshot.",
      "size": "L (7 PRs, 3 migrations, 1 trigger table, 1 cron)",
      "blocker": "None for PRs 0–3. Five proposed defaults below stand until the owner says otherwise.",
      "ver": "designed 09-16",
      "opinion": "later — seven PRs and a cron for management oversight; wait until Grace says she would read it weekly.",
      "mockups": [
        "to-dos/day-book/mockup.html"
      ],
      "artifacts": [
        {
          "label": "Office Days",
          "url": "https://claude.ai/artifact/6hhWGCLhYZWGNQLbPyj5f2"
        },
        {
          "label": "Office Day Outcomes",
          "url": "https://claude.ai/artifact/6GoxkNC4G9K3Bxy1V13HUA"
        }
      ],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "pipeline-load-speed",
      "group": "ready",
      "name": "Pipeline load speed",
      "file": "to-dos/pipeline-load-speed/README.md",
      "pointer": false,
      "summary": "Pipeline (Stages) loads 136 database requests per visit and re-runs all of them on every tab switch. The first section shows at 0.6 s, the rest at 1.3–2.5 s, and the page keeps working until 5.5 s. The server is not the problem (every query is milliseconds); the count is. PR 1 stops the Mercury card-charge loader on a tab that never renders it and keys the list-driven effects on a stable id string (≈ −90 requests). PR 2 paints rows from the primary query before the four enrichment passes land. PR 3 folds those passes into one RPC. PR 4 remembers the last board on the device so cold loads paint instantly while refreshing.",
      "next": "PR 2 — paint rows from the primary query before the four enrichment passes land, and run those passes with Promise.all; the crew, geocode and thread-stats re-fires PR 1 could not stop live in the per-section scope merges this changes. Run measure.js before and after.",
      "size": "S · M · M (PR 1 done)",
      "blocker": "None. Coordinate with the JobsStagesTab decomposition train (engineering-hygiene.md) — PR 1 and PR 2 touch Jobs.tsx and JobsListCacheContext.tsx, not the tab file, so they can run alongside.",
      "ver": "PR 1 v2.3569",
      "opinion": "build — PR 2 puts every section on screen at ~0.6 s and ends the re-fires PR 1 measured; PRs 3–4 after it.",
      "mockups": [],
      "artifacts": [],
      "mockup": "not-required",
      "mockupNote": "a load-speed pass — the screen stays the same"
    },
    {
      "slug": "contract-paper-lane",
      "group": "ready",
      "name": "Signing it on paper",
      "file": "to-dos/contract-paper-lane/README.md",
      "pointer": false,
      "summary": "Signing it on paper: prod says the sweep's only outcome is the one that has never worked — 0 contracts ever signed through the e-signing link, 3 of 3 finished ones signed on paper, 0 customer documents in the Contract Book so the Terms dropdown has exactly one option (a source constant). The lane runs one way: the app files signed paper but cannot produce the page to sign. Proposed: How this one gets signed per row (email the PDF to sign by hand · email a signing link · download to print), a gc_job row collapsing to File their subcontract, terms as two labelled levers with the built-in wording seeded into the Book, and Edit & re-send while a sent agreement is still unopened. Reach, counted live 2026-09-16: 24 of the 105 rows are ready and are what this sends; 21 need an email or amount first; 59 are builder rows that nothing here sends to — their lever is the owner's customer-level agreements decision. Mock-up carries the rejected first pass and the five-point critique.",
      "next": "Ask Taunya which terms she means (legal paragraphs or the payment line) — one message, it resizes PR 4. Then PR 2 the hand-off stamp (one migration); PR 3 email the PDF; PR 4 terms as two levers; PR 5 the three-way block; PR 6 Edit & re-send.",
      "size": "L (5 PRs left)",
      "blocker": "The owner's approval of the design for PRs 2–6. Five owner decisions listed.",
      "ver": "proposed 09-15 · endorsed 09-16 · PR 1 v2.3527",
      "opinion": "your call — zero contracts ever e-signed says the lane is wrong, but PRs 2–6 are five PRs on a design you have not approved.",
      "mockups": [
        "to-dos/contract-paper-lane/mockup.html"
      ],
      "artifacts": [],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "submittals",
      "group": "ready",
      "name": "Submittals",
      "file": "to-dos/submittals/README.md",
      "pointer": false,
      "summary": "Submittals: the product decision as one row per fixture tag from the plan's schedule to the GC's approval — a Specified column and status chips on the quote compare, a Submittals tab after Cover Letter (rows, revisions, the package PDF), the house's cut-sheet page, the GC's review page and decisions, four Needs You cards, the won question, then the customer portal: the submittal line and card, a We need you strip, one conversation per job, a push when a revision lands; robots read the schedule, split PDFs by tag and lift redlines. Nine artboards in the folder.",
      "next": "Run the robot half of gate 6b from a twin seat (BP398 has a read_redlines task queued); then first real use on SpaceX Rev 4; 3b when the owner says so. Owed live checks: Wendi pastes the schedule on one live bid she is pricing this week (gate 1's second half) and the SpaceX Rev 3 rebuild on B375 (gate 2's second half).",
      "size": "S (live checks and SpaceX; 3b gated)",
      "blocker": "A twin key for the robot half of gate 6b; the live gates need Wendi on one live bid and the SpaceX Rev 3 on B375.",
      "ver": "stages 1 → 6c shipped",
      "opinion": "later — everything shippable shipped; what is left is live gates that need Wendi and a twin key, not code.",
      "mockups": [
        "to-dos/submittals/before-after-5b.html",
        "to-dos/submittals/mockup.html"
      ],
      "artifacts": [
        {
          "label": "design canvas 1",
          "url": "https://claude.ai/artifact/2tUmSFQPqNaedEhQbeJVaX"
        },
        {
          "label": "design canvas 2",
          "url": "https://claude.ai/artifact/JHb3f7Tr7LVPfjMg6sdNLf"
        }
      ],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "texas-lien-rules-in-the-app",
      "group": "ready",
      "name": "The Texas lien rules, in the app",
      "file": "to-dos/texas-lien-rules-in-the-app.md",
      "pointer": false,
      "summary": "The Texas lien rules, exposed in the app for the office to read: the verified rules table (chapter 53, CPRC ch. 38, Rule 185, Fin. Code ch. 392 and § 302.002, Prop. Code ch. 28, § 31.04, § 27.031) with what the app does about each; proposed as a help guide the Texas lien rules the app follows plus a § The rules door on the Lien desk and the Lien window.",
      "next": "PR 1 the help guide 'the Texas lien rules the app follows' with per-row anchors — unblocked, write it today. PR 2 the § The rules doors on the Lien desk header and the Lien window, plus a LIEN_RULE_CITES constant.",
      "size": "S",
      "blocker": "PR 2 only: you pick where it lives and who sees it.",
      "ver": "PR 1 v2.3516",
      "opinion": "your call — PR 1 (the guide) shipped v2.3516; PR 2 is one door and waits only on where you want it and who sees it.",
      "mockups": [
        "to-dos/texas-lien-rules-in-the-app-before-after.html"
      ],
      "artifacts": [],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "pay-run-payments-view",
      "group": "close",
      "name": "Pay run: a Payments view",
      "file": "to-dos/pay-run-payments-view/README.md",
      "pointer": false,
      "summary": "A view of just the payments made on People → Pay → Payroll: a third pill beside Pay run · Balances — Payments — one row per payment (paid on, person, period, amount, memo, who recorded it), every header a sort, a window (30 d · 90 d · this year · all), the same name box also matching memo text, a total for what is visible, and by week paid / by person bands like the ledger's. Reads pay_stub_payments joined to pay_stubs; no new writes.",
      "next": "Once #3377 lands, use it for a week. The two follow-ups the owner did not pick stay here as the options they are: the by-week-paid / by-person band modes (S), and a real method field on Record payment with a chip filter (M, one migration). Delete the folder when neither is wanted.",
      "size": "S (bands) · M (a method field)",
      "blocker": "A week of use; the two follow-ups are the owner's to want.",
      "ver": "mock-up 09-17",
      "opinion": "later — the flat list answers the ask; add bands or a method field only when the list shows it needs them.",
      "mockups": [
        "to-dos/pay-run-payments-view/before-after.html"
      ],
      "artifacts": [],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "gc-on-notice",
      "group": "close",
      "name": "Put a GC on notice",
      "file": "to-dos/gc-on-notice/README.md",
      "pointer": false,
      "summary": "Put a GC on notice: one modal that sends the § 53.056 notice (the notice of intent to lien — fund trapping, § 53.081) to every owner on every job with a failing GC, for every unnoticed month, no 30-day window: find the owners first, months and claim amounts named, one cover letter for all, one decision (reason on the record + the GC's standing rule, payment terms, a Legal desk account) → the run. Three doors (Pipeline GC filter ⋯, Customer review, the desk header). Mock-up in the folder.",
      "next": "The first real run on a TEST GC (approve, print, record), then delete the folder. Residuals stay listed: a GC-wide demand letter, one envelope for two notices to one owner, the attorney's § 53.081 wording.",
      "size": "XS",
      "blocker": "A live run.",
      "ver": "v2.3469 · 3470 · 3482 · 3479",
      "opinion": "your call — the code is done; the first real run on a test GC is yours to sit through.",
      "mockups": [
        "to-dos/gc-on-notice/mockup.html"
      ],
      "artifacts": [],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "test-reports",
      "group": "close",
      "name": "Test reports (retire plumbingtooling.com)",
      "file": "to-dos/test-reports/README.md",
      "pointer": false,
      "summary": "The hydrostatic / gas test report and its email (report PDF + Stripe pay link to the GC), rebuilt inside PipeTooling from the plumbingtooling.com app: kernel + real-text PDF, job_test_reports, the modal on the Stages door, Send to the GC, drafts from the clock-out report, Needs You line, portal; retire the external app. Mock-up in the folder.",
      "next": "Around Oct 11: drop the footer link + buildClickToolingUrl, archive the repo.",
      "size": "XS",
      "blocker": "Dated ~2026-10-11.",
      "ver": "v2.3296–3331",
      "opinion": "later — dated October 11; nothing to do until then.",
      "mockups": [
        "to-dos/test-reports/mockup-portal.html",
        "to-dos/test-reports/mockup.html"
      ],
      "artifacts": [],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "burn-against-the-bid",
      "group": "gated",
      "name": "Burn against the bid: leftovers",
      "file": "to-dos/burn-against-the-bid/README.md",
      "pointer": false,
      "summary": "A job budget with provenance (bid snapshot · typed · assumed) so Burn reads against the actual bid; linking as the feature (the 15 exact matches were linked 2026-09-11; 10 ambiguous pairs wait for a hand pick); per-component burn, hours first; Bid Board chips; mock-ups kept in the folder.",
      "next": "Link the 10 pairs (UI, no code). Then decide on the two deferred pieces.",
      "size": "S + M",
      "blocker": "Your action + decision.",
      "ver": "v2.3297–3306 shipped",
      "opinion": "build (the links) — ten hand picks in Settings → Data make Burn read against real bids on those jobs; the two deferred pieces can stay deferred.",
      "mockups": [
        "to-dos/burn-against-the-bid/mockup-burn-budget-stages-2026-09-09.html",
        "to-dos/burn-against-the-bid/mockup.html"
      ],
      "artifacts": [],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "crew-pnl-and-wheels",
      "group": "gated",
      "name": "Crew P&L: wheels and the $50 default",
      "file": "to-dos/crew-pnl-and-wheels.md",
      "pointer": false,
      "summary": "Vehicle rates on Crew P&L and Bids; the $50 sub-equivalent default; the backlog lines still true.",
      "next": "Wheels PR 3 yes / no.",
      "size": "S + S",
      "blocker": "Optional, your call.",
      "ver": "from v2.2735",
      "opinion": "drop — vehicle rates on Crew P&L move numbers nobody has asked to see, and the $50 default already stands.",
      "mockups": [
        "to-dos/crew-pnl-and-wheels-before-after.html"
      ],
      "artifacts": [],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "customer-waiting-residuals",
      "group": "gated",
      "name": "Customer Waiting: three wording calls",
      "file": "to-dos/customer-waiting-residuals.md",
      "pointer": false,
      "summary": "Callback-promise wording, sub-portal priority, auto-lower overnight — three owner decisions. The code side is done: the eligibility hook, the per-caller mute and the tel: sweep.",
      "next": "The three answers; each is one string or one flag.",
      "size": "XS once decided",
      "blocker": "Three decisions are yours.",
      "ver": "hook v2.3434 · hide for me v2.3524 · sweep v2.3571",
      "opinion": "your call — the callback promise is the only one customers read; say what the office can keep and it is one string.",
      "mockups": [],
      "artifacts": [],
      "mockup": "not-required",
      "mockupNote": "three constants — no screen changes"
    },
    {
      "slug": "division-22-rules-manager",
      "group": "gated",
      "name": "Division 22 rules manager",
      "file": "to-dos/division-22-rules-manager.md",
      "pointer": false,
      "summary": "Rules manager UI; RH / EDF / med-gas seed call. Gas and the Needs You card shipped.",
      "next": "Wendi: is pinning enough? You: seed RH / EDF, rule on med gas?",
      "size": "M",
      "blocker": "Wendi + you.",
      "ver": "coverage 73%",
      "opinion": "later — coverage is 73% and gas shipped; ask Wendi once whether pinning is enough before building a manager.",
      "mockups": [
        "to-dos/division-22-rules-manager-before-after.html"
      ],
      "artifacts": [],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "email-reports-one-modal",
      "group": "gated",
      "name": "Email reports, one modal",
      "file": "to-dos/email-reports-one-modal/README.md",
      "pointer": false,
      "summary": "Email reports, one modal: fold Jobs → Reports' two buttons — Recurring Email Reports (digests on a schedule) and Report email recipients (one email per report, as filed) — into one Email reports button and modal. Option A keeps both bodies under two tabs; Option B shows one row per person with a Digest chip and an Every-report chip. Client-only, no migration. Mock-up in the folder.",
      "next": "Only if the owner picks Option B: PR 2 the people kernel and the one-row-per-person list, PR 3 the schedule line. Otherwise delete this folder.",
      "size": "M (B only)",
      "blocker": "The owner's pick — A is live; B is a rebuild of the body.",
      "ver": "PR 1 v2.3570",
      "opinion": "your call — A is live and does the job; B is worth it only if the office wants the who-gets-what view by person.",
      "mockups": [
        "to-dos/email-reports-one-modal/before-after-pr1.html",
        "to-dos/email-reports-one-modal/mockup.html"
      ],
      "artifacts": [
        {
          "label": "artifact",
          "url": "https://claude.ai/artifact/VbdxwqAKxgkzsEXAFMUSa3"
        },
        {
          "label": "design canvas",
          "url": "https://claude.ai/artifact/JHb3f7Tr7LVPfjMg6sdNLf"
        }
      ],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "bids-labor-refresh",
      "group": "gated",
      "name": "Labor refresh PR 6: one book",
      "file": "to-dos/bids-labor-refresh/README.md",
      "pointer": false,
      "summary": "\"Hours that learn\": the queue of rows the book could not answer, alias learning, source chips, the crew rate, one direct-costs list, calibration against linked jobs. Left (PR 6): fold the human labor books into Robot Default as overrides, who may recalibrate, retire Old.",
      "next": "Fold and retire, or keep the parallel run?",
      "size": "M",
      "blocker": "Your call.",
      "ver": "v2.3276–3310 shipped",
      "opinion": "later — the parallel run is still teaching the book; fold when a month of New-view use shows Old unused.",
      "mockups": [
        "to-dos/bids-labor-refresh/mockup.html"
      ],
      "artifacts": [],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "owner-decisions-pending",
      "group": "gated",
      "name": "Owner decisions pending (the standing list)",
      "file": "to-dos/owner-decisions-pending.md",
      "pointer": true,
      "summary": "Every yes/no the docs are waiting on, one line each.",
      "next": "Walk the table in one sitting; each answer deletes a line.",
      "size": "a sitting",
      "blocker": "You.",
      "ver": "re-verified 09-17",
      "opinion": "",
      "mockups": [],
      "artifacts": [],
      "mockup": "not-required",
      "mockupNote": ""
    },
    {
      "slug": "partnerships-off-toggles",
      "group": "gated",
      "name": "Partnerships: the off toggles",
      "file": "to-dos/partnerships-off-toggles.md",
      "pointer": false,
      "summary": "Notice delivery, estimating cap, W2 watch (modeled); runway floor (not modeled); the notes preview.",
      "next": "You + the attorney first; then one scoped PR per toggle.",
      "size": "M each",
      "blocker": "You + attorney.",
      "ver": "plan decision 6",
      "opinion": "your call — attorney-dependent, and nothing in the app is wrong without them.",
      "mockups": [
        "to-dos/partnerships-off-toggles-before-after.html"
      ],
      "artifacts": [],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "pipeline-cell-residuals",
      "group": "gated",
      "name": "Pipeline cell item 2: a visit report's 100%",
      "file": "to-dos/pipeline-cell-residuals.md",
      "pointer": false,
      "summary": "What the Where the Job Is train (v2.3416–v2.3421) left: date a report- or back-fill-sourced percent on the row (pct_set_at of any source), and whether a service-visit report's 100% should feed Job Summary (owner decision).",
      "next": "Pick a, b or c in the file: whole-job reports only · reports before the last Working entry are out of scope · leave it.",
      "size": "S",
      "blocker": "Your call (a / b / c).",
      "ver": "item 1 shipped v2.3432",
      "opinion": "build (pick b) — a service-visit report's 100% should not read as job-complete; reports before the last Working entry are out of scope, and it is S.",
      "mockups": [
        "to-dos/pipeline-cell-residuals-before-after.html"
      ],
      "artifacts": [],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "stage-plan-residuals",
      "group": "gated",
      "name": "Stage Plan: items 3–4",
      "file": "to-dos/stage-plan-residuals.md",
      "pointer": false,
      "summary": "What the Stage Plan train (v2.3083–v2.3134) left: capable-to-bill reading billable(), retiring offered_to_gc / bundles, plain rows on the final draw, the Any-done rule, the drawer's mint door.",
      "next": "Items 3–4 are yours — the final-draw sweep of plain rows, and an office-marked done.",
      "size": "S each",
      "blocker": "Both remaining items are owner calls.",
      "ver": "3 of 5 shipped",
      "opinion": "later — both are final-draw conveniences no one has asked for twice.",
      "mockups": [
        "to-dos/stage-plan-residuals-before-after.html"
      ],
      "artifacts": [],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "weekly-money-later",
      "group": "gated",
      "name": "Weekly Money phase 6",
      "file": "to-dos/weekly-money-later.md",
      "pointer": false,
      "summary": "Phase 6: drilldowns, GC lens, month roll-up, timeline feed, wider access.",
      "next": "Any of these wanted?",
      "size": "M",
      "blocker": "Optional, your call.",
      "ver": "plan phase 6",
      "opinion": "drop — drilldowns on a report read once a week; build the piece when someone names the question it answers.",
      "mockups": [
        "to-dos/weekly-money-later-before-after.html"
      ],
      "artifacts": [],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "unlinked-payments-on-multi-bill-jobs",
      "group": "gated",
      "name": "Which bill does an unlinked payment pay?",
      "file": "to-dos/unlinked-payments-on-multi-bill-jobs.md",
      "pointer": false,
      "summary": "Which bill does an unlinked payment pay? 191 payments worth $2.32M carry no invoice_id, and the two readers disagree in opposite directions: the invoice shows them on every open bill, the demand letter's claim counts none of them on a multi-bill job (a single-bill job counts them since v2.3515 — job 102 now reads $2,355). Three candidate rules; one kernel must answer for the invoice, the letter and the lien claim. The other half of Taunya's report — the bill-borrows-another-bill's-payment half — shipped as v2.3498.",
      "next": "Pick one of the three candidate rules in the file; then one kernel answers for the invoice's payment history, the demand letter's claim and the lien claim together. Also decide whether the 11 bills already sent with the old rendering are re-sent or corrected in place.",
      "size": "M once decided",
      "blocker": "An owner rule — guessing reintroduces the double credit v2.3498 removed.",
      "ver": "found at v2.3498 · single-bill half v2.3515",
      "opinion": "build — $2.32M of payments that two readers count differently is a lien-claim risk; pick a rule this week.",
      "mockups": [
        "to-dos/unlinked-payments-on-multi-bill-jobs-before-after.html"
      ],
      "artifacts": [],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "job-summary-follow-ups",
      "group": "waiting",
      "name": "Job Summary: what is left",
      "file": "to-dos/job-summary-follow-ups.md",
      "pointer": false,
      "summary": "What the Job Summary train left: overtime as its own Capacity slice and travel on Days both wait on ledger fields the day ledger does not carry; Crew P&L still credits gross bill by hours rather than the earned-revenue kernel the Jobs view reads since v2.3575.",
      "next": "Nothing until the day ledger carries per-person weekly hours (overtime) and per-session start times (travel). Crew P&L onto the kernel is a sitting when Crew P&L is next opened.",
      "size": "M each, gated",
      "blocker": "Ledger fields for items 2 and 4; a Crew P&L sitting for the kernel's other half.",
      "ver": "5 of 8 shipped · kernel v2.3575",
      "opinion": "later — nothing on Job Summary is wrong today; the two field additions follow the ledger, not the other way round.",
      "mockups": [
        "to-dos/job-summary-follow-ups-earned-revenue.html"
      ],
      "artifacts": [
        {
          "label": "design canvas",
          "url": "https://claude.ai/artifact/JHb3f7Tr7LVPfjMg6sdNLf"
        }
      ],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "journey-map-tier-1",
      "group": "waiting",
      "name": "Journey map: J31-N4",
      "file": "to-dos/journey-map-tier-1.md",
      "pointer": true,
      "summary": "Which drift rows are closed here; the list lives in the private repo.",
      "next": "Read _DRIFT-2 in the private repo first.",
      "size": "S",
      "blocker": "Private repo context.",
      "ver": "tiers 1–4 mostly closed",
      "opinion": "",
      "mockups": [],
      "artifacts": [],
      "mockup": "not-required",
      "mockupNote": ""
    },
    {
      "slug": "per-gc-bid-retirement",
      "group": "waiting",
      "name": "Per-GC bids: retire submitted_to / itb_links",
      "file": "to-dos/per-gc-bid-retirement.md",
      "pointer": false,
      "summary": "Retire bids.submitted_to / itb_links behind bid_gcs; the auto-derive question.",
      "next": "One mechanical PR after real per-GC usage.",
      "size": "M",
      "blocker": "Usage.",
      "ver": "v2.2416 base",
      "opinion": "later — a mechanical PR once real per-GC usage shows the two columns are dead.",
      "mockups": [],
      "artifacts": [],
      "mockup": "not-required",
      "mockupNote": "retires two columns — no screen changes"
    },
    {
      "slug": "person-identity-phase-e",
      "group": "waiting",
      "name": "Person identity phase E",
      "file": "to-dos/person-identity-phase-e.md",
      "pointer": false,
      "summary": "NOT NULL, re-PK off person_name, retire the name cascade — after a quiet quarter.",
      "next": "Revisit in December.",
      "size": "M",
      "blocker": "A quiet quarter.",
      "ver": "phases A–D done",
      "opinion": "later — a primary-key change on people in a busy quarter is risk without payoff; December as written.",
      "mockups": [],
      "artifacts": [],
      "mockup": "not-required",
      "mockupNote": "a schema change — no screen changes"
    },
    {
      "slug": "review-into-the-bridge",
      "group": "waiting",
      "name": "Review folds into the Bridge: step 3",
      "file": "to-dos/review-into-the-bridge.md",
      "pointer": false,
      "summary": "People → Review folds into the Bridge: one earned convention + the Vectors row as the door (v2.3360, v2.3366), retire Team Summary once the tables agree (gated). Teammates get money-free Needs You items only.",
      "next": "Re-check two more pay weeks; if they agree, ship the redirect.",
      "size": "M",
      "blocker": "Two more weeks.",
      "ver": "v2.3360 / 66 / 68",
      "opinion": "build — once two more pay weeks agree it is a redirect and a retirement, and it removes a duplicate surface people still open.",
      "mockups": [],
      "artifacts": [
        {
          "label": "Step Three, Redrawn",
          "url": "https://claude.ai/code/artifact/9c72e792-f8ea-43c9-8b92-6afca365c376"
        }
      ],
      "mockup": "not-required",
      "mockupNote": "step 3 is a redirect and a retirement once the tables agree — no new screen"
    },
    {
      "slug": "decomposition-residuals",
      "group": "residual",
      "name": "Decomposition residuals: the Workbench block, the picker sweep",
      "file": "to-dos/decomposition-residuals.md",
      "pointer": false,
      "summary": "What the two decomposition trains left on purpose: the Pricing tab's Workbench block (P2 — 1,975 lines over 77 state values, re-mapped into nine blocks in the architecture map, not worth cutting until a Workbench feature train needs a smaller file), the shared bid-picker sweep (~15 lines × fourteen tabs, a quiet-week mechanical PR), the L4 box components (18 props for 253 lines — the formulas were the duplication and they are one kernel now), and the optional renderStagesFieldAndBillingLines component on the Stages map.",
      "next": "Nothing scheduled. The Workbench cut starts as PR 1 of the next Workbench feature train, from the nine-block table in the map's P2 dossier; the picker sweep goes the next day the Bids surface has no open PR.",
      "size": "XS (sweep) · L (Workbench, only inside a feature train)",
      "blocker": "None. Each is a judgment about value, recorded in the map.",
      "ver": "closed 09-17",
      "opinion": "drop — left by decision; the Workbench cut only pays inside a Workbench feature train.",
      "mockups": [],
      "artifacts": [],
      "mockup": "not-required",
      "mockupNote": "refactors — no screen changes"
    },
    {
      "slug": "dispatch-residuals",
      "group": "residual",
      "name": "Dispatch residuals",
      "file": "to-dos/dispatch-residuals.md",
      "pointer": false,
      "summary": "Dispatch blocks / nudge history on the sheet rows, the tag-slice refresh. The phone-request self-heal shipped v2.3567 (the inbox sweep covers add_job_phone as it covers link_job_pictures).",
      "next": "The sheet-row history when the feed or the email log grows a per-sheet key; the tag-slice sum server-side.",
      "size": "S",
      "blocker": "None.",
      "ver": "from v2.2880 / 83 · item 1 v2.3567",
      "opinion": "later — the self-heal shipped; the two left wait on data the sheet rows do not carry yet.",
      "mockups": [],
      "artifacts": [],
      "mockup": "not-required",
      "mockupNote": "draw the sheet-row history when it is picked up"
    },
    {
      "slug": "robots-residuals",
      "group": "residual",
      "name": "Robots residuals (client side)",
      "file": "to-dos/robots-residuals.md",
      "pointer": false,
      "summary": "Client-side leftovers only; the twins program runs from docs/twins/HANDOFF.md.",
      "next": "The CI route / slug test (S).",
      "size": "S",
      "blocker": "CT-side work for the rest.",
      "ver": "program in HANDOFF",
      "opinion": "later — the CI route test is S but nothing is broken; fold it into the next twin PR.",
      "mockups": [],
      "artifacts": [],
      "mockup": "not-required",
      "mockupNote": "a CI route / slug test — no screen changes"
    },
    {
      "slug": "sub-payment-move-remove",
      "group": "residual",
      "name": "Sub payments — move or remove, the rest",
      "file": "to-dos/sub-payment-move-remove/README.md",
      "pointer": false,
      "summary": "A payment recorded on the wrong job can now be moved to the right one instead of deleted and retyped. Shipped for sub sheets (Jobs → Subs → Pay): every payment and backcharge row carries Edit · Move… · Remove, Move lists the same sub's other sheets first and previews both sheets' paid and owed, Remove asks why and can be undone for 30 days, and both sheets keep a grey trace line. Two pieces are left — carrying that trace to the sub's own portal so a sub does not phone about a payment that vanished, and putting the same Move to job… on customer payments in Edit Job, where only a sent bill may refuse the move.",
      "next": "PR 2 the portal trace (one edge function, no migration) — when a sub asks about a payment that vanished, or in a quiet hour. Someone runs one real move on a throwaway sheet and one on a throwaway job first.",
      "size": "S (PR 2)",
      "blocker": "None for PR 2. Three wording / policy calls in Open questions are the owner's and change one constant each.",
      "ver": "v2.3562 · v2.3576",
      "opinion": "later — both office doors are live; the portal trace can wait for a sub to ask.",
      "mockups": [
        "to-dos/sub-payment-move-remove/before-after.html"
      ],
      "artifacts": [
        {
          "label": "design canvas — Delete or move a payment",
          "url": "https://claude.ai/artifact/KevTT7eXyDAi4MENU5GAa8"
        }
      ],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "subs-residuals",
      "group": "residual",
      "name": "Subs residuals",
      "file": "to-dos/subs-residuals.md",
      "pointer": false,
      "summary": "Derived sheet stage (now unblocked), Spanish signature form, compliance chips, offer templates, benched subs in the sheet form, roster hygiene.",
      "next": "The bench flag (S); the Spanish pass with the next portal change.",
      "size": "S each",
      "blocker": "None.",
      "ver": "board polish done v2.3395",
      "opinion": "later — the bench flag is S; the Spanish pass rides with the next portal change.",
      "mockups": [],
      "artifacts": [],
      "mockup": "waiting",
      "mockupNote": ""
    },
    {
      "slug": "supply-house-credit-residuals",
      "group": "residual",
      "name": "Supply house credits: what the train left",
      "file": "to-dos/supply-house-credit-residuals.md",
      "pointer": false,
      "summary": "What the supply-house credits train left. The feature is done: a return is recorded as its own document with a negative amount and a document_kind, the aging table carries credits in their own column, and the two edges that would double-count a credit refuse it. One thing outlives it — pairing a credit to the invoice it credits, deferred until the office says it wants the field. The card-refund sign bug found alongside it shipped as v2.3519 / v2.3525.",
      "next": "Nothing urgent. Ask the office in a few weeks whether they reach for a pairing field.",
      "size": "S (pairing)",
      "blocker": "The pairing waits on real usage.",
      "ver": "v2.3500 · 3501 · 3502 · 3503 shipped",
      "opinion": "drop — pairing a credit to its invoice is a field nobody has reached for; build it the day someone does.",
      "mockups": [],
      "artifacts": [],
      "mockup": "waiting",
      "mockupNote": ""
    },
    {
      "slug": "supply-house-job-account-aging",
      "group": "residual",
      "name": "Supply houses: aging heat map + the Job accounts leftovers",
      "file": "to-dos/supply-house-job-account-aging.md",
      "pointer": false,
      "summary": "The May follow-ups (an editable Paid On date, Last Paid sortable); after the Job accounts train (v2.3423–v2.3440): Curly's missing phone, the Job Accounts tab rename question, a mark-all back-fill. The heat map's job-account line shipped v2.3568.",
      "next": "The two May follow-ups left — an editable Paid On date in the edit-invoice modal, Last Paid sortable on the summary table — in one sitting; Curly's phone is an office fix.",
      "size": "S",
      "blocker": "None.",
      "ver": "item 1 v2.3568 · items 4–6 added 09-14",
      "opinion": "later — the heat map is right now; the two May follow-ups are conveniences for a quiet hour.",
      "mockups": [
        "to-dos/supply-house-job-account-aging-before-after.html"
      ],
      "artifacts": [],
      "mockup": "has",
      "mockupNote": ""
    },
    {
      "slug": "what-customers-see-residuals",
      "group": "residual",
      "name": "What customers see — residuals",
      "file": "to-dos/what-customers-see-residuals.md",
      "pointer": false,
      "summary": "What the What-customers-see train left: a full sample matter on the law firm's portal (today the sample is the portal before its first matter), the signed-copy agreement email as its own step, and the Job window's Their journey door (the Customer page has it).",
      "next": "Any of the three in a quiet hour; the firm's sample matter is the largest (a fixture that satisfies parseLegalPortalPayload).",
      "size": "S each",
      "blocker": "None.",
      "ver": "shipped 09-16",
      "opinion": "later — the firm's sample matter is a fixture worth having before the next demo, not before.",
      "mockups": [],
      "artifacts": [],
      "mockup": "waiting",
      "mockupNote": ""
    }
  ]
}

export default data
