import { q, asRole, P } from './verify-lib.mjs'
const T = `'gc_draws','gc_draw_lines','gc_sow_line_reports','gc_change_order_trade_sends'`
const F = `'gc_sow_line_of','gc_draw_claim','gc_draw_money','gc_draw_came_in','gc_approve_draw','gc_approve_draw_less','gc_send_draw_back','gc_pay_draw','gc_draw_waiver_signed','gc_draw_waiver_in','gc_take_back_charge','gc_send_trade_change','gc_trade_sow_report','gc_trade_pay_app','gc_trade_unconditional_waiver','gc_trade_sign_change'`
await q('1a four tables, RLS, policies', `SELECT c.relname, c.relrowsecurity, (SELECT string_agg(polname, ',') FROM pg_policy WHERE polrelid = c.oid) AS policies FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace AND n.nspname = 'public' WHERE c.relname IN (${T}) ORDER BY 1;`)
await q('1b sixteen functions, invoker, callers', `SELECT p.proname, p.prosecdef AS definer, has_function_privilege('anon', p.oid, 'EXECUTE') AS anon_can, has_function_privilege('authenticated', p.oid, 'EXECUTE') AS signed_in_can, has_function_privilege('service_role', p.oid, 'EXECUTE') AS service_can FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace AND n.nspname = 'public' WHERE p.proname IN (${F}) ORDER BY p.proname;`)
await q('1b summary', `SELECT count(*) AS fns, bool_and(NOT prosecdef) AS all_invoker, bool_or(has_function_privilege('anon', oid, 'EXECUTE')) AS any_anon, count(*) FILTER (WHERE has_function_privilege('authenticated', oid, 'EXECUTE')) AS signed_in, count(*) FILTER (WHERE proname LIKE 'gc_trade_%' AND NOT has_function_privilege('authenticated', oid, 'EXECUTE') AND has_function_privilege('service_role', oid, 'EXECUTE')) AS trade_service_only FROM pg_proc WHERE proname IN (${F});`)
await q('1c constraints (expect credit_by_change_order + taken_draw_fkey, no amount_not_negative)', `SELECT conname FROM pg_constraint WHERE conname IN ('gc_sow_lines_credit_by_change_order', 'gc_sow_lines_amount_not_negative', 'gc_back_charges_taken_draw_fkey');`)
await q('2 signed SOWs on prod (step 2 needs one)', `SELECT id, project_id, signed_at FROM public.gc_sows WHERE signed_at IS NOT NULL LIMIT 3;`)
await q('2b draws rows after', `SELECT (SELECT count(*) FROM public.gc_draws) AS draws, (SELECT count(*) FROM public.gc_draw_lines) AS lines;`)
