import { q, asRole, P } from './verify-lib.mjs'
await q('1a the column, key (confdeltype n), index, triggers, linked count', `SELECT (SELECT data_type FROM information_schema.columns WHERE table_schema='public' AND table_name='gc_trade_packages' AND column_name='job_ledger_id') AS col_type, (SELECT string_agg(conname||':'||confdeltype::text, ',') FROM pg_constraint WHERE conrelid='public.gc_trade_packages'::regclass AND contype='f' AND conname LIKE '%job_ledger%') AS fk, (SELECT count(*) FROM pg_indexes WHERE indexname='gc_trade_packages_job_ledger_idx') AS idx, (SELECT string_agg(tgname, ',' ORDER BY tgname) FROM pg_trigger WHERE tgrelid='public.gc_trade_packages'::regclass AND NOT tgisinternal) AS triggers, (SELECT count(*) FROM public.gc_trade_packages WHERE job_ledger_id IS NOT NULL) AS linked;`)
await q('1b the two functions (expect gc_crew_on_site definer+stable, gc_link_crew_job invoker; anon false, signed-in true)', `SELECT p.proname, p.prosecdef AS definer, p.provolatile, has_function_privilege('anon', p.oid, 'EXECUTE') AS anon_can, has_function_privilege('authenticated', p.oid, 'EXECUTE') AS signed_in_can FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace AND n.nspname='public' WHERE p.proname IN ('gc_link_crew_job','gc_crew_on_site') ORDER BY 1;`)
await q('2a the count as a dev over a week (expect no rows; rolled back)', `BEGIN; ${asRole('dev')} SELECT count(*) AS rows FROM public.gc_crew_on_site('${P}', public.app_today() - 7, public.app_today()); ROLLBACK;`)
await q('2b the cap (expect Count at most 92 days at a time.; rolled back)', `BEGIN; ${asRole('dev')} SELECT count(*) FROM public.gc_crew_on_site('${P}', public.app_today() - 92, public.app_today()); ROLLBACK;`)
await q('3 the guard: a dev plain UPDATE on the test project own trade (expect the guard words 42501; rolled back)', `BEGIN; ${asRole('dev')} UPDATE public.gc_trade_packages SET job_ledger_id = (SELECT id FROM public.jobs_ledger WHERE NOT coalesce(billing_only,false) ORDER BY created_at DESC LIMIT 1) WHERE id = (SELECT id FROM public.gc_trade_packages WHERE project_id = '${P}' AND ours LIMIT 1); ROLLBACK;`)
await q('4 the link as a dev then the counts, all rolled back (expect a count row set, maybe empty)', `BEGIN; ${asRole('dev')} SELECT public.gc_link_crew_job((SELECT id FROM public.gc_trade_packages WHERE project_id = '${P}' AND ours LIMIT 1), (SELECT id FROM public.jobs_ledger WHERE NOT coalesce(billing_only,false) AND status = 'working' ORDER BY created_at DESC LIMIT 1)) AS linked; SELECT count(*) AS count_rows FROM public.gc_crew_on_site('${P}', public.app_today() - 7, public.app_today()); ROLLBACK;`)
await q('4b a hired trade refused in words (rolled back)', `BEGIN; ${asRole('dev')} SELECT public.gc_link_crew_job((SELECT id FROM public.gc_trade_packages WHERE project_id = '${P}' AND NOT ours LIMIT 1), (SELECT id FROM public.jobs_ledger WHERE NOT coalesce(billing_only,false) ORDER BY created_at DESC LIMIT 1)); ROLLBACK;`)
await q('5 linked after (expect 0)', `SELECT count(*) AS linked FROM public.gc_trade_packages WHERE job_ledger_id IS NOT NULL;`)
