/// <reference lib="webworker" />

import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching'
import { clientsClaim } from 'workbox-core'

declare let self: ServiceWorkerGlobalScope

// Precache all assets generated by the build
precacheAndRoute(self.__WB_MANIFEST)
cleanupOutdatedCaches()

// Take control when activated (prompt mode: skipWaiting only when client requests via message)
clientsClaim()

// Handle SKIP_WAITING message from client (when user clicks Reload to update)
self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') {
    self.skipWaiting()
  }
})

// Web Push: show notification when push message received
self.addEventListener('push', (event: PushEvent) => {
  const data = (event.data?.json() || {}) as { title?: string; body?: string; url?: string; tag?: string }
  const title = data.title || 'PipeTooling'
  const options = {
    body: data.body,
    icon: '/favicon.svg',
    data: { url: data.url },
    tag: data.tag || 'workflow',
    renotify: true,
  } as NotificationOptions
  event.waitUntil(self.registration.showNotification(title, options))
})

// Web Push: open app when notification is clicked
self.addEventListener('notificationclick', (event: NotificationEvent) => {
  event.notification.close()
  const url = (event.notification.data?.url as string) || '/'
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      for (const client of clientList) {
        if (client.url === url || client.url.startsWith(new URL(url).origin)) {
          client.focus()
          client.navigate(url)
          return
        }
      }
      if (self.clients.openWindow) {
        return self.clients.openWindow(url)
      }
    })
  )
})
